const DAYS_DATA_PART3 = [
  {
    day: 41,
    topic: "Điện tử",
    topicEn: "Electronics",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Nghe mô tả hành động (Listening - Mô tả hành động)",
      explanation: "Trong phần nghe TOEIC Part 1, bạn sẽ nghe mô tả về hành động đang diễn ra trong hình ảnh. Hãy chú ý đến: 1) Ai đang làm gì (chủ ngữ + động từ), 2) Đồ vật ở đâu, đang được sử dụng thế nào. Thường dùng thì hiện tại tiếp diễn (is/are + V-ing) để mô tả hành động đang xảy ra.",
      structure: "Subject + is/are + V-ing + Object",
      examples: ["The man is plugging in the charger.", "She is adjusting the settings on the monitor.", "They are recording a video with a camera.", "The technician is checking the circuit board."],
      exceptions: [],
      notes: [],
      tips: "Khi nghe mô tả hành động, tập trung vào ĐỘNG TỪ chính. Phân biệt các hành động tương tự nhau: plugging in ≠ unplugging, turning on ≠ turning off."
    },
    words: [
      {word:'integrated circuit', ipa:'/ˈɪntɪɡreɪtɪd ˈsɜːrkɪt/', meaning:'mạch tích hợp (IC)', type:'noun', example:'Chips contain integrated circuits.', viAnswers:['mạch tích hợp', 'IC']},
      {word:'semiconductor', ipa:'/ˌsemikənˈdʌktər/', meaning:'chất bán dẫn', type:'noun', example:'Semiconductors are essential for microchips.', viAnswers:['chất bán dẫn']},
      {word:'processor', ipa:'/ˈprɑːsesər/', meaning:'bộ vi xử lý', type:'noun', example:'The device features a quad-core processor.', viAnswers:['bộ xử lý', 'bộ vi xử lý']},
      {word:'component', ipa:'/kəmˈpoʊnənt/', meaning:'linh kiện, thành phần', type:'noun', example:'Check the electronic components.', viAnswers:['linh kiện', 'thành phần']},
      {word:'transistor', ipa:'/trænˈzɪstər/', meaning:'bóng bán dẫn', type:'noun', example:'Modern chips contain billions of transistors.', viAnswers:['bóng bán dẫn']},
      {word:'automation', ipa:'/ˌɔːtəˈmeɪʃən/', meaning:'sự tự động hóa', type:'noun', example:'Industrial automation increases efficiency.', viAnswers:['tự động hóa', 'sự tự động hóa']},
      {word:'sensor', ipa:'/ˈsensər/', meaning:'cảm biến', type:'noun', example:'The phone has a light sensor.', viAnswers:['cảm biến']},
      {word:'interface', ipa:'/ˈɪntərfeɪs/', meaning:'giao diện', type:'noun / verb', example:'The user interface is intuitive.', viAnswers:['giao diện']},
      {word:'compatibility', ipa:'/kəmˌpætəˈbɪləti/', meaning:'tính tương thích', type:'noun', example:'Check hardware compatibility.', viAnswers:['tương thích', 'tính tương thích']},
      {word:'obsolescence', ipa:'/ˌɑːbsəˈlesəns/', meaning:'sự lỗi thời, sự không còn dùng', type:'noun', example:'Plan for product obsolescence.', viAnswers:['sự lỗi thời', 'lỗi thời']},
      {word:'firmware', ipa:'/ˈfɜːrmwer/', meaning:'phần sụn, phần mềm hệ thống', type:'noun', example:'Download the firmware update.', viAnswers:['phần sụn', 'firmware']},
      {word:'frequency', ipa:'/ˈfriːkwənsi/', meaning:'tần số, sự thường xuyên', type:'noun', example:'The processor operates at high frequency.', viAnswers:['tần số']},
      {word:'prototype', ipa:'/ˈproʊtətaɪp/', meaning:'mẫu đầu tiên, nguyên mẫu', type:'noun', example:'The prototype device is being tested.', viAnswers:['nguyên mẫu', 'mẫu thử']},
      {word:'specifications', ipa:'/ˌspesəfɪˈkeɪʃənz/', meaning:'thông số kỹ thuật', type:'noun', example:'The specs are detailed.', viAnswers:['thông số', 'thông số kỹ thuật']},
      {word:'calibrate', ipa:'/ˈkælɪbreɪt/', meaning:'hiệu chuẩn, chỉnh thông số chính xác', type:'verb', example:'The scales need to be calibrated.', viAnswers:['hiệu chuẩn']},
      {word:'patent', ipa:'/ˈpætənt/', meaning:'bằng sáng chế', type:'noun', example:'They secured a patent for the chip design.', viAnswers:['bằng sáng chế']},
      {word:'voltage', ipa:'/ˈvoʊltɪdʒ/', meaning:'điện áp', type:'noun', example:'High voltage can damage the device.', viAnswers:['điện áp', 'hiệu điện thế']},
      {word:'bandwidth', ipa:'/ˈbændwɪtθ/', meaning:'băng thông', type:'noun', example:'The connection has high bandwidth.', viAnswers:['băng thông']},
      {word:'telecommunications', ipa:'/ˌtelɪkəˌmjuːnɪˈkeɪʃənz/', meaning:'viễn thông', type:'noun', example:'He works in telecommunications.', viAnswers:['viễn thông', 'ngành viễn thông']},
      {word:'manual', ipa:'/ˈmænjuəl/', meaning:'sách hướng dẫn sử dụng, thủ công', type:'noun / adjective', example:'Read the user manual.', viAnswers:['sách hướng dẫn', 'thủ công']},
      {word:'assembly', ipa:'/əˈsembli/', meaning:'lắp ráp, hội đồng', type:'noun', example:'The assembly line is automated.', viAnswers:['lắp ráp', 'hội đồng']},
      {word:'configuration', ipa:'/kənˌfɪɡjəˈreɪʃən/', meaning:'sự cấu hình, thiết lập cấu hình', type:'noun', example:'Check the system configuration.', viAnswers:['cấu hình', 'thiết lập']}
    ]
  },

  {
    day: 42,
    topic: "Hợp đồng / Pháp lý",
    topicEn: "Contracts / Legal",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Nghe hội thoại (Listening - Hội thoại)",
      explanation: "Trong TOEIC Part 3, bạn sẽ nghe đoạn hội thoại giữa 2-3 người. Mẹo: 1) Đọc câu hỏi TRƯỚC khi nghe, 2) Chú ý ai nói gì - phân biệt người nói, 3) Nghe từ khóa để trả lời câu hỏi về: mục đích cuộc hội thoại, chi tiết cụ thể, hành động tiếp theo.",
      structure: "Nghe → Xác định: Who? What? Where? Why? What next?",
      examples: ["A: Have you signed the contract yet? B: Not yet. I need to review it first.", "A: When does the agreement expire? B: It expires next month.", "A: We should negotiate better terms. B: I agree. Let's set up a meeting."],
      exceptions: [],
      notes: [],
      tips: "Trước khi nghe, đọc lướt câu hỏi và các đáp án. Gạch chân từ khóa trong câu hỏi. Khi nghe, tập trung vào từ khóa đó."
    },
    words: [
      {word:'arbitration', ipa:'/ˌɑːrbɪˈtreɪʃən/', meaning:'sự phân xử, sự trọng tài', type:'noun', example:'The dispute was settled by arbitration.', viAnswers:['trọng tài', 'phân xử', 'sự phân xử']},
      {word:'litigation', ipa:'/ˌlɪtɪˈɡeɪʃən/', meaning:'sự kiện tụng, kiện cáo', type:'noun', example:'We hope to avoid costly litigation.', viAnswers:['kiện tụng', 'sự kiện tụng', 'tranh chấp']},
      {word:'compliance', ipa:'/kəmˈplaɪəns/', meaning:'sự tuân thủ luật pháp', type:'noun', example:'The audit checks for regulatory compliance.', viAnswers:['tuân thủ', 'sự tuân thủ']},
      {word:'liability', ipa:'/ˌlaɪəˈbɪləti/', meaning:'trách nhiệm pháp lý, nghĩa vụ nợ', type:'noun', example:'The company has limited liability.', viAnswers:['trách nhiệm pháp lý', 'nghĩa vụ']},
      {word:'indemnity', ipa:'/ɪnˈdemnəti/', meaning:'sự bồi thường, sự bảo đảm bồi thường', type:'noun', example:'The contract includes an indemnity clause.', viAnswers:['bồi thường', 'sự bồi thường']},
      {word:'breach', ipa:'/briːtʃ/', meaning:'vi phạm (hợp đồng), sự phá vỡ', type:'noun / verb', example:'They sued for breach of contract.', viAnswers:['vi phạm', 'sự vi phạm']},
      {word:'provision', ipa:'/prəˈvɪʒən/', meaning:'điều khoản quy định, sự cung cấp', type:'noun', example:'Under the provisions of the treaty, trade is free.', viAnswers:['điều khoản', 'quy định']},
      {word:'covenant', ipa:'/ˈkʌvənənt/', meaning:'cam ước, lời cam kết chính thức', type:'noun / verb', example:'The lease contains a covenant to keep the premises in repair.', viAnswers:['cam kết', 'lời cam kết']},
      {word:'null and void', ipa:'/nʌl ənd vɔɪd/', meaning:'vô hiệu, không có hiệu lực pháp lý', type:'adjective phrase', example:'The contract was declared null and void.', viAnswers:['vô hiệu', 'không có hiệu lực']},
      {word:'solicitor', ipa:'/səˈlɪsɪtər/', meaning:'luật sư tư vấn, luật sư đại diện', type:'noun', example:'Consult a solicitor before signing.', viAnswers:['luật sư', 'luật sư tư vấn']},
      {word:'notary public', ipa:'/ˌnoʊtəri ˈpʌblɪk/', meaning:'công chứng viên', type:'noun', example:'The signature must be witnessed by a notary public.', viAnswers:['công chứng viên']},
      {word:'clause', ipa:'/klɔːz/', meaning:'điều khoản', type:'noun', example:'Read the liability clause.', viAnswers:['điều khoản']},
      {word:'amendment', ipa:'/əˈmendmənt/', meaning:'sự sửa đổi, bổ sung (hợp đồng, luật)', type:'noun', example:'They proposed an amendment to the contract.', viAnswers:['sửa đổi', 'bổ sung', 'sự sửa đổi']},
      {word:'validity', ipa:'/vəˈlɪdəti/', meaning:'hiệu lực pháp lý, tính hợp lệ', type:'noun', example:'We questioned the validity of the contract.', viAnswers:['hiệu lực', 'tính hợp lệ', 'hợp lệ']},
      {word:'enforce', ipa:'/ɪnˈfɔːrs/', meaning:'bắt buộc thực thi, thi hành', type:'verb', example:'The police enforce the law.', viAnswers:['thi hành', 'thực thi', 'bắt buộc']},
      {word:'party', ipa:'/ˈpɑːrti/', meaning:'bên tham gia ký kết', type:'noun', example:'Both parties agreed to the terms.', viAnswers:['bên', 'đối tác']},
      {word:'negotiate', ipa:'/nɪˈɡoʊʃieɪt/', meaning:'đàm phán', type:'verb', example:'Negotiating a contract takes patience.', viAnswers:['đàm phán']},
      {word:'terminate', ipa:'/ˈtɜːrməneɪt/', meaning:'chấm dứt', type:'verb', example:'They decided to terminate the contract.', viAnswers:['chấm dứt']},
      {word:'jurisdiction', ipa:'/ˌdʒʊrɪsˈdɪkʃən/', meaning:'quyền tài phán, thẩm quyền pháp lý', type:'noun', example:'The case is under our jurisdiction.', viAnswers:['thẩm quyền', 'quyền tài phán']},
      {word:'execute', ipa:'/ˈeksɪkjuːt/', meaning:'ký kết thi hành (hợp đồng), thực hiện', type:'verb', example:'The contract was executed yesterday.', viAnswers:['ký kết', 'thực hiện', 'thi hành']},
      {word:'binding', ipa:'/ˈbaɪndɪŋ/', meaning:'có tính ràng buộc pháp lý', type:'adjective', example:'The agreement is legally binding.', viAnswers:['ràng buộc', 'có tính ràng buộc']},
      {word:'attorney', ipa:'/əˈtɜːrni/', meaning:'luật sư', type:'noun', example:'The attorney advised us to settle.', viAnswers:['luật sư']}
    ]
  },

  {
    day: 43,
    topic: "Sự kiện",
    topicEn: "Events",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Nghe thông báo (Listening - Thông báo / Talks)",
      explanation: "Trong TOEIC Part 4, bạn sẽ nghe một người nói (thông báo, quảng cáo, tin nhắn thoại, bài phát biểu). Mẹo: 1) Xác định LOẠI thông báo (announcement, advertisement, voicemail...), 2) Nghe mục đích chính, 3) Chú ý các chi tiết: thời gian, địa điểm, yêu cầu hành động.",
      structure: "Nghe → Xác định: Loại thông báo? Mục đích? Chi tiết quan trọng?",
      examples: ["Attention all guests, the ceremony will begin at 3 PM in the main hall.", "Please note that the exhibition has been moved to the second floor.", "We are pleased to announce the opening of our new conference center."],
      exceptions: [],
      notes: [],
      tips: "Thông báo thường bắt đầu bằng: Attention please, We are pleased to announce, Please note that... Hãy nghe kỹ phần đầu để biết chủ đề chính."
    },
    words: [
      {word:'banquet', ipa:'/ˈbæŋkwɪt/', meaning:'tiệc lớn, quốc yến', type:'noun', example:'An awards banquet was held at the hotel.', viAnswers:['tiệc lớn', 'ban yến']},
      {word:'coordinator', ipa:'/koʊˈɔːrdɪneɪtər/', meaning:'người điều phối', type:'noun', example:'Talk to the events coordinator.', viAnswers:['điều phối viên', 'người điều phối']},
      {word:'registration', ipa:'/ˌredʒɪˈstreɪʃən/', meaning:'sự đăng ký, quầy đăng ký', type:'noun', example:'Registration begins at 8 AM.', viAnswers:['đăng ký', 'sự đăng ký']},
      {word:'keynote speaker', ipa:'/ˈkiːnoʊt ˈspiːkər/', meaning:'diễn giả chính', type:'noun', example:'The keynote speaker was inspiring.', viAnswers:['diễn giả chính']},
      {word:'exhibition', ipa:'/ˌeksəˈbɪʃən/', meaning:'triển lãm', type:'noun', example:'We set up a booth at the exhibition.', viAnswers:['triển lãm']},
      {word:'itinerary', ipa:'/aɪˈtɪnəreri/', meaning:'lộ trình, lịch trình chuyến đi', type:'noun', example:'Check the travel itinerary.', viAnswers:['lộ trình', 'lịch trình']},
      {word:'hospitality', ipa:'/ˌhɑːspɪˈtæləti/', meaning:'sự hiếu khách, ngành nhà hàng khách sạn', type:'noun', example:'We appreciated the warm hospitality.', viAnswers:['hiếu khách', 'ngành khách sạn', 'sự hiếu khách']},
      {word:'catering', ipa:'/ˈkeɪtərɪŋ/', meaning:'dịch vụ cung cấp tiệc ăn uống', type:'noun', example:'Who is handling the catering?', viAnswers:['cung cấp tiệc', 'ăn uống']},
      {word:'facilitator', ipa:'/fəˈsɪlɪteɪtər/', meaning:'người hỗ trợ, điều phối viên hội thảo', type:'noun', example:'The facilitator led the workshop.', viAnswers:['người hỗ trợ', 'điều phối viên']},
      {word:'delegate', ipa:'/ˈdelɪɡət/, /ˈdelɪɡeɪt/', meaning:'đại biểu, giao phó việc', type:'noun / verb', example:'Hundreds of delegates attended the summit.', viAnswers:['đại biểu', 'giao phó']},
      {word:'symposium', ipa:'/sɪmˈpoʊziəm/', meaning:'hội thảo khoa học', type:'noun', example:'The symposium focused on climate change.', viAnswers:['hội thảo', 'hội thảo khoa học']},
      {word:'panel', ipa:'/ˈpænəl/', meaning:'ban chuyên gia, bảng điều khiển, hội đồng', type:'noun', example:'A panel of experts discussed the issue.', viAnswers:['ban chuyên gia', 'hội đồng']},
      {word:'sponsor', ipa:'/ˈspɑːnsər/', meaning:'nhà tài trợ, tài trợ', type:'noun / verb', example:'The event is sponsored by local brands.', viAnswers:['tài trợ', 'nhà tài trợ']},
      {word:'logistics', ipa:'/lɒˈdʒɪstɪks/', meaning:'công tác hậu cần, logistics', type:'noun', example:'The logistics of the event are complex.', viAnswers:['hậu cần', 'logistics']},
      {word:'reception', ipa:'/rɪˈsepʃən/', meaning:'tiệc chiêu đãi, sự tiếp nhận', type:'noun', example:'The wedding reception was at a winery.', viAnswers:['tiệc chiêu đãi', 'sự tiếp nhận', 'lễ tân']},
      {word:'networking', ipa:'/ˈnetwɜːrkɪŋ/', meaning:'việc kết nối giao lưu, thiết lập mạng lưới', type:'noun', example:'Conferences are great for networking.', viAnswers:['kết nối', 'giao lưu']},
      {word:'commemorate', ipa:'/kəˈmeməreɪt/', meaning:'kỷ niệm, tưởng niệm', type:'verb', example:'A banquet was held to commemorate the anniversary.', viAnswers:['kỷ niệm', 'tưởng niệm']},
      {word:'souvenir', ipa:'/ˌsuːvəˈnɪr/', meaning:'quà lưu niệm', type:'noun', example:'I bought a souvenir at the museum.', viAnswers:['quà lưu niệm']},
      {word:'accommodation', ipa:'/əˌkɑːməˈdeɪʃən/', meaning:'chỗ ở, phòng nghỉ', type:'noun', example:'The ticket price includes accommodation.', viAnswers:['chỗ ở', 'phòng nghỉ']},
      {word:'brochure', ipa:'/broʊˈʃʊr/', meaning:'tờ gấp quảng cáo', type:'noun', example:'We sent brochures to clients.', viAnswers:['sách quảng cáo', 'tờ rơi']},
      {word:'attendee', ipa:'/əˌtenˈdiː/', meaning:'người tham dự', type:'noun', example:'Each attendee received a gift bag.', viAnswers:['người tham dự']},
      {word:'venue', ipa:'/ˈvenjuː/', meaning:'địa điểm', type:'noun', example:'The venue is easy to find.', viAnswers:['địa điểm']}
    ]
  },

  {
    day: 44,
    topic: "Nông nghiệp / Thiên nhiên",
    topicEn: "Agriculture / Nature",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Tổng ôn nghe (Listening - Tổng hợp)",
      explanation: "Tổng ôn tất cả kỹ năng nghe TOEIC: Part 1 (mô tả hình ảnh), Part 2 (hỏi-đáp), Part 3 (hội thoại), Part 4 (bài nói). Quy trình làm bài nghe hiệu quả: 1) Đọc trước câu hỏi và đáp án, 2) Gạch chân từ khóa, 3) Nghe và chọn đáp án ngay, 4) Không dừng lại ở câu khó - đi tiếp.",
      structure: "Part 1: Hình ảnh → Part 2: Hỏi-đáp → Part 3: Hội thoại → Part 4: Bài nói",
      examples: ["Part 1: The farmer is planting seeds in the field.", "Part 2: When is the harvest season? - It starts in September.", "Part 3: A: How is the crop this year? B: It is better than last year.", "Part 4: Due to the drought, water usage will be limited."],
      exceptions: [],
      notes: [],
      tips: "Luyện nghe mỗi ngày 15-30 phút. Nghe đi nghe lại nhiều lần. Lần 1: nghe hiểu ý chính. Lần 2: nghe chi tiết. Lần 3: nghe và đọc transcript."
    },
    words: [
      {word:'agriculture', ipa:'/ˈæɡrɪkʌltʃər/', meaning:'nông nghiệp', type:'noun', example:'Agriculture is the main industry here.', viAnswers:['nông nghiệp']},
      {word:'harvest', ipa:'/ˈhɑːrvɪst/', meaning:'vụ mùa, thu hoạch', type:'noun / verb', example:'Farmers expect a good harvest.', viAnswers:['thu hoạch', 'vụ mùa']},
      {word:'fertilizer', ipa:'/ˈfɜːrtəlaɪzər/', meaning:'phân bón', type:'noun', example:'We use organic fertilizers.', viAnswers:['phân bón']},
      {word:'pesticide', ipa:'/ˈpestɪsaɪd/', meaning:'thuốc trừ sâu', type:'noun', example:'Pesticides protect crops from insects.', viAnswers:['thuốc trừ sâu']},
      {word:'cultivate', ipa:'/ˈkʌltɪveɪt/', meaning:'gieo trồng, vun quén', type:'verb', example:'They cultivate rice in this region.', viAnswers:['gieo trồng', 'vun trồng']},
      {word:'irrigation', ipa:'/ˌɪrɪˈɡeɪʃən/', meaning:'sự tưới tiêu', type:'noun', example:'An irrigation system was built.', viAnswers:['tưới tiêu', 'sự tưới tiêu']},
      {word:'organic', ipa:'/ɔːrˈɡænɪk/', meaning:'hữu cơ', type:'adjective', example:'Organic food is popular.', viAnswers:['hữu cơ']},
      {word:'livestock', ipa:'/ˈlaɪvstɑːk/', meaning:'gia súc, vật nuôi', type:'noun', example:'The farm raises livestock.', viAnswers:['gia súc', 'vật nuôi']},
      {word:'forestry', ipa:'/ˈfɔːrɪstri/', meaning:'lâm nghiệp', type:'noun', example:'He studied forestry.', viAnswers:['lâm nghiệp']},
      {word:'commodity', ipa:'/kəˈmɑːdəti/', meaning:'hàng hóa nguyên liệu/thương phẩm', type:'noun', example:'Agricultural commodities include wheat and coffee.', viAnswers:['hàng hóa', 'thương phẩm']},
      {word:'sustainability', ipa:'/səˌsteɪnəˈbɪləti/', meaning:'bền vững', type:'noun', example:'Focus on farming sustainability.', viAnswers:['sự bền vững', 'bền vững']},
      {word:'ecology', ipa:'/iˈkɑːlədʒi/', meaning:'sinh thái học', type:'noun', example:'Study the ecology of the forest.', viAnswers:['sinh thái', 'sinh thái học']},
      {word:'conservation', ipa:'/ˌkɑːnsərˈveɪʃən/', meaning:'sự bảo tồn', type:'noun', example:'Soil conservation is important.', viAnswers:['bảo tồn', 'sự bảo tồn']},
      {word:'arable', ipa:'/ˈærəbəl/', meaning:'có thể trồng trọt được (đất)', type:'adjective', example:'Vietnam has much arable land.', viAnswers:['trồng trọt được', 'màu mỡ']},
      {word:'yield', ipa:'/jiːld/', meaning:'sản lượng, lợi suất', type:'noun / verb', example:'Crop yields increased this year.', viAnswers:['sản lượng', 'lợi suất']},
      {word:'erosion', ipa:'/ɪˈroʊʒən/', meaning:'sự xói mòn', type:'noun', example:'Soil erosion is a serious problem.', viAnswers:['xói mòn', 'sự xói mòn']},
      {word:'deforestation', ipa:'/ˌdiːˌfɔːrɪˈsteɪʃən/', meaning:'sự phá rừng', type:'noun', example:'Deforestation causes climate issues.', viAnswers:['phá rừng', 'sự phá rừng']},
      {word:'wildlife', ipa:'/ˈwaɪldlaɪf/', meaning:'động vật hoang dã', type:'noun', example:'Protect local wildlife.', viAnswers:['động vật hoang dã']},
      {word:'produce', ipa:'/ˈproʊduːs/, /prəˈduːs/', meaning:'nông sản, sản xuất', type:'noun / verb', example:'Fresh produce is sold at the market.', viAnswers:['nông sản', 'sản xuất']},
      {word:'export', ipa:'/ˈekspɔːrt/', meaning:'xuất khẩu', type:'verb / noun', example:'We export agricultural goods.', viAnswers:['xuất khẩu']},
      {word:'subsidy', ipa:'/ˈsʌbsədi/', meaning:'tiền trợ cấp (của chính phủ)', type:'noun', example:'Farmers receive agricultural subsidies.', viAnswers:['trợ cấp', 'tiền trợ cấp']},
      {word:'arboriculture', ipa:'/ˈɑːrbərɪkʌltʃər/', meaning:'ngành trồng và chăm sóc cây thân gỗ', type:'noun', example:'He is an expert in arboriculture.', viAnswers:['trồng cây xanh']}
    ]
  },

  {
    day: 45,
    topic: "Chính sách / Quy trình",
    topicEn: "Policies / Procedures",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Chọn từ loại (Word Forms)",
      explanation: "Trong TOEIC Part 5, bạn cần chọn từ loại đúng để điền vào chỗ trống. Cách nhận biết từ loại: 1) DANH TỪ (noun): đứng sau a/an/the, sau tính từ - đuôi: -tion, -ment, -ness, -ity, -ance. 2) ĐỘNG TỪ (verb): đứng sau chủ ngữ - đuôi: -ize, -ify, -ate. 3) TÍNH TỪ (adjective): đứng trước danh từ, sau be - đuôi: -ful, -less, -ive, -able, -ous. 4) TRẠNG TỪ (adverb): bổ nghĩa cho động từ, tính từ - đuôi: -ly.",
      structure: "Nhìn vị trí chỗ trống → Xác định cần từ loại gì → Chọn đáp án đúng từ loại",
      examples: ["The company will ___ the new policy. (implement - verb)", "The ___ of the new rule is important. (implementation - noun)", "We need ___ guidelines. (regulatory - adjective)", "The policy was ___ enforced. (strictly - adverb)"],
      exceptions: ["Cần điền Trạng từ chứ không phải Tính từ khi chỗ trống đứng trước cụm Tính từ + Danh từ bổ nghĩa: <code>Mạo từ + Trạng từ + Tính từ + Danh từ</code>.", "Bẫy phân biệt danh từ chỉ người và danh từ chỉ vật (ví dụ: <i>representative</i> - người đại diện vs. <i>representation</i> - sự đại diện)."],
      notes: ["Nguyên tắc vàng làm bài từ loại: Nhìn 1 từ ngay <b>trước</b> và 1 từ ngay <b>sau</b> khoảng trống để xác định loại từ cần điền, sau đó dùng đuôi từ loại để chọn nhanh đáp án."],
      tips: "Học thuộc các đuôi từ phổ biến: -tion (noun), -ly (adverb), -ive (adjective), -ize (verb). Khi làm bài, nhìn VỊ TRÍ chỗ trống trước, rồi mới nhìn đáp án."
    },
    words: [
      {word:'protocol', ipa:'/ˈproʊtəkɑːl/', meaning:'nghi thức ngoại giao, giao thức, quy trình chuẩn', type:'noun', example:'Follow the safety protocol.', viAnswers:['quy trình', 'giao thức', 'nghi thức']},
      {word:'compliance', ipa:'/kəmˈplaɪəns/', meaning:'sự tuân thủ đúng quy chuẩn', type:'noun', example:'Compliance audits are scheduled annually.', viAnswers:['tuân thủ', 'sự tuân thủ']},
      {word:'regulation', ipa:'/ˌreɡjəˈloʊʃən/', meaning:'quy định, điều lệ', type:'noun', example:'Government regulations protect workers.', viAnswers:['quy định', 'điều lệ']},
      {word:'guideline', ipa:'/ˈɡaɪdlaɪn/', meaning:'nguyên tắc chỉ đạo, hướng dẫn', type:'noun', example:'The board issued new guidelines.', viAnswers:['hướng dẫn', 'nguyên tắc']},
      {word:'enforce', ipa:'/ɪnˈfɔːrs/', meaning:'thực thi, bắt buộc', type:'verb', example:'We enforce strict safety policies.', viAnswers:['thực thi', 'thành lập', 'bắt buộc']},
      {word:'amendment', ipa:'/əˈmendmənt/', meaning:'sự bổ sung, sửa đổi', type:'noun', example:'Read the amendment to the handbook.', viAnswers:['sửa đổi', 'bổ sung']},
      {word:'standardization', ipa:'/ˌstændərdaɪˈzeɪʃən/', meaning:'sự tiêu chuẩn hóa', type:'noun', example:'Standardization improves efficiency.', viAnswers:['tiêu chuẩn hóa', 'sự tiêu chuẩn hóa']},
      {word:'implement', ipa:'/ˈɪmplɪment/', meaning:'thực hiện, áp dụng thi hành', type:'verb', example:'We will implement the new policy next week.', viAnswers:['thực hiện', 'áp dụng', 'thi hành']},
      {word:'supervision', ipa:'/ˌsuːpərˈvɪʒən/', meaning:'sự giám sát', type:'noun', example:'Under the supervision of the manager.', viAnswers:['giám sát', 'sự giám sát']},
      {word:'authorization', ipa:'/ˌɔːθəraɪˈzeɪʃən/', meaning:'sự cho phép, cấp quyền chính thức', type:'noun', example:'You need written authorization.', viAnswers:['cho phép', 'sự cho phép', 'ủy quyền']},
      {word:'mandatory', ipa:'/ˈmændətɔːri/', meaning:'bắt buộc', type:'adjective', example:'Attendance at the meeting is mandatory.', viAnswers:['bắt buộc']},
      {word:'code of conduct', ipa:'/koʊd əv ˈkɑːndʌkt/', meaning:'quy tắc ứng xử', type:'noun', example:'Read the code of conduct.', viAnswers:['quy tắc ứng xử']},
      {word:'standard operating procedure', ipa:'/ˈstændərd ˈɑːpəreɪtɪŋ prəˈsiːdʒər/', meaning:'quy trình vận hành tiêu chuẩn (SOP)', type:'noun', example:'Follow the SOP.', viAnswers:['SOP', 'quy trình tiêu chuẩn']},
      {word:'administrative', ipa:'/ədˈmɪnɪstreɪtɪv/', meaning:'thuộc hành chính/quản trị', type:'adjective', example:'He handles administrative duties.', viAnswers:['hành chính', 'quản trị']},
      {word:'manual', ipa:'/ˈmænjuəl/', meaning:'sách hướng dẫn', type:'noun', example:'Consult the policy manual.', viAnswers:['sách hướng dẫn']},
      {word:'credential', ipa:'/krəˈdenʃəl/', meaning:'chứng chỉ năng lực, giấy chứng nhận', type:'noun', example:'Check the applicant\'s credentials.', viAnswers:['chứng chỉ', 'giấy chứng nhận', 'bằng cấp']},
      {word:'non-compliance', ipa:'/ˌnɒn kəmˈplaɪəns/', meaning:'sự không tuân thủ quy định', type:'noun', example:'Non-compliance leads to fines.', viAnswers:['không tuân thủ', 'sự không tuân thủ']},
      {word:'restriction', ipa:'/rɪˈstrɪkʃən/', meaning:'sự hạn chế, giới hạn', type:'noun', example:'There are travel restrictions.', viAnswers:['hạn chế', 'sự hạn chế']},
      {word:'clause', ipa:'/klɔːz/', meaning:'điều khoản', type:'noun', example:'The confidentiality clause is important.', viAnswers:['điều khoản']},
      {word:'violation', ipa:'/ˌvaɪəˈleɪʃən/', meaning:'sự vi phạm', type:'noun', example:'Any violation results in termination.', viAnswers:['vi phạm', 'sự vi phạm']},
      {word:'confidentiality', ipa:'/ˌkɑːnfɪˌdenʃiˈæləti/', meaning:'sự bảo mật, tính bảo mật', type:'noun', example:'Sign the confidentiality agreement.', viAnswers:['bảo mật', 'sự bảo mật']},
      {word:'oversight', ipa:'/ˈoʊvərsaɪt/', meaning:'sự giám sát sơ suất, sự bỏ quên', type:'noun', example:'The error was a minor oversight.', viAnswers:['sơ suất', 'giám sát']}
    ]
  },

  {
    day: 46,
    topic: "Đào tạo",
    topicEn: "Training",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Thì động từ (Verb Tenses)",
      explanation: "Trong TOEIC Part 5, bạn cần chọn thì động từ đúng. Các dấu hiệu nhận biết: 1) Hiện tại đơn: always, usually, every day, often. 2) Quá khứ đơn: yesterday, last week, ago, in 2020. 3) Hiện tại hoàn thành: since, for, already, yet, recently. 4) Tương lai: tomorrow, next week, will, be going to. 5) Hiện tại tiếp diễn: now, currently, at the moment.",
      structure: "Tìm dấu hiệu thời gian → Chọn thì phù hợp",
      examples: ["The training program ___ last month. (started - quá khứ đơn, vì 'last month')", "She ___ three courses since January. (has completed - hiện tại hoàn thành, vì 'since')", "The workshop ___ every Friday. (takes place - hiện tại đơn, vì 'every Friday')", "They ___ a new program next year. (will launch - tương lai, vì 'next year')"],
      exceptions: ["Sự hòa hợp các thì trong câu có <b>since</b>: Mệnh đề chứa <i>since</i> chia ở thì <b>Quá khứ đơn</b>, mệnh đề chính chia ở thì <b>Hiện tại hoàn thành</b> (ví dụ: <i>We have grown since he joined us</i>).", "Khi hành động đang xảy ra (Quá khứ tiếp diễn) thì có hành động ngắn khác xen vào (Quá khứ đơn): dùng <b>when / while</b>."],
      notes: ["Luôn luôn dựa vào trạng từ chỉ thời gian trong câu (như <i>recently, already, tomorrow, next week</i>...) để xác định thì chính xác của động từ."],
      tips: "Gạch chân trạng từ chỉ thời gian trong câu trước. Đó là chìa khóa để chọn thì đúng. Nếu không có trạng từ, nhìn ngữ cảnh câu."
    },
    words: [
      {word:'curriculum', ipa:'/kəˈrɪkjələm/', meaning:'chương trình giảng dạy', type:'noun', example:'The school updated its curriculum.', viAnswers:['chương trình giảng dạy', 'chương trình học']},
      {word:'mentor', ipa:'/ˈmentɔːr/', meaning:'người cố vấn, hướng dẫn', type:'noun / verb', example:'She acted as my mentor.', viAnswers:['cố vấn', 'người cố vấn']},
      {word:'orientation', ipa:'/ˌɔːriənˈteɪʃən/', meaning:'sự định hướng, buổi định hướng nhân viên mới', type:'noun', example:'Orientation is held on Monday.', viAnswers:['định hướng', 'buổi định hướng']},
      {word:'workshop', ipa:'/ˈwɜːrkʃɑːp/', meaning:'hội thảo thực hành', type:'noun', example:'The training workshop was useful.', viAnswers:['hội thảo', 'hội thảo thực hành']},
      {word:'development', ipa:'/dɪˈveləpmənt/', meaning:'sự phát triển', type:'noun', example:'Focus on career development.', viAnswers:['phát triển', 'sự phát triển']},
      {word:'evaluation', ipa:'/ɪˌvæljuˈeɪʃən/', meaning:'sự đánh giá', type:'noun', example:'Training evaluation is necessary.', viAnswers:['đánh giá', 'sự đánh giá']},
      {word:'feedback', ipa:'/ˈfiːdbæk/', meaning:'ý kiến phản hồi', type:'noun', example:'We need trainee feedback.', viAnswers:['phản hồi', 'ý kiến phản hồi']},
      {word:'facilitator', ipa:'/fəˈsɪlɪteɪtər/', meaning:'người hướng dẫn thảo luận', type:'noun', example:'The facilitator made learning easy.', viAnswers:['người hỗ trợ', 'điều phối viên']},
      {word:'session', ipa:'/ˈseʃən/', meaning:'buổi, phiên họp', type:'noun', example:'We have two training sessions.', viAnswers:['buổi', 'phiên']},
      {word:'seminar', ipa:'/ˈsemɪnɑːr/', meaning:'hội thảo', type:'noun', example:'Register for the seminar.', viAnswers:['hội thảo']},
      {word:'competence', ipa:'/ˈkɑːmpɪtəns/', meaning:'năng lực, khả năng chuyên môn', type:'noun', example:'Test the competence of staff.', viAnswers:['năng lực', 'khả năng']},
      {word:'certification', ipa:'/ˌsɜːrtɪfɪˈkeɪʃən/', meaning:'sự cấp chứng chỉ, chứng nhận', type:'noun', example:'He received a project manager certification.', viAnswers:['chứng chỉ', 'chứng nhận', 'sự cấp chứng chỉ']},
      {word:'coaching', ipa:'/ˈkoʊtʃɪŋ/', meaning:'huấn luyện, sự kèm cặp', type:'noun', example:'Executive coaching improves leadership.', viAnswers:['huấn luyện', 'sự huấn luyện']},
      {word:'instruction', ipa:'/ɪnˈstrʌkʃən/', meaning:'sự hướng dẫn', type:'noun', example:'Follow instructions carefully.', viAnswers:['hướng dẫn', 'sự hướng dẫn']},
      {word:'handout', ipa:'/ˈhændaʊt/', meaning:'tài liệu phát tay', type:'noun', example:'Read the training handout.', viAnswers:['tài liệu', 'tài liệu phát tay']},
      {word:'skillset', ipa:'/ˈskɪl.set/', meaning:'bộ kỹ năng', type:'noun', example:'This job requires a varied skillset.', viAnswers:['bộ kỹ năng', 'kỹ năng']},
      {word:'on-the-job training', ipa:'/ɒn ðə dʒɒb ˈtreɪnɪŋ/', meaning:'đào tạo tại chỗ, đào tạo thực tế', type:'noun', example:'We offer on-the-job training.', viAnswers:['đào tạo thực tế', 'đào tạo tại chỗ']},
      {word:'retrain', ipa:'/ˌriːˈtreɪn/', meaning:'đào tạo lại, tái huấn luyện', type:'verb', example:'We need to retrain our team.', viAnswers:['đào tạo lại']},
      {word:'performance', ipa:'/pərˈfɔːrməns/', meaning:'hiệu suất', type:'noun', example:'Training improves performance.', viAnswers:['hiệu suất', 'trình diễn']},
      {word:'supervise', ipa:'/ˈsuːpərvaɪz/', meaning:'giám sát', type:'verb', example:'Supervise the new recruits.', viAnswers:['giám sát']},
      {word:'syllabus', ipa:'/ˈsɪləbəs/', meaning:'đề cương khóa học', type:'noun', example:'Check the syllabus for details.', viAnswers:['đề cương', 'đề cương khóa học']},
      {word:'apprentice', ipa:'/əˈprentɪs/', meaning:'người học việc', type:'noun / verb', example:'He works as an apprentice chef.', viAnswers:['học việc', 'người học việc']}
    ]
  },

  {
    day: 47,
    topic: "Bảo hiểm",
    topicEn: "Insurance",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Giới từ (Prepositions)",
      explanation: "Giới từ là phần hay gặp trong TOEIC Part 5. Cần nhớ các giới từ đi với danh từ, động từ, tính từ: 1) Giới từ chỉ thời gian: in (tháng, năm), on (ngày), at (giờ), by (trước thời hạn), within (trong vòng). 2) Giới từ chỉ nơi chốn: in, on, at, between, among. 3) Cụm giới từ cố định: depend on, apply for, responsible for, comply with.",
      structure: "Verb/Adj/Noun + Preposition (học thuộc cụm cố định)",
      examples: ["The insurance policy is valid ___ two years. (for)", "You must file a claim ___ 30 days. (within)", "The coverage depends ___ the plan you choose. (on)", "She applied ___ health insurance. (for)"],
      exceptions: ["Một số tính từ đi với giới từ cố định bắt buộc phải học thuộc: <i>responsible for (chịu trách nhiệm), interested in (quan tâm), associated with (liên kết với), compatible with (tương thích với), equivalent to (tương đương với)</i>."],
      notes: ["Học thuộc các động từ đi kèm giới từ tạo cụm từ thông dụng: <i>comply with (tuân thủ), depend on (phụ thuộc), participate in (tham gia), agree on (đồng ý về việc gì)</i>."],
      tips: "Giới từ không có quy tắc rõ ràng - phải HỌC THUỘC từng cụm. Mỗi ngày học 3-5 cụm giới từ. Ví dụ: apply for, depend on, responsible for, comply with."
    },
    words: [
      {word:'premium', ipa:'/ˈpriːmiəm/', meaning:'phí bảo hiểm, phần thưởng, cao cấp', type:'noun / adjective', example:'Monthly premiums went up.', viAnswers:['phí bảo hiểm', 'cao cấp']},
      {word:'deductible', ipa:'/dɪˈdʌktəbəl/', meaning:'mức miễn bồi thường có khấu trừ, được trừ thuế', type:'noun / adjective', example:'He chose a policy with a high deductible.', viAnswers:['khấu trừ', 'mức khấu trừ']},
      {word:'coverage', ipa:'/ˈkʌvərɪdʒ/', meaning:'phạm vi bảo hiểm, độ phủ sóng', type:'noun', example:'Does the policy offer comprehensive coverage?', viAnswers:['phạm vi bảo hiểm', 'bao phủ']},
      {word:'policyholder', ipa:'/ˈpɑːləsihouldər/', meaning:'người đứng tên hợp đồng bảo hiểm', type:'noun', example:'The policyholder filed a claim.', viAnswers:['người mua bảo hiểm', 'chủ hợp đồng']},
      {word:'beneficiary', ipa:'/ˌbenəˈfɪʃieri/', meaning:'người thụ hưởng (bảo hiểm/di sản)', type:'noun', example:'His wife is the sole beneficiary.', viAnswers:['người thụ hưởng']},
      {word:'indemnity', ipa:'/ɪnˈdemnəti/', meaning:'sự bảo đảm bồi thường, đền bù', type:'noun', example:'He signed an indemnity contract.', viAnswers:['bồi thường', 'bảo đảm bồi thường']},
      {word:'claim', ipa:'/kleɪm/', meaning:'yêu cầu bồi thường, tuyên bố, đòi hỏi', type:'noun / verb', example:'Submit an insurance claim.', viAnswers:['yêu cầu bồi thường', 'tuyên bố']},
      {word:'liability', ipa:'/ˌlaɪəˈbɪləti/', meaning:'trách nhiệm pháp lý', type:'noun', example:'Buy liability insurance.', viAnswers:['trách nhiệm pháp lý']},
      {word:'underwrite', ipa:'/ˌʌndərˈraɪt/', meaning:'định phí bảo hiểm, bảo lãnh phát hành', type:'verb', example:'The risk is underwritten by Lloyd\'s.', viAnswers:['định phí bảo hiểm', 'bảo lãnh']},
      {word:'actuary', ipa:'/ˈæktʃueri/', meaning:'chuyên viên định phí bảo hiểm', type:'noun', example:'Actuaries calculate insurance risk.', viAnswers:['chuyên viên định phí', 'định phí viên']},
      {word:'lapse', ipa:'/læps/', meaning:'sự mất hiệu lực (do chậm đóng tiền), khoảng thời gian', type:'noun / verb', example:'My policy lapsed last month.', viAnswers:['mất hiệu lực', 'khoảng thời gian']},
      {word:'comprehensive', ipa:'/ˌkɑːmprɪˈhensɪv/', meaning:'toàn diện', type:'adjective', example:'This is comprehensive car insurance.', viAnswers:['toàn diện', 'bao quát']},
      {word:'expire', ipa:'/ɪkˈspaɪər/', meaning:'hết hạn', type:'verb', example:'The policy will expire tomorrow.', viAnswers:['hết hạn']},
      {word:'renew', ipa:'/rɪˈnuː/', meaning:'gia hạn', type:'verb', example:'We need to renew our policy.', viAnswers:['gia hạn', 'làm mới']},
      {word:'appraise', ipa:'/əˈpreɪz/', meaning:'định giá, thẩm định', type:'verb', example:'The jewelry was appraised at $5000.', viAnswers:['định giá', 'thẩm định']},
      {word:'depreciation', ipa:'/dɪˌpriːʃiˈeɪʃən/', meaning:'sự giảm giá, khấu hao', type:'noun', example:'We take depreciation into account.', viAnswers:['khấu hao', 'sự giảm giá']},
      {word:'reimbursement', ipa:'/ˌriːɪmˈbɜːrsmənt/', meaning:'sự hoàn lại chi phí', type:'noun', example:'Claim medical reimbursement.', viAnswers:['hoàn tiền', 'sự bồi hoàn']},
      {word:'assessment', ipa:'/əˈsesmənt/', meaning:'sự đánh giá, sự thẩm định mức thiệt hại', type:'noun', example:'The damage assessment took 3 days.', viAnswers:['đánh giá', 'sự đánh giá', 'thẩm định']},
      {word:'clause', ipa:'/klɔːz/', meaning:'điều khoản', type:'noun', example:'Read the exclusion clause.', viAnswers:['điều khoản']},
      {word:'exclude', ipa:'/ɪkˈskluːd/', meaning:'loại trừ, không bao gồm', type:'verb', example:'Pre-existing conditions are excluded.', viAnswers:['loại trừ', 'không bao gồm']},
      {word:'broker', ipa:'/ˈbroʊkər/', meaning:'người môi giới', type:'noun', example:'Consult an insurance broker.', viAnswers:['môi giới', 'người môi giới']},
      {word:'quote', ipa:'/kwoʊt/', meaning:'báo giá, trích dẫn', type:'noun / verb', example:'Get a free quote online.', viAnswers:['báo giá', 'trích dẫn']}
    ]
  },

  {
    day: 48,
    topic: "Bất động sản",
    topicEn: "Real Estate",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Liên từ (Conjunctions)",
      explanation: "Liên từ nối các mệnh đề trong câu. Có 3 loại chính: 1) Liên từ kết hợp (and, but, or, so, yet): nối 2 mệnh đề ngang hàng. 2) Liên từ phụ thuộc (because, although, if, when, while, unless, until, before, after, since): nối mệnh đề phụ với mệnh đề chính. 3) Liên từ tương quan (both...and, either...or, neither...nor, not only...but also).",
      structure: "Clause 1 + conjunction + Clause 2",
      examples: ["___ the property is expensive, it is in a great location. (Although)", "We will sign the lease ___ we agree on the price. (after / when)", "The tenant must pay rent ___ the landlord will cancel the lease. (or)", "___ the house is old, it needs renovation. (Because / Since)"],
      exceptions: ["Các cặp liên từ tương hỗ luôn đi cùng nhau: <i>either... or...</i>, <i>neither... nor...</i>, <i>both... and...</i>, <i>not only... but also...</i>, <i>whether... or...</i>"],
      notes: ["Khi làm bài thi Part 5, nếu thấy một trong các từ trong cặp tương hỗ nằm ở vế sau của chỗ trống, hãy chọn ngay từ còn lại đi kèm."],
      tips: "Đọc cả 2 mệnh đề để hiểu QUAN HỆ LOGIC giữa chúng: nguyên nhân → because/since, tương phản → although/even though, điều kiện → if/unless, thời gian → when/while/before/after."
    },
    words: [
      {word:'tenant', ipa:'/ˈtenənt/', meaning:'người thuê nhà/văn phòng', type:'noun', example:'The tenant paid rent.', viAnswers:['người thuê nhà', 'người thuê']},
      {word:'landlord', ipa:'/ˈlændlɔːrd/', meaning:'chủ nhà, chủ đất', type:'noun', example:'The landlord owns the building.', viAnswers:['chủ nhà']},
      {word:'lease', ipa:'/liːs/', meaning:'hợp đồng thuê, cho thuê', type:'noun / verb', example:'Sign a commercial lease.', viAnswers:['cho thuê', 'hợp đồng thuê']},
      {word:'mortgage', ipa:'/ˈmɔːrɡɪdʒ/', meaning:'khoản thế chấp mua nhà', type:'noun / verb', example:'Apply for a mortgage loan.', viAnswers:['thế chấp', 'khoản thế chấp']},
      {word:'foreclosure', ipa:'/fɔːrˈkloʊʒər/', meaning:'sự phát mãi tài sản thế chấp (do vỡ nợ)', type:'noun', example:'The bank started foreclosure proceedings.', viAnswers:['phát mãi', 'tịch thu tài sản']},
      {word:'equity', ipa:'/ˈekwəti/', meaning:'giá trị ròng của tài sản (sau khi trừ nợ)', type:'noun', example:'We built equity in our home.', viAnswers:['giá trị tài sản', 'cổ phần']},
      {word:'appraisal', ipa:'/əˈpreɪzəl/', meaning:'sự thẩm định giá tài sản', type:'noun', example:'A professional appraisal is required.', viAnswers:['thẩm định giá', 'sự đánh giá']},
      {word:'broker', ipa:'/ˈbroʊkər/', meaning:'người môi giới bất động sản', type:'noun', example:'The real estate broker showed us the office.', viAnswers:['môi giới', 'người môi giới']},
      {word:'commission', ipa:'/kəˈmɪʃən/', meaning:'tiền hoa hồng, ủy ban, nhiệm vụ', type:'noun', example:'The broker gets a 5% commission.', viAnswers:['hoa hồng', 'tiền hoa hồng', 'ủy ban']},
      {word:'premises', ipa:'/ˈpreməsɪz/', meaning:'cơ sở, mặt bằng văn phòng', type:'noun', example:'Keep the premises clean.', viAnswers:['cơ sở', 'mặt bằng', 'khuôn viên']},
      {word:'sublet', ipa:'/ˌsʌbˈlet/', meaning:'cho thuê lại', type:'verb', example:'The tenant decided to sublet the basement.', viAnswers:['cho thuê lại']},
      {word:'evict', ipa:'/ɪˈvɪkt/', meaning:'trục xuất, đuổi (người thuê) đi', type:'verb', example:'The landlord evicted the noisy tenant.', viAnswers:['trục xuất', 'đuổi đi']},
      {word:'vacate', ipa:'/ˈveɪkeɪt/', meaning:'trả lại phòng trống, di dời đi', type:'verb', example:'You must vacate the room by noon.', viAnswers:['trả phòng', 'di dời đi', 'bỏ trống']},
      {word:'amenities', ipa:'/əˈmenətiz/', meaning:'tiện ích sinh hoạt', type:'noun', example:'The complex has excellent amenities.', viAnswers:['tiện ích', 'các tiện nghi']},
      {word:'maintenance', ipa:'/ˈmeɪntənəns/', meaning:'sự bảo trì', type:'noun', example:'Maintenance costs are high.', viAnswers:['bảo trì', 'sự bảo trì']},
      {word:'realtor', ipa:'/ˈriːəltər/', meaning:'nhà môi giới bất động sản chuyên nghiệp', type:'noun', example:'The realtor helped us buy the house.', viAnswers:['nhà môi giới', 'môi giới bất động sản']},
      {word:'zoning', ipa:'/ˈzoʊnɪŋ/', meaning:'quy hoạch phân khu', type:'noun', example:'Check the zoning laws.', viAnswers:['quy hoạch', 'phân khu']},
      {word:'deposit', ipa:'/dɪˈpɑːzɪt/', meaning:'tiền đặt cọc', type:'noun', example:'Pay the deposit check.', viAnswers:['đặt cọc', 'tiền đặt cọc']},
      {word:'covenant', ipa:'/ˈhændlɪŋ fiː/', meaning:'điều khoản ràng buộc sử dụng tài sản', type:'noun', example:'Read the lease covenants.', viAnswers:['điều khoản ràng buộc', 'cam kết']},
      {word:'escrow', ipa:'/ˈeskroʊ/', meaning:'tài khoản ký thác phong tỏa (bên thứ ba giữ)', type:'noun', example:'The money was placed in escrow.', viAnswers:['ký thác', 'ký quỹ']},
      {word:'deed', ipa:'/diːd/', meaning:'chứng thư sở hữu (nhà đất), hành động', type:'noun', example:'He signed the property deed.', viAnswers:['chứng thư', 'giấy chứng nhận sở hữu']},
      {word:'easement', ipa:'/ˈiːzmənt/', meaning:'quyền sử dụng lối đi qua đất người khác', type:'noun', example:'The public has an easement to cross the path.', viAnswers:['quyền lối đi', 'quyền sử dụng đất']}
    ]
  },

  {
    day: 49,
    topic: "Thuế",
    topicEn: "Taxes",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Đại từ (Pronouns)",
      explanation: "Đại từ thường xuất hiện trong TOEIC Part 5. Các loại đại từ cần nhớ: 1) Đại từ nhân xưng: I, you, he, she, it, we, they. 2) Đại từ tân ngữ: me, you, him, her, it, us, them. 3) Tính từ sở hữu: my, your, his, her, its, our, their. 4) Đại từ sở hữu: mine, yours, his, hers, ours, theirs. 5) Đại từ phản thân: myself, yourself, himself, herself, itself, ourselves, themselves.",
      structure: "Chủ ngữ → đại từ nhân xưng | Tân ngữ → đại từ tân ngữ | Trước danh từ → tính từ sở hữu",
      examples: ["Each taxpayer must file ___ return on time. (his/her - tính từ sở hữu)", "The accountant prepared the report ___. (herself - đại từ phản thân)", "The company paid ___ taxes early. (its - tính từ sở hữu)", "___ who file late will pay a penalty. (Those - đại từ chỉ định)"],
      exceptions: ["Đại từ phản thân (myself, himself, themselves...) đứng ở cuối câu hoặc đứng ngay sau Chủ ngữ nhằm nhấn mạnh việc tự tay làm hành động.", "Cấu trúc <code>by + đại từ phản thân</code> tương đương với cụm từ <code>on one's own</code> (tự mình, một mình)."],
      notes: ["Phân biệt Tính từ sở hữu (<i>my, his, her, their</i> + Danh từ) và Đại từ sở hữu (<i>mine, his, hers, theirs</i> - đóng vai trò như cụm danh từ, không đi kèm danh từ)."],
      tips: "Nhìn vị trí chỗ trống: trước danh từ → tính từ sở hữu (my, your, his...). Sau động từ → tân ngữ (me, him, her...). Đứng một mình → đại từ sở hữu (mine, yours...)."
    },
    words: [
      {word:'exemption', ipa:'/ɪɡˈzempʃən/', meaning:'sự miễn thuế', type:'noun', example:'Tax exemption for non-profit organizations.', viAnswers:['miễn thuế', 'sự miễn trừ']},
      {word:'deductible', ipa:'/dɪˈdʌktəbəl/', meaning:'được khấu trừ thuế', type:'adjective', example:'Charitable donations are tax-deductible.', viAnswers:['khấu trừ thuế', 'được trừ thuế']},
      {word:'withholding tax', ipa:'/wɪθˈhoʊldɪŋ tæks/', meaning:'thuế khấu trừ tại nguồn', type:'noun', example:'Withholding tax is deducted from dividends.', viAnswers:['thuế khấu trừ tại nguồn']},
      {word:'evasion', ipa:'/ɪˈveɪʒən/', meaning:'sự trốn thuế', type:'noun', example:'Tax evasion leads to prosecution.', viAnswers:['trốn thuế', 'trốn tránh']},
      {word:'compliance', ipa:'/kəmˈplaɪəns/', meaning:'sự tuân thủ đúng luật thuế', type:'noun', example:'The firm operates in full compliance with tax codes.', viAnswers:['tuân thủ', 'sự tuân thủ']},
      {word:'liability', ipa:'/ˌlaɪəˈbɪləti/', meaning:'nghĩa vụ đóng thuế', type:'noun', example:'Reducing tax liability legally is called tax planning.', viAnswers:['nghĩa vụ thuế', 'nợ thuế']},
      {word:'audit', ipa:'/ˈɔːdɪt/', meaning:'sự thanh tra thuế, kiểm toán', type:'noun / verb', example:'The tax office ordered an audit.', viAnswers:['thanh tra thuế', 'kiểm toán']},
      {word:'revenue', ipa:'/ˈrevənuː/', meaning:'doanh thu, ngân sách thu thuế', type:'noun', example:'Government tax revenue fell during recession.', viAnswers:['nguồn thu', 'doanh thu']},
      {word:'file', ipa:'/faɪl/', meaning:'nộp (tờ khai thuế)', type:'verb', example:'File your tax returns early.', viAnswers:['nộp', 'nộp tờ khai']},
      {word:'allowance', ipa:'/əˈlaʊəns/', meaning:'hạn mức miễn thuế, tiền trợ cấp', type:'noun', example:'You have a personal tax allowance.', viAnswers:['hạn mức miễn thuế', 'trợ cấp']},
      {word:'bracket', ipa:'/ˈbrækɪt/', meaning:'khung thuế, bậc thuế', type:'noun', example:'Which tax bracket do you belong to?', viAnswers:['khung thuế', 'bậc thuế']},
      {word:'levy', ipa:'/ˈlevi/', meaning:'thu thuế, đánh thuế, sắc thuế', type:'verb / noun', example:'A new levy was imposed on luxury cars.', viAnswers:['đánh thuế', 'thu thuế', 'sắc thuế']},
      {word:'corporate', ipa:'/ˈkɔːrpərət/', meaning:'thuộc doanh nghiệp, tập đoàn', type:'adjective', example:'Read the corporate tax code.', viAnswers:['doanh nghiệp', 'tập đoàn']},
      {word:'returns', ipa:'/rɪˈtɜːrnz/', meaning:'tờ khai thuế thu nhập', type:'noun', example:'Ensure the tax returns are accurate.', viAnswers:['tờ khai thuế']},
      {word:'auditor', ipa:'/ˈɔːdɪtər/', meaning:'kiểm toán viên thuế', type:'noun', example:'The auditor requested ledger books.', viAnswers:['kiểm toán viên']},
      {word:'penalty', ipa:'/ˈpenəlti/', meaning:'tiền phạt chậm nộp', type:'noun', example:'Late filing results in a penalty.', viAnswers:['tiền phạt']},
      {word:'incentive', ipa:'/ɪnˈsentɪv/', meaning:'chính sách ưu đãi khuyến khích (thuế)', type:'noun', example:'Tax incentives attract foreign investment.', viAnswers:['ưu đãi', 'khuyến khích']},
      {word:'tariff', ipa:'/ˈtærɪf/', meaning:'thuế quan xuất nhập khẩu', type:'noun', example:'The government raised tariffs on steel.', viAnswers:['thuế quan', 'thuế nhập khẩu']},
      {word:'rebate', ipa:'/ˈriːbeɪt/', meaning:'sự giảm trừ thuế, hoàn lại một phần tiền', type:'noun / verb', example:'He applied for a tax rebate.', viAnswers:['giảm trừ', 'hoàn lại tiền']},
      {word:'assessment', ipa:'/əˈsesmənt/', meaning:'sự thẩm định mức thuế', type:'noun', example:'We received our tax assessment letter.', viAnswers:['thẩm định', 'đánh giá']},
      {word:'treaty', ipa:'/ˈtriːti/', meaning:'hiệp ước (tránh đánh thuế hai lần)', type:'noun', example:'The two countries signed a tax treaty.', viAnswers:['hiệp ước']},
      {word:'deduction', ipa:'/dɪˈdʌkʃən/', meaning:'khoản giảm trừ gia cảnh/chi phí', type:'noun', example:'List your tax deductions.', viAnswers:['giảm trừ', 'khấu trừ']}
    ]
  },

  {
    day: 50,
    topic: "Nghiên cứu",
    topicEn: "Research",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Câu bị động (Passive Voice)",
      explanation: "Câu bị động được dùng khi muốn nhấn mạnh đối tượng chịu tác động hoặc khi không biết ai thực hiện hành động. Cấu trúc: Subject + be + V3/ed (+ by agent). Các thì bị động thường gặp: 1) Hiện tại đơn: is/are + V3. 2) Quá khứ đơn: was/were + V3. 3) Hiện tại hoàn thành: has/have been + V3. 4) Tương lai: will be + V3.",
      structure: "Subject + be + past participle (V3) + (by + agent)",
      examples: ["The research ___ conducted by a team of scientists. (was - quá khứ bị động)", "The data ___ being analyzed now. (is - hiện tại tiếp diễn bị động)", "The results ___ published next month. (will be - tương lai bị động)", "The report has ___ reviewed by experts. (been - hiện tại hoàn thành bị động)"],
      exceptions: ["Một số cụm từ mang hình thức bị động nhưng lại dùng để diễn tả trạng thái chủ động: <i>be located in/at</i> (nằm ở vị trí), <i>be dedicated/devoted to</i> (tận tụy, cống hiến cho), <i>be interested in</i> (hứng thú với)."],
      notes: ["Nếu chỗ trống đứng trước cụm giới từ (<i>by, to, in, at, with</i>...) hoặc trạng từ, hãy ưu tiên chọn câu bị động."],
      tips: "Nếu chủ ngữ là người/vật CHỊU tác động → dùng bị động. Dấu hiệu: có 'by + ai đó' phía sau, hoặc không đề cập ai thực hiện hành động."
    },
    words: [
      {word:'hypothesis', ipa:'/haɪˈpɑːθəsɪs/', meaning:'giả thuyết', type:'noun', example:'The experiment proved the hypothesis.', viAnswers:['giả thuyết']},
      {word:'empirical', ipa:'/ɪmˈpɪrɪkəl/', meaning:'dựa trên thực nghiệm, thực tế', type:'adjective', example:'We need empirical evidence.', viAnswers:['thực nghiệm', 'thực tế']},
      {word:'methodology', ipa:'/ˌmeθəˈdɑːlədʒi/', meaning:'phương pháp luận, hệ phương pháp', type:'noun', example:'Explain your research methodology.', viAnswers:['phương pháp luận', 'hệ phương pháp']},
      {word:'correlation', ipa:'/ˌkɔːrəˈleɪʃən/', meaning:'sự tương quan', type:'noun', example:'There is a strong correlation between advertising and sales.', viAnswers:['tương quan', 'sự tương quan']},
      {word:'statistics', ipa:'/stəˈtɪstɪks/', meaning:'số liệu thống kê', type:'noun', example:'The statistics show a upward trend.', viAnswers:['thống kê', 'số liệu thống kê']},
      {word:'significant', ipa:'/sɪɡˈnɪfɪkənt/', meaning:'đáng kể, có ý nghĩa thống kê', type:'adjective', example:'The difference in results is significant.', viAnswers:['đáng kể', 'quan trọng']},
      {word:'variable', ipa:'/ˈveriəbəl/', meaning:'biến số', type:'noun / adjective', example:'Identify the independent variables.', viAnswers:['biến số', 'biến']},
      {word:'survey', ipa:'/ˈsɜːrveɪ/', meaning:'khảo sát', type:'noun / verb', example:'Conduct a customer survey.', viAnswers:['khảo sát']},
      {word:'sample size', ipa:'/ˈsæmpəl saɪz/', meaning:'quy mô mẫu khảo sát', type:'noun', example:'We need to increase the sample size.', viAnswers:['quy mô mẫu', 'mẫu khảo sát']},
      {word:'findings', ipa:'/ˈfaɪndɪŋz/', meaning:'kết quả phát hiện được', type:'noun', example:'The findings were published in a journal.', viAnswers:['phát hiện', 'kết quả']},
      {word:'conclusion', ipa:'/kənˈkluːʒən/', meaning:'kết luận', type:'noun', example:'What is the conclusion of the study?', viAnswers:['kết luận']},
      {word:'analyze', ipa:'/ˈænəlaɪz/', meaning:'phân tích', type:'verb', example:'We analyzed the survey data.', viAnswers:['phân tích']},
      {word:'peer-reviewed', ipa:'/ˌpɪr rɪˈvjuːd/', meaning:'được bình duyệt bởi các chuyên gia đồng nghiệp', type:'adjective', example:'Publish in a peer-reviewed journal.', viAnswers:['bình duyệt', 'được bình duyệt']},
      {word:'literature', ipa:'/ˈlɪtərətsər/', meaning:'tài liệu tham khảo, văn học', type:'noun', example:'We reviewed the scientific literature.', viAnswers:['tài liệu tham khảo', 'văn học']},
      {word:'qualitative', ipa:'/ˈkwɑːlɪteɪtɪv/', meaning:'thuộc định tính', type:'adjective', example:'We did a qualitative research.', viAnswers:['định tính', 'thuộc định tính']},
      {word:'quantitative', ipa:'/ˈkwɑːntɪteɪtɪv/', meaning:'thuộc định lượng', type:'adjective', example:'The survey provided quantitative data.', viAnswers:['định lượng', 'thuộc định lượng']},
      {word:'bias', ipa:'/ˈbaɪəs/', meaning:'sự thiên vị, sai lệch trong nghiên cứu', type:'noun', example:'Avoid researcher bias in interviews.', viAnswers:['thiên vị', 'sai lệch']},
      {word:'funding', ipa:'/ˈfʌndɪŋ/', meaning:'kinh phí tài trợ nghiên cứu', type:'noun', example:'The project secured government funding.', viAnswers:['tài trợ', 'kinh phí', 'nguồn vốn']},
      {word:'laboratory', ipa:'/ˈlæbrətɔːri/', meaning:'phòng thí nghiệm', type:'noun', example:'The tests were done in a laboratory.', viAnswers:['phòng thí nghiệm']},
      {word:'experiment', ipa:'/ɪkˈsperɪmənt/', meaning:'thí nghiệm, thử nghiệm', type:'noun / verb', example:'They conducted a scientific experiment.', viAnswers:['thí nghiệm', 'thử nghiệm']},
      {word:'academic', ipa:'/ˌækəˈdemɪk/', meaning:'thuộc học thuật', type:'adjective', example:'He has a strong academic record.', viAnswers:['học thuật', 'thuộc học thuật']},
      {word:'patent', ipa:'/ˈpætənt/', meaning:'bằng sáng chế', type:'noun', example:'They applied for a patent for the compound.', viAnswers:['bằng sáng chế']}
    ]
  },

  {
    day: 51,
    topic: "Đàm phán",
    topicEn: "Negotiations",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - So sánh (Comparisons)",
      explanation: "Có 3 cấp so sánh: 1) So sánh hơn: tính từ ngắn + -er + than / more + tính từ dài + than. 2) So sánh nhất: the + tính từ ngắn + -est / the most + tính từ dài. 3) So sánh bằng: as + adj/adv + as. Ngoại lệ: good → better → best, bad → worse → worst, much/many → more → most, little → less → least.",
      structure: "So sánh hơn: adj-er than / more adj than | So sánh nhất: the adj-est / the most adj | So sánh bằng: as adj as",
      examples: ["This offer is ___ than the last one. (better - so sánh hơn bất quy tắc)", "We need a ___ flexible approach. (more - so sánh hơn, tính từ dài)", "This is the ___ important deal of the year. (most - so sánh nhất)", "Our terms are as ___ as theirs. (fair - so sánh bằng)"],
      exceptions: ["Cấu trúc so sánh kép (Double Comparative): <code>The + so sánh hơn + S + V, the + so sánh hơn + S + V</code> (Càng... thì càng...). Ví dụ: <i>The more you practice, the better you will perform</i>."],
      notes: ["Trong cấu trúc so sánh bằng <code>as + Adj/Adv + as</code>, điền tính từ nếu động từ chính là <i>to be/linking verb</i>, điền trạng từ nếu động từ chính là động từ thường."],
      tips: "Tính từ ngắn (1 âm tiết): thêm -er/-est. Tính từ dài (2+ âm tiết): dùng more/most. Luôn nhớ ngoại lệ: good-better-best, bad-worse-worst."
    },
    words: [
      {word:'negotiate', ipa:'/nɪˈɡoʊʃieɪt/', meaning:'đàm phán, thương lượng', type:'verb', example:'We need to negotiate the terms of the deal.', viAnswers:['đàm phán', 'thương lượng']},
      {word:'concession', ipa:'/kənˈseʃən/', meaning:'sự nhượng bộ', type:'noun', example:'Both sides made concessions.', viAnswers:['nhượng bộ', 'sự nhượng bộ']},
      {word:'compromise', ipa:'/ˈkɑːmprəmaɪz/', meaning:'sự thỏa hiệp, thỏa hiệp', type:'noun / verb', example:'We reached a compromise.', viAnswers:['thỏa hiệp', 'sự thỏa hiệp']},
      {word:'leverage', ipa:'/ˈlevərɪdʒ/', meaning:'đòn bẩy, lợi thế đàm phán', type:'noun / verb', example:'Our strong brand gives us leverage.', viAnswers:['lợi thế', 'đòn bẩy']},
      {word:'counteroffer', ipa:'/ˈkaʊntərˌɔːfər/', meaning:'lời phản đề nghị (đưa ra đề nghị ngược lại)', type:'noun', example:'They rejected our price and made a counteroffer.', viAnswers:['phản đề nghị', 'lời phản đề nghị']},
      {word:'deadlock', ipa:'/ˈdedlɑːk/', meaning:'sự bế tắc hoàn toàn', type:'noun', example:'The negotiations reached a deadlock.', viAnswers:['bế tắc', 'sự bế tắc']},
      {word:'dispute', ipa:'/dɪˈspjuːt/', meaning:'tranh chấp, cuộc tranh cãi', type:'noun / verb', example:'They resolved the contract dispute.', viAnswers:['tranh chấp', 'tranh cãi']},
      {word:'mediate', ipa:'/ˈmiːdieɪt/', meaning:'hòa giải, làm trung gian', type:'verb', example:'A third party was hired to mediate.', viAnswers:['hòa giải', 'trung gian']},
      {word:'resolve', ipa:'/rɪˈzɑːlv/', meaning:'giải quyết ổn thỏa', type:'verb', example:'We hope to resolve the issue amicably.', viAnswers:['giải quyết']},
      {word:'agreement', ipa:'/əˈɡriːmənt/', meaning:'thỏa thuận', type:'noun', example:'They signed a trade agreement.', viAnswers:['thỏa thuận', 'hợp đồng']},
      {word:'mutual', ipa:'/ˈmjuːtʃuəl/', meaning:'lẫn nhau, hai bên cùng...', type:'adjective', example:'The deal was to our mutual benefit.', viAnswers:['lẫn nhau', 'chung', 'hai bên']},
      {word:'terms', ipa:'/tɜːrmz/', meaning:'các điều khoản điều kiện', type:'noun', example:'Accept the terms of the deal.', viAnswers:['điều khoản']},
      {word:'priority', ipa:'/praɪˈɔːrəti/', meaning:'sự ưu tiên', type:'noun', example:'Lowering costs is our main priority.', viAnswers:['ưu tiên', 'sự ưu tiên']},
      {word:'flexible', ipa:'/ˈfleksəbəl/', meaning:'linh hoạt', type:'adjective', example:'We are flexible on the delivery date.', viAnswers:['linh hoạt']},
      {word:'firm', ipa:'/fɜːrm/', meaning:'kiên quyết, vững chắc, công ty', type:'adjective / noun', example:'We are firm on our price limit.', viAnswers:['kiên quyết', 'công ty', 'vững chắc']},
      {word:'arbitrator', ipa:'/ˈɑːrbɪtreɪtər/', meaning:'trọng tài phân xử', type:'noun', example:'The arbitrator gave a final ruling.', viAnswers:['trọng tài']},
      {word:'deadlines', ipa:'/ˈdedlaɪnz/', meaning:'hạn chót', type:'noun', example:'Meet the negotiation deadlines.', viAnswers:['hạn chót']},
      {word:'outcome', ipa:'/ˈaʊtkʌm/', meaning:'kết quả đạt được', type:'noun', example:'What was the outcome of the talk?', viAnswers:['kết quả']},
      {word:'propose', ipa:'/prəˈpoʊz/', meaning:'đề xuất', type:'verb', example:'Propose a new solution.', viAnswers:['đề xuất', 'đề nghị']},
      {word:'reject', ipa:'/rɪˈdʒekt/', meaning:'từ chối, bác bỏ', type:'verb', example:'They rejected the proposal.', viAnswers:['từ chối', 'bác bỏ']},
      {word:'accept', ipa:'/ækˈsept/', meaning:'chấp nhận', type:'verb', example:'We accepted the terms.', viAnswers:['chấp nhận', 'đồng ý']},
      {word:'walk away', ipa:'/wɔːk əˈweɪ/', meaning:'rời đi, bỏ đi (không ký kết)', type:'verb phrase', example:'We will walk away if they don\'t lower the price.', viAnswers:['bỏ đi', 'rời đi']}
    ]
  },

  {
    day: 52,
    topic: "Nghệ thuật / Văn hóa",
    topicEn: "Arts / Culture",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 1)",
      explanation: "Ôn tập tổng hợp các điểm ngữ pháp đã học: từ loại, thì động từ, giới từ, liên từ, đại từ, bị động, so sánh. Khi làm bài TOEIC Part 5, làm theo quy trình: 1) Đọc toàn bộ câu, 2) Xác định loại câu hỏi (từ loại? thì? giới từ?...), 3) Áp dụng kiến thức ngữ pháp phù hợp, 4) Chọn đáp án, 5) Đọc lại câu hoàn chỉnh để kiểm tra.",
      structure: "Đọc câu → Xác định loại câu hỏi → Áp dụng quy tắc → Chọn đáp án → Kiểm tra",
      examples: ["The ___ performance was amazing. (artistic - từ loại: tính từ trước danh từ)", "The exhibition ___ visited by thousands of people. (was - bị động quá khứ)", "This painting is ___ beautiful than that one. (more - so sánh hơn)", "The artist created the sculpture ___ herself. (by - giới từ)"],
      exceptions: [],
      notes: [],
      tips: "Làm bài Part 5 không quá 30 giây mỗi câu. Nếu không chắc chắn, dùng phương pháp loại trừ. Đánh dấu câu khó và quay lại sau."
    },
    words: [
      {word:'gallery', ipa:'/ˈɡæləri/', meaning:'triển lãm nghệ thuật, phòng trưng bày', type:'noun', example:'The art gallery features local paintings.', viAnswers:['triển lãm', 'phòng tranh', 'phòng trưng bày']},
      {word:'exhibit', ipa:'/ɪɡˈzɪbɪt/', meaning:'hiện vật trưng bày, cuộc triển lãm, trưng bày', type:'noun / verb', example:'The museum has a new Egyptian exhibit.', viAnswers:['trưng bày', 'triển lãm', 'hiện vật']},
      {word:'sculpture', ipa:'/ˈskʌlptʃər/', meaning:'tác phẩm điêu khắc, tượng', type:'noun', example:'A marble sculpture stands in the lobby.', viAnswers:['điêu khắc', 'tác phẩm điêu khắc', 'tượng']},
      {word:'orchestra', ipa:'/ˈɔːrkɪstrə/', meaning:'dàn nhạc giao hưởng', type:'noun', example:'The orchestra played Beethoven\'s Ninth.', viAnswers:['dàn nhạc', 'dàn nhạc giao hưởng']},
      {word:'heritage', ipa:'/ˈherɪtɪdʒ/', meaning:'di sản', type:'noun', example:'Protect our cultural heritage.', viAnswers:['di sản']},
      {word:'aesthetic', ipa:'/esˈθetɪk/', meaning:'thuộc mỹ học, có tính thẩm mỹ', type:'adjective / noun', example:'The building has a modern aesthetic.', viAnswers:['thẩm mỹ', 'thẩm mỹ học']},
      {word:'patron', ipa:'/ˈpeɪtrən/', meaning:'khách hàng quen, nhà bảo trợ nghệ thuật', type:'noun', example:'He is a wealthy patron of the arts.', viAnswers:['khách quen', 'nhà bảo trợ']},
      {word:'performance', ipa:'/pərˈfɔːrməns/', meaning:'buổi trình diễn, biểu diễn', type:'noun', example:'The performance starts at 8 PM.', viAnswers:['biểu diễn', 'trình diễn', 'buổi biểu diễn']},
      {word:'creative', ipa:'/kriˈeɪtɪv/', meaning:'sáng tạo', type:'adjective', example:'Advertising requires creative ideas.', viAnswers:['sáng tạo']},
      {word:'critic', ipa:'/ˈkrɪtɪk/', meaning:'nhà phê bình', type:'noun', example:'The film critic gave it a good review.', viAnswers:['nhà phê bình']},
      {word:'masterpiece', ipa:'/ˈmæstərpiːs/', meaning:'kiệt tác, tác phẩm để đời', type:'noun', example:'The painting is a masterpiece.', viAnswers:['kiệt tác']},
      {word:'composer', ipa:'/kəmˈpoʊzər/', meaning:'nhà soạn nhạc', type:'noun', example:'Mozart is a famous composer.', viAnswers:['nhà soạn nhạc']},
      {word:'literary', ipa:'/ˈlɪtəreri/', meaning:'thuộc văn học', type:'adjective', example:'The Nobel Prize for literary achievements.', viAnswers:['văn học', 'thuộc văn học']},
      {word:'genre', ipa:'/ˈʒɑːnrə/', meaning:'thể loại (sách, nhạc, phim)', type:'noun', example:'Science fiction is a popular film genre.', viAnswers:['thể loại']},
      {word:'curator', ipa:'/ˈkjʊreɪtər/', meaning:'người phụ trách, giám tuyển bảo tàng', type:'noun', example:'The curator organized the new gallery display.', viAnswers:['người phụ trách', 'giám tuyển']},
      {word:'repertoire', ipa:'/ˈrepərtwɑːr/', meaning:'vốn tiết mục biểu diễn (của nghệ sĩ/ban nhạc)', type:'noun', example:'The band has a wide repertoire.', viAnswers:['vốn tiết mục', 'tiết mục']},
      {word:'portray', ipa:'/pɔːrˈtreɪ/', meaning:'khắc họa, vẽ chân dung, đóng vai', type:'verb', example:'The actor portrayed the president.', viAnswers:['khắc họa', 'đóng vai', 'vẽ']},
      {word:'review', ipa:'/rɪˈvjuː/', meaning:'sự phê bình, đánh giá', type:'noun / verb', example:'The play received rave reviews.', viAnswers:['đánh giá', 'phê bình']},
      {word:'acclaim', ipa:'/əˈkleɪm/', meaning:'ca ngợi, hoan nghênh', type:'verb / noun', example:'The movie was highly acclaimed.', viAnswers:['ca ngợi', 'hoan nghênh']},
      {word:'inspiration', ipa:'/ˌɪnspəˈreɪʃən/', meaning:'nguồn cảm hứng', type:'noun', example:'Nature is her main source of inspiration.', viAnswers:['cảm hứng', 'nguồn cảm hứng']},
      {word:'auditorium', ipa:'/ˌɔːdɪˈtɔːriəm/', meaning:'khán phòng, giảng đường lớn', type:'noun', example:'The auditorium was full.', viAnswers:['khán phòng']},
      {word:'expressive', ipa:'/ɪkˈspresɪv/', meaning:'có tính biểu cảm, diễn cảm', type:'adjective', example:'Dance is a highly expressive art.', viAnswers:['biểu cảm', 'diễn cảm']}
    ]
  },

  {
    day: 53,
    topic: "Chính phủ",
    topicEn: "Government",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 2)",
      explanation: "Tiếp tục ôn tập tổng hợp. Tập trung vào các dạng câu hỏi thường gặp trong TOEIC: 1) Chọn từ vựng phù hợp ngữ cảnh, 2) Điền từ nối mệnh đề (however, therefore, moreover, furthermore, nevertheless, in addition), 3) Phân biệt các từ gần nghĩa nhưng khác cách dùng (như rise/raise, lay/lie, affect/effect).",
      structure: "Đọc ngữ cảnh → Xác định nghĩa phù hợp → Chọn từ chính xác",
      examples: ["The government ___ a new law. (passed - chọn từ phù hợp ngữ cảnh)", "Taxes increased; ___, spending was cut. (therefore - từ nối chỉ kết quả)", "The policy will ___ all citizens. (affect - phân biệt affect/effect)", "The president ___ reforms. (implemented - từ vựng ngữ cảnh)"],
      exceptions: [],
      notes: [],
      tips: "Với câu hỏi từ vựng, đọc toàn bộ câu để hiểu ngữ cảnh. Đừng chỉ nhìn chỗ trống. Nhiều khi đáp án đúng không phải từ bạn nghĩ đầu tiên."
    },
    words: [
      {word:'parliament', ipa:'/ˈpɑːrləmənt/', meaning:'nghị viện, quốc hội', type:'noun', example:'Parliament voted on the tax bill.', viAnswers:['quốc hội', 'nghị viện']},
      {word:'legislation', ipa:'/ˌledʒɪsˈleɪʃən/', meaning:'luật pháp, dự luật, sự lập pháp', type:'noun', example:'New legislation was introduced.', viAnswers:['luật pháp', 'sự lập pháp', 'dự luật']},
      {word:'bureaucracy', ipa:'/bjʊˈrɑːkrəsi/', meaning:'thói quan liêu, hệ thống công chức', type:'noun', example:'Red tape and bureaucracy delay projects.', viAnswers:['quan liêu', 'hệ thống công chức']},
      {word:'constituency', ipa:'/kənˈstɪtʃuənsi/', meaning:'khu vực bầu cử, cử tri', type:'noun', example:'He represented his constituency well.', viAnswers:['khu vực bầu cử', 'cử tri']},
      {word:'municipal', ipa:'/mjuːˈnɪsɪpəl/', meaning:'thuộc thành phố, thuộc đô thị', type:'adjective', example:'Municipal government manages public transit.', viAnswers:['thành phố', 'thuộc thành phố', 'đô thị']},
      {word:'referendum', ipa:'/ˌrefəˈrendəm/', meaning:'trưng cầu dân ý', type:'noun', example:'The decision was made by referendum.', viAnswers:['trưng cầu dân ý']},
      {word:'policy', ipa:'/ˈpɑːləsi/', meaning:'chính sách', type:'noun', example:'What is the policy on environmental subsidies?', viAnswers:['chính sách']},
      {word:'regulation', ipa:'/ˌreɡjəˈleɪʃən/', meaning:'quy định, luật lệ', type:'noun', example:'Safety regulations are strict.', viAnswers:['quy định', 'luật lệ']},
      {word:'subsidy', ipa:'/ˈsʌbsədi/', meaning:'tiền trợ cấp của chính phủ', type:'noun', example:'The government cut agricultural subsidies.', viAnswers:['trợ cấp', 'tiền trợ cấp']},
      {word:'welfare', ipa:'/ˈwelfer/', meaning:'phúc lợi xã hội, sự an sinh', type:'noun', example:'Social welfare programs help poor families.', viAnswers:['phúc lợi', 'an sinh']},
      {word:'reform', ipa:'/rɪˈfɔːrm/', meaning:'cải cách', type:'noun / verb', example:'We need tax reform.', viAnswers:['cải cách']},
      {word:'infrastructure', ipa:'/ˈɪnfrəˌstrʌktʃər/', meaning:'cơ sở hạ tầng', type:'noun', example:'Public funding for infrastructure.', viAnswers:['cơ sở hạ tầng']},
      {word:'deficit', ipa:'/ˈdefəsɪt/', meaning:'thâm hụt tài chính', type:'noun', example:'The government faces a huge budget deficit.', viAnswers:['thâm hụt']},
      {word:'sanction', ipa:'/ˈsæŋkʃən/', meaning:'sự trừng phạt, sự phê chuẩn', type:'noun / verb', example:'Economic sanctions were imposed.', viAnswers:['trừng phạt', 'phê chuẩn']},
      {word:'treaty', ipa:'/ˈtriːti/', meaning:'hiệp ước, điều ước quốc tế', type:'noun', example:'They signed a peace treaty.', viAnswers:['hiệp ước']},
      {word:'diplomacy', ipa:'/dɪˈploʊməsi/', meaning:'ngành ngoại giao, sự khôn khéo', type:'noun', example:'International problems require diplomacy.', viAnswers:['ngoại giao', 'sự khéo léo']},
      {word:'official', ipa:'/əˈfɪʃəl/', meaning:'quan chức, chính thức', type:'noun / adjective', example:'A government official made the statement.', viAnswers:['quan chức', 'chính thức']},
      {word:'agency', ipa:'/ˈeɪdʒənsi/', meaning:'cơ quan chính phủ, đại lý', type:'noun', example:'Environmental Protection Agency.', viAnswers:['cơ quan', 'đại lý']},
      {word:'federal', ipa:'/ˈfedərəl/', meaning:'thuộc liên bang', type:'adjective', example:'Federal court has jurisdiction.', viAnswers:['liên bang', 'thuộc liên bang']},
      {word:'candidate', ipa:'/ˈkændɪdət/', meaning:'ứng viên tranh cử', type:'noun', example:'The candidate gave a campaign speech.', viAnswers:['ứng viên', 'ứng cử viên']},
      {word:'campaign', ipa:'/kæmˈpeɪn/', meaning:'chiến dịch vận động tranh cử/quảng cáo', type:'noun / verb', example:'Launch a political campaign.', viAnswers:['chiến dịch']},
      {word:'senate', ipa:'/ˈsenət/', meaning:'thượng nghị viện', type:'noun', example:'The senate rejected the bill.', viAnswers:['thượng nghị viện', 'thượng viện']}
    ]
  },

  {
    day: 54,
    topic: "Chuỗi cung ứng",
    topicEn: "Supply Chain",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 3)",
      explanation: "Luyện tập tổng hợp tập trung vào Part 6 & 7 của TOEIC: đọc hiểu đoạn văn. Kỹ năng cần: 1) Đọc lướt (skimming) để nắm ý chính, 2) Đọc quét (scanning) để tìm thông tin cụ thể, 3) Suy luận ý ẩn (inference), 4) Hiểu mục đích của đoạn văn (email, thông báo, quảng cáo...).",
      structure: "Đọc câu hỏi trước → Đọc lướt bài → Tìm thông tin → Chọn đáp án",
      examples: ["Email: 'The shipment will arrive by Friday.' → Khi nào hàng đến? (By Friday)", "Notice: 'All vendors must submit invoices by the 15th.' → Ai phải nộp? (Vendors)", "Memo: 'Due to high demand, production has increased.' → Tại sao? (High demand)", "Ad: 'Free shipping on orders over $50.' → Điều kiện? (Orders over $50)"],
      exceptions: [],
      notes: [],
      tips: "Đọc câu hỏi TRƯỚC khi đọc bài. Gạch chân từ khóa trong câu hỏi. Khi đọc bài, tìm từ khóa đó. Không cần hiểu 100% bài - chỉ cần tìm đúng thông tin."
    },
    words: [
      {word:'freight', ipa:'/freɪt/', meaning:'hàng hóa, cước vận chuyển hàng hóa', type:'noun', example:'Freight charges are based on weight.', viAnswers:['hàng hóa', 'vận tải', 'cước']},
      {word:'logistics', ipa:'/lɒˈdʒɪstɪks/', meaning:'ngành hậu cần, điều phối logistics', type:'noun', example:'Logistics managers handle transport.', viAnswers:['hậu cần', 'logistics']},
      {word:'warehouse', ipa:'/ˈwerhaʊs/', meaning:'nhà kho', type:'noun', example:'The inventory is stored in the warehouse.', viAnswers:['nhà kho']},
      {word:'inventory', ipa:'/ˈɪnvəntɔːri/', meaning:'hàng tồn kho', type:'noun', example:'Do an inventory check.', viAnswers:['hàng tồn kho']},
      {word:'procurement', ipa:'/prəˈkjʊərmənt/', meaning:'việc thu mua nguyên vật liệu', type:'noun', example:'The procurement officer signed the deal.', viAnswers:['thu mua', 'sự thu mua']},
      {word:'distributor', ipa:'/dɪˈstrɪbjətər/', meaning:'nhà phân phối', type:'noun', example:'We are the exclusive distributor for this brand.', viAnswers:['nhà phân phối']},
      {word:'vendor', ipa:'/ˈvendər/', meaning:'nhà cung cấp', type:'noun', example:'Pay the vendor invoice.', viAnswers:['nhà cung cấp']},
      {word:'wholesale', ipa:'/ˈhoʊlseɪl/', meaning:'bán sỉ', type:'noun', example:'Buy at wholesale price.', viAnswers:['bán sỉ', 'bán buôn']},
      {word:'shipment', ipa:'/ˈʃɪpmənt/', meaning:'lô hàng vận chuyển', type:'noun', example:'The shipment arrived safely.', viAnswers:['lô hàng', 'vận chuyển']},
      {word:'cargo', ipa:'/ˈcɑːrɡoʊ/', meaning:'hàng hóa', type:'noun', example:'The plane carries cargo.', viAnswers:['hàng hóa']},
      {word:'customs', ipa:'/ˈkʌstəmz/', meaning:'hải quan', type:'noun', example:'Pay customs duty.', viAnswers:['hải quan']},
      {word:'lead time', ipa:'/liːd taɪm/', meaning:'thời gian chuẩn bị từ lúc đặt đến lúc nhận hàng', type:'noun', example:'The manufacturing lead time is two weeks.', viAnswers:['thời gian chuẩn bị', 'thời gian giao hàng']},
      {word:'consignment', ipa:'/kənˈsaɪnmənt/', meaning:'lô hàng ký gửi, sự ký gửi', type:'noun', example:'The goods were sent on consignment.', viAnswers:['ký gửi', 'lô hàng ký gửi']},
      {word:'bill of lading', ipa:'/bɪl əv ˈleɪdɪŋ/', meaning:'vận đơn đường biển/đường bộ', type:'noun', example:'Check the bill of lading details.', viAnswers:['vận đơn']},
      {word:'carrier', ipa:'/ˈkæriər/', meaning:'hãng vận chuyển', type:'noun', example:'Choose a reliable carrier.', viAnswers:['hãng vận chuyển', 'người vận chuyển']},
      {word:'tracking number', ipa:'/ˈtrækɪŋ ˈnʌmbər/', meaning:'mã vận đơn', type:'noun', example:'Use the tracking number to check status.', viAnswers:['mã vận đơn', 'mã theo dõi']},
      {word:'outsource', ipa:'/ˈaʊtsɔːrs/', meaning:'thuê ngoài, gia công ngoài', type:'verb', example:'We outsource our logistics operation.', viAnswers:['thuê ngoài', 'gia công ngoài']},
      {word:'supply chain', ipa:'/səˈplaɪ tʃeɪn/', meaning:'chuỗi cung ứng', type:'noun', example:'The supply chain is complex.', viAnswers:['chuỗi cung ứng']},
      {word:'optimize', ipa:'/ˈɑːptɪmaɪz/', meaning:'tối ưu hóa', type:'verb', example:'Optimize the shipping route.', viAnswers:['tối ưu hóa', 'tối ưu']},
      {word:'bottleneck', ipa:'/ˈbɑːtəlnek/', meaning:'điểm nghẽn, trở ngại lớn', type:'noun', example:'Port delays are a bottleneck for shipping.', viAnswers:['điểm nghẽn', 'trở ngại']},
      {word:'transit', ipa:'/ˈtrænsɪt/', meaning:'vận chuyển, quá cảnh', type:'noun', example:'Transit times are long.', viAnswers:['vận chuyển', 'quá cảnh']},
      {word:'handling fee', ipa:'/ˈhændlɪŋ fiː/', meaning:'phí bốc dỡ hàng', type:'noun', example:'There is a handling fee.', viAnswers:['phí bốc dỡ', 'phí xử lý']}
    ]
  },

  {
    day: 55,
    topic: "Khiếu nại",
    topicEn: "Complaints",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 4)",
      explanation: "Ôn tập cách viết email/thư khiếu nại và phản hồi - dạng hay gặp trong TOEIC Part 6 & 7. Cấu trúc thư khiếu nại: 1) Mở đầu: nêu vấn đề (I am writing to complain about...), 2) Thân bài: mô tả chi tiết vấn đề, 3) Kết luận: yêu cầu giải pháp (I would like a refund/replacement...). Cấu trúc thư phản hồi: xin lỗi → giải thích → đề xuất giải pháp.",
      structure: "Khiếu nại: Problem → Details → Request | Phản hồi: Apology → Explanation → Solution",
      examples: ["I am writing to complain about the service I received.", "The product was damaged when it arrived.", "I would like a full refund.", "We sincerely apologize for the inconvenience."],
      exceptions: [],
      notes: [],
      tips: "Trong TOEIC, thường hỏi: 'What is the purpose of the email?' → Mục đích. 'What does the customer want?' → Yêu cầu. 'What will the company do?' → Giải pháp."
    },
    words: [
      {word:'dissatisfied', ipa:'/dɪsˈsætɪsfaɪd/', meaning:'không hài lòng, bất mãn', type:'adjective', example:'The dissatisfied client wanted a refund.', viAnswers:['không hài lòng', 'bất mãn']},
      {word:'inconvenience', ipa:'/ˌɪnkənˈviːniəns/', meaning:'sự bất tiện', type:'noun / verb', example:'We apologize for the inconvenience caused.', viAnswers:['bất tiện', 'sự bất tiện']},
      {word:'compensation', ipa:'/ˌkɑːmpənˈseɪʃən/', meaning:'sự bồi thường, đền bù thiệt hại', type:'noun', example:'We offered compensation for the delay.', viAnswers:['bồi thường', 'sự bồi thường']},
      {word:'escalate', ipa:'/ˈeskəleɪt/', meaning:'chuyển lên cấp trên giải quyết, leo thang', type:'verb', example:'The complaint was escalated to the director.', viAnswers:['chuyển lên cấp trên', 'leo thang']},
      {word:'supervisor', ipa:'/ˈsuːpərvaɪzər/', meaning:'giám sát viên', type:'noun', example:'Talk to the shift supervisor.', viAnswers:['giám sát viên']},
      {word:'investigate', ipa:'/ɪnˈvestɪɡeɪt/', meaning:'điều tra làm rõ', type:'verb', example:'We will investigate the matter.', viAnswers:['điều tra', 'làm rõ']},
      {word:'satisfaction', ipa:'/ˌsætɪsˈfækʃən/', meaning:'sự hài lòng', type:'noun', example:'Customer satisfaction is our goal.', viAnswers:['sự hài lòng']},
      {word:'apologize', ipa:'/əˈpɑːlədʒaɪz/', meaning:'xin lỗi', type:'verb', example:'We apologize for the error.', viAnswers:['xin lỗi']},
      {word:'resolution', ipa:'/ˌrezəˈluːʃən/', meaning:'sự giải quyết, nghị quyết', type:'noun', example:'We reached a quick resolution.', viAnswers:['giải quyết', 'sự giải quyết']},
      {word:'refund', ipa:'/ˈriːfʌnd/', meaning:'hoàn tiền', type:'noun / verb', example:'We will issue a full refund.', viAnswers:['hoàn tiền']},
      {word:'replacement', ipa:'/rɪˈpleɪsmənt/', meaning:'sự thay thế, hàng thay thế', type:'noun', example:'We sent a replacement immediately.', viAnswers:['thay thế', 'hàng thay thế']},
      {word:'faulty', ipa:'/ˈfɔːlti/', meaning:'bị lỗi, bị hỏng', type:'adjective', example:'Return the faulty keyboard.', viAnswers:['bị lỗi', 'hỏng']},
      {word:'warranty', ipa:'/ˈwɔːrənti/', meaning:'bảo hành', type:'noun', example:'Is the repair covered under warranty?', viAnswers:['bảo hành']},
      {word:'complaint', ipa:'/kəmˈpleɪnt/', meaning:'khiếu nại', type:'noun', example:'File a formal complaint.', viAnswers:['khiếu nại', 'lời phàn nàn']},
      {word:'defective', ipa:'/dɪˈfektɪv/', meaning:'lỗi hỏng, có khuyết tật', type:'adjective', example:'Return the defective goods.', viAnswers:['lỗi hỏng', 'bị lỗi']},
      {word:'malfunction', ipa:'/ˌmælˈfʌŋkʃən/', meaning:'sự cố trục trặc máy móc', type:'noun / verb', example:'The printer malfunctioned.', viAnswers:['trục trặc', 'sự cố']},
      {word:'reimburse', ipa:'/ˌriːɪmˈbɜːrs/', meaning:'hoàn lại tiền mặt', type:'verb', example:'We will reimburse your travel costs.', viAnswers:['hoàn tiền', 'trả lại chi phí']},
      {word:'frustrated', ipa:'/ˈfrʌstreɪtɪd/', meaning:'bực bội, bất lực', type:'adjective', example:'The customer was frustrated with the service.', viAnswers:['bực bội', 'thất vọng']},
      {word:'policy', ipa:'/ˈpɑːləsi/', meaning:'chính sách', type:'noun', example:'Read the customer return policy.', viAnswers:['chính sách']},
      {word:'negligence', ipa:'/ˈneɡlɪdʒəns/', meaning:'sự cẩu thả, sự tắc trách', type:'noun', example:'The damage was due to negligence.', viAnswers:['cẩu thả', 'sự cẩu thả', 'tắc trách']},
      {word:'amends', ipa:'/əˈmendz/', meaning:'sự bồi thường, làm hòa đền bù', type:'noun', example:'We offered a gift card to make amends.', viAnswers:['bồi thường', 'đền bù']},
      {word:'settle', ipa:'/ˈsetəl/', meaning:'giải quyết ổn thỏa, dàn xếp', type:'verb', example:'The dispute was settled out of court.', viAnswers:['giải quyết', 'dàn xếp']}
    ]
  },

  {
    day: 56,
    topic: "Lễ kỷ niệm / Chúc mừng",
    topicEn: "Celebrations",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 5)",
      explanation: "Ôn tập toàn diện tất cả ngữ pháp đã học trong 56 ngày. Checklist cuối cùng: ✓ Từ loại (noun, verb, adj, adv), ✓ Thì động từ (12 thì), ✓ Giới từ (in, on, at, by, for, with...), ✓ Liên từ (and, but, because, although...), ✓ Đại từ (I, me, my, mine, myself...), ✓ Câu bị động (be + V3), ✓ So sánh (more/most, -er/-est, as...as).",
      structure: "Ôn tập toàn bộ → Làm bài tập tổng hợp → Sửa lỗi → Ghi nhớ",
      examples: ["The ___ ceremony was held at the hotel. (award - từ loại)", "They ___ the company's 10th anniversary. (celebrated - thì quá khứ đơn)", "The event was ___ by the marketing team. (organized - bị động)", "This year's celebration is ___ than last year's. (bigger - so sánh hơn)"],
      exceptions: [],
      notes: [],
      tips: "Trước ngày thi, tập trung vào những điểm ngữ pháp mình HAY SAI nhất. Làm lại các bài tập đã sai. Ghi nhớ bằng cách viết lại câu đúng 3 lần."
    },
    words: [
      {word:'commemorate', ipa:'/kəˈmeməreɪt/', meaning:'kỷ niệm, tưởng niệm', type:'verb', example:'A banquet was held to commemorate our 20th anniversary.', viAnswers:['kỷ niệm', 'tưởng niệm']},
      {word:'achievement', ipa:'/əˈtʃiːvmənt/', meaning:'thành tích, thành tựu', type:'noun', example:'The sales team celebrated their achievements.', viAnswers:['thành tích', 'thành tựu']},
      {word:'milestone', ipa:'/ˈmaɪlstoʊn/', meaning:'cột mốc quan trọng', type:'noun', example:'Reaching one million users is a major milestone.', viAnswers:['cột mốc', 'mốc quan trọng']},
      {word:'banquet', ipa:'/ˈbæŋkwɪt/', meaning:'tiệc lớn chiêu đãi', type:'noun', example:'The year-end banquet was held at the Ritz.', viAnswers:['tiệc lớn', 'tiệc chiêu đãi']},
      {word:'reception', ipa:'/rɪˈsepʃən/', meaning:'tiệc chiêu đãi tiếp tân', type:'noun', example:'A cocktail reception followed the meeting.', viAnswers:['tiệc chiêu đãi', 'lễ tân']},
      {word:'gala', ipa:'/ˈɡeɪlə/', meaning:'hội dạ yến, đại tiệc liên hoan', type:'noun / adjective', example:'The charity gala raised $10,000.', viAnswers:['đại tiệc', 'hội liên hoan']},
      {word:'toast', ipa:'/toʊst/', meaning:'nâng ly chúc mừng, lát bánh mì nướng', type:'noun / verb', example:'Let\'s make a toast to the new project.', viAnswers:['nâng ly', 'nâng cốc chúc mừng']},
      {word:'congratulate', ipa:'/kənˈɡrætʃəleɪt/', meaning:'chúc mừng', type:'verb', example:'We congratulated her on her promotion.', viAnswers:['chúc mừng']},
      {word:'appreciation', ipa:'/əˌpriːʃiˈeɪʃən/', meaning:'sự đánh giá cao, trân trọng', type:'noun', example:'The gift is a token of our appreciation.', viAnswers:['trân trọng', 'sự đánh giá cao']},
      {word:'dedication', ipa:'/ˌdedɪˈkeɪʃən/', meaning:'sự cống hiến', type:'noun', example:'We celebrate your dedication.', viAnswers:['cống hiến', 'sự cống hiến']},
      {word:'honor', ipa:'/ˈɑːnər/', meaning:'tôn vinh, vinh danh', type:'verb / noun', example:'They honored long-serving employees.', viAnswers:['vôn vinh', 'vinh danh', 'danh dự']},
      {word:'gathering', ipa:'/ˈɡæðərɪŋ/', meaning:'buổi tụ họp, cuộc gặp gỡ', type:'noun', example:'A small family gathering.', viAnswers:['tụ họp', 'cuộc họp mặt']},
      {word:'reunion', ipa:'/ˌriːˈuːnjən/', meaning:'buổi sum họp, họp mặt', type:'noun', example:'The class reunion was held online.', viAnswers:['sum họp', 'họp mặt']},
      {word:'memorable', ipa:'/ˈmemərəbəl/', meaning:'đáng nhớ', type:'adjective', example:'It was a memorable celebration.', viAnswers:['đáng nhớ']},
      {word:'outstanding', ipa:'/aʊtˈstændɪŋ/', meaning:'nổi bật, xuất sắc', type:'adjective', example:'An outstanding performance.', viAnswers:['xuất sắc', 'nổi bật']},
      {word:'acclaim', ipa:'/əˈkleɪm/', meaning:'ca ngợi, hoan nghênh', type:'noun / verb', example:'The project won critical acclaim.', viAnswers:['ca ngợi', 'hoan nghênh']},
      {word:'distinction', ipa:'/dɪˈstɪŋkʃən/', meaning:'sự ưu tú, sự phân biệt', type:'noun', example:'He served with distinction.', viAnswers:['ưu tú', 'sự xuất sắc']},
      {word:'plaque', ipa:'/plæk/', meaning:'tấm vinh danh, kỷ niệm chương', type:'noun', example:'He received a gold plaque.', viAnswers:['kỷ niệm chương', 'bản vinh danh']},
      {word:'award', ipa:'/əˈwɔːrd/', meaning:'giải thưởng', type:'noun', example:'The award ceremony was televised.', viAnswers:['giải thưởng']},
      {word:'tribute', ipa:'/ˈtrɪbjuːt/', meaning:'vật phẩm tôn vinh, lòng tri ân', type:'noun', example:'Pay tribute to the founder.', viAnswers:['tri ân', 'tôn vinh']},
      {word:'festivity', ipa:'/feˈstɪvəti/', meaning:'hoạt động lễ hội, sự vui vẻ lễ hội', type:'noun', example:'The wedding festivities lasted for days.', viAnswers:['lễ hội', 'hoạt động lễ hội']},
      {word:'jubilee', ipa:'/ˈdʒuːbɪliː/', meaning:'lễ kỷ niệm năm tròn (bạc, vàng, kim cương)', type:'noun', example:'The company celebrated its silver jubilee (25 years).', viAnswers:['lễ kỷ niệm', 'lễ kỷ niệm năm tròn']}
    ]
  },

  {
    day: 57,
    topic: "Bài thi thử",
    topicEn: "Practice Test",
    phase: 3,
    isReview: true,
    reviewDays: [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
    grammar: {
      title: "Bài thi thử TOEIC",
      explanation: "Hôm nay bạn sẽ làm bài thi thử TOEIC để đánh giá trình độ hiện tại. Hãy làm bài trong điều kiện giống thi thật: 1) Không sử dụng từ điển, 2) Tính giờ nghiêm túc (Listening: 45 phút, Reading: 75 phút), 3) Không dừng lại quá lâu ở câu khó, 4) Ghi lại các câu sai để ôn tập.",
      structure: "",
      examples: [],
      exceptions: [],
      notes: [],
      tips: "Làm bài thi thử, chữa lỗi, ghi lại lỗi sai. Tập trung vào những phần còn yếu."
    },
    words: []
  },

  {
    day: 58,
    topic: "Ôn tập lỗi sai",
    topicEn: "Review Mistakes",
    phase: 3,
    isReview: true,
    reviewDays: [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
    grammar: {
      title: "Ôn tập lỗi sai",
      explanation: "Xem lại tất cả các lỗi sai từ bài thi thử ngày 57. Phân loại lỗi sai theo nhóm: 1) Lỗi từ vựng: học lại từ đã quên, 2) Lỗi ngữ pháp: ôn lại quy tắc, 3) Lỗi nghe: luyện nghe lại đoạn bị sai, 4) Lỗi đọc hiểu: luyện đọc lại bài. Ghi chú lỗi vào sổ tay để tránh lặp lại.",
      structure: "",
      examples: [],
      exceptions: [],
      notes: [],
      tips: "Làm bài tập, chữa lỗi, ghi lại lỗi sai. Ôn lại từ vựng các ngày trước."
    },
    words: []
  },

  {
    day: 59,
    topic: "Ôn tập tổng kết",
    topicEn: "Final Review",
    phase: 3,
    isReview: true,
    reviewDays: [1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
    grammar: {
      title: "Ôn tập tổng kết toàn bộ khóa học",
      explanation: "Đây là ngày ôn tập tổng kết toàn bộ 60 ngày học. Hãy: 1) Ôn lại tất cả từ vựng từ ngày 1 đến ngày 56, 2) Làm lại các bài tập ngữ pháp khó, 3) Luyện nghe 1-2 bài TOEIC hoàn chỉnh, 4) Đọc lại các dạng bài Reading Part 5, 6, 7, 5) Ghi nhớ các mẹo làm bài thi.",
      structure: "",
      examples: [],
      exceptions: [],
      notes: [],
      tips: "Làm bài tập, chữa lỗi, ghi lại lỗi sai. Ôn lại tất cả từ vựng và ngữ pháp đã học."
    },
    words: []
  },

  {
    day: 60,
    topic: "Chuẩn bị thi",
    topicEn: "Test Preparation",
    phase: 3,
    isReview: true,
    reviewDays: [1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
    grammar: {
      title: "Chuẩn bị trước ngày thi",
      explanation: "Ngày cuối cùng trước kỳ thi TOEIC. Checklist chuẩn bị: 1) ĐÊM TRƯỚC: ngủ đủ giấc (7-8 tiếng), chuẩn bị giấy tờ (CMND/CCCD, phiếu dự thi), bút chì 2B, gôm. 2) SÁNG THI: ăn sáng nhẹ, đến sớm 30 phút, giữ bình tĩnh. 3) KHI THI: quản lý thời gian, không dừng quá lâu ở câu khó, tô đáp án cẩn thận. 4) CHIẾN LƯỢC: Listening - đọc trước câu hỏi, Reading - làm Part 5 trước (nhanh), dành thời gian cho Part 7.",
      structure: "",
      examples: [],
      exceptions: [],
      notes: [],
      tips: "Nghỉ ngơi đầy đủ, tự tin vào bản thân. Bạn đã chuẩn bị tốt trong 60 ngày qua. Chúc bạn thi tốt! 🎯"
    },
    words: []
  }
];
