const DAYS_DATA_PART2 = [
  {
    day: 21,
    topic: "Tài chính",
    topicEn: "Finance",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Nhận diện Từ loại qua Hậu tố (Suffixes)",
      explanation: "Trong đề thi TOEIC Part 5, các câu hỏi về từ loại chiếm số lượng lớn. Việc nhớ đuôi từ loại giúp bạn chọn ngay đáp án đúng trong 3 giây.\n\n1. Hậu tố của Danh từ (Noun Suffixes):\n- Chỉ vật/sự việc/trạng thái: -tion/-sion (decision), -ment (agreement), -ness (business), -ity (priority), -ance/-ence (performance), -ship (partnership), -ing (training).\n- Chỉ người: -er/-or (manager, visitor), -ist (specialist), -ee (employee - người nhận hành động), -ant (assistant, applicant).\n\n2. Hậu tố của Tính từ (Adjective Suffixes):\n- -ful (helpful), -less (useless), -able/-ible (reliable, flexible), -ive (creative), -ous (famous), -al (professional), -ic (specific), -y (busy).\n\n3. Hậu tố của Động từ (Verb Suffixes):\n- -ize/-ise (organize), -ate (create), -ify (simplify), -en (shorten).\n\n4. Hậu tố của Trạng từ (Adverb Suffixes):\n- Hầu hết trạng từ kết thúc bằng đuôi -ly (Tính từ + ly).",
      structure: "Word + Suffix = Part of Speech",
      examples: ["develop (V) -> development (N) -> developing/developed (Adj)", "rely (V) -> reliability (N) -> reliable (Adj) -> reliably (Adv)", "beauty (N) -> beautify (V) -> beautiful (Adj) -> beautifully (Adv)"],
      exceptions: ["<b>BẪY CỰC LỚN TRONG TOEIC:</b> Một số từ kết thúc bằng đuôi <b>-al</b> nhưng lại là DANH TỪ chứ không phải tính từ: <i>proposal (đề xuất), approval (phê duyệt), arrival (sự đến nơi), renewal (sự gia hạn), disposal (sự vứt bỏ), referral (thư giới thiệu)</i>.", "Một số từ kết thúc bằng đuôi <b>-ive</b> nhưng lại là DANH TỪ: <i>representative (người đại diện), initiative (sáng kiến), alternative (sự thay thế), objective (mục tiêu)</i>.", "Một số từ có đuôi <b>-ly</b> vừa là tính từ vừa là trạng từ: <i>daily, weekly, monthly, yearly, early</i>."],
      notes: ["Mẹo tìm tính từ nhanh trong 4 đáp án: Hãy tìm trạng từ kết thúc bằng đuôi <b>-ly</b>, sau đó bỏ đuôi <b>-ly</b> đi ta sẽ thu được tính từ tương ứng."],
      tips: "Mẹo: Nếu phân vân giữa các đáp án, hãy tìm trạng từ đuôi -ly trước. Bỏ đuôi -ly đi bạn sẽ thu được Tính từ. Từ đó loại trừ và suy ra đáp án đúng."
    },
    words: [
      {word:'lease', ipa:'/liːs/', meaning:'hợp đồng cho thuê, cho thuê', type:'noun / verb', example:'They signed a three-year lease.', viAnswers:['cho thuê', 'hợp đồng cho thuê']},
      {word:'rent', ipa:'/rent/', meaning:'tiền thuê, thuê', type:'noun / verb', example:'The monthly rent is $500.', viAnswers:['thuê', 'tiền thuê']},
      {word:'tenant', ipa:'/ˈtenənt/', meaning:'người thuê nhà/văn phòng', type:'noun', example:'The tenant paid the rent on time.', viAnswers:['người thuê', 'người thuê nhà']},
      {word:'landlord', ipa:'/ˈlændlɔːrd/', meaning:'chủ nhà, chủ đất', type:'noun', example:'The landlord repaired the roof.', viAnswers:['chủ nhà', 'chủ đất']},
      {word:'deposit', ipa:'/dɪˈpɑːzɪt/', meaning:'tiền đặt cọc, đặt cọc, gửi tiền', type:'noun / verb', example:'You must pay a one-month deposit.', viAnswers:['đặt cọc', 'tiền đặt cọc', 'tiền gửi']},
      {word:'utilities', ipa:'/juːˈtɪlɪtiz/', meaning:'dịch vụ điện, nước, tiện ích', type:'noun', example:'Rent does not include utilities.', viAnswers:['tiện ích', 'điện nước', 'tiền điện nước']},
      {word:'amenities', ipa:'/əˈmenətiz/', meaning:'các tiện nghi (hồ bơi, phòng gym...)', type:'noun', example:'The apartment has many amenities.', viAnswers:['tiện nghi', 'các tiện nghi']},
      {word:'terminate', ipa:'/ˈtɜːrməneɪt/', meaning:'chấm dứt, kết thúc', type:'verb', example:'You can terminate the lease early.', viAnswers:['chấm dứt', 'kết thúc']},
      {word:'occupy', ipa:'/ˈɑːkjəpaɪ/', meaning:'ở, chiếm đóng, sử dụng', type:'verb', example:'The office is currently occupied.', viAnswers:['ở', 'chiếm đóng', 'sử dụng']},
      {word:'vacant', ipa:'/ˈveɪkənt/', meaning:'trống, bỏ không', type:'adjective', example:'There are some vacant offices.', viAnswers:['trống', 'bỏ không', 'nhàn rỗi']},
      {word:'sublet', ipa:'/ˌsʌbˈlet/', meaning:'cho thuê lại', type:'verb', example:'You need permission to sublet.', viAnswers:['cho thuê lại']},
      {word:'renovate', ipa:'/ˈrenəveɪt/', meaning:'cải tạo, nâng cấp, trùng tu', type:'verb', example:'The building was renovated last year.', viAnswers:['cải tạo', 'nâng cấp', 'trùng tu']},
      {word:'property', ipa:'/ˈprɑːpərti/', meaning:'tài sản, bất động sản', type:'noun', example:'He manages several properties.', viAnswers:['bất động sản', 'tài sản']},
      {word:'location', ipa:'/loʊˈkeɪʃən/', meaning:'vị trí, địa điểm', type:'noun', example:'The office is in a prime location.', viAnswers:['vị trí', 'địa điểm']},
      {word:'agreement', ipa:'/əˈgriːmənt/', meaning:'thỏa thuận, hợp đồng', type:'noun', example:'They signed a lease agreement.', viAnswers:['hợp đồng', 'thỏa thuận']},
      {word:'negotiate', ipa:'/nɪˈɡoʊʃieɪt/', meaning:'đàm phán, thương lượng', type:'verb', example:'We negotiated a lower rent.', viAnswers:['đàm phán', 'thương lượng']},
      {word:'maintenance', ipa:'/ˈmeɪntənəns/', meaning:'sự bảo trì, sửa chữa', type:'noun', example:'The landlord is responsible for maintenance.', viAnswers:['bảo trì', 'sự bảo trì', 'sửa chữa']},
      {word:'furnished', ipa:'/ˈfɜːrnɪʃt/', meaning:'được trang bị đồ đạc', type:'adjective', example:'The apartment is fully furnished.', viAnswers:['được trang bị đồ đạc', 'đầy đủ nội thất']},
      {word:'square footage', ipa:'/skwer ˈfʊtɪdʒ/', meaning:'diện tích tính theo foot vuông', type:'noun', example:'What is the square footage of the office?', viAnswers:['diện tích']},
      {word:'sign', ipa:'/saɪn/', meaning:'ký tên, biển báo', type:'verb / noun', example:'Sign the lease contract.', viAnswers:['ký', 'ký tên']}
    ]
  },

  {
    day: 22,
    topic: "Nhà ở",
    topicEn: "Housing",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Từ loại sau the / a / an / my / his / her",
      explanation: "Sau các từ hạn định (the, a, an, my, his, her, their, our, this, that...) phải là DANH TỪ hoặc CỤM DANH TỪ (tính từ + danh từ).\n\nQuy tắc:\n• the/a/an/my + DANH TỪ: the house, a kitchen, my apartment\n• the/a/an/my + TÍNH TỪ + DANH TỪ: the new house, a large kitchen\n\n⚠️ KHÔNG được đặt động từ hay trạng từ ngay sau the/a/an/my.",
      structure: "the / a / an / my + (adjective) + NOUN",
      examples: ["The apartment is very nice. (apartment = noun sau the)", "She signed a new lease. (new = adj, lease = noun sau a)", "His monthly rent is $500. (monthly = adj, rent = noun sau his)"],
      exceptions: ["Nếu sau chỗ trống đã có sẵn một danh từ làm trung tâm, vị trí trống trước đó phải điền <b>tính từ</b> để bổ nghĩa cho danh từ đó chứ không điền danh từ khác. Cấu trúc: <code>a/an/the + Adj + Noun</code>."],
      notes: ["Công thức đầy đủ vị trí: <code>a/an/the/tính từ sở hữu + (Adv) + (Adj) + Danh từ</code>.", "Luôn luôn kiểm tra từ đứng ngay sau khoảng trống trước khi chọn đáp án."],
      tips: "Thấy the/a/an/my → tìm danh từ ngay sau. Nếu có 2 chỗ trống, thường là tính từ + danh từ."
    },
    words: [
      {word:'select', ipa:'/sɪˈlekt/', meaning:'lựa chọn, tuyển chọn', type:'verb / adjective', example:'Please select your preferred options.', viAnswers:['lựa chọn', 'chọn']},
      {word:'choice', ipa:'/tʃɔɪs/', meaning:'sự lựa chọn', type:'noun', example:'You have a wide choice of colors.', viAnswers:['sự lựa chọn', 'lựa chọn']},
      {word:'compare', ipa:'/kəmˈper/', meaning:'so sánh', type:'verb', example:'Compare different models before buying.', viAnswers:['so sánh']},
      {word:'criteria', ipa:'/kraɪˈtɪriə/', meaning:'tiêu chí', type:'noun', example:'What are your criteria for selecting a laptop?', viAnswers:['tiêu chí']},
      {word:'feature', ipa:'/ˈfiːtʃər/', meaning:'tính năng, đặc điểm', type:'noun', example:'Let\'s compare the features.', viAnswers:['tính năng', 'đặc điểm']},
      {word:'quality', ipa:'/ˈkwɑːləti/', meaning:'chất lượng', type:'noun', example:'We prioritize quality over price.', viAnswers:['chất lượng']},
      {word:'preference', ipa:'/ˈprefərəns/', meaning:'sự ưu tiên, sự ưa thích hơn', type:'noun', example:'What is your preference?', viAnswers:['sự ưu tiên', 'sự ưa thích']},
      {word:'recommend', ipa:'/ˌrekəˈmend/', meaning:'khuyên, tiến cử, đề xuất', type:'verb', example:'Can you recommend a good printer?', viAnswers:['khuyên', 'tiến cử', 'đề xuất', 'giới thiệu']},
      {word:'review', ipa:'/rɪˈvjuː/', meaning:'đánh giá, xem lại', type:'noun / verb', example:'Read product reviews online.', viAnswers:['đánh giá', 'xem xét', 'xem lại']},
      {word:'suit', ipa:'/suːt/', meaning:'phù hợp, bộ com-lê', type:'verb / noun', example:'This model suits our needs.', viAnswers:['phù hợp']},
      {word:'decide', ipa:'/dɪˈsaɪd/', meaning:'quyết định', type:'verb', example:'It is hard to decide which one to buy.', viAnswers:['quyết định']},
      {word:'budget', ipa:'/ˈbʌdʒɪt/', meaning:'ngân sách', type:'noun', example:'Choose a product within your budget.', viAnswers:['ngân sách']},
      {word:'brand', ipa:'/brænd/', meaning:'thương hiệu', type:'noun', example:'I prefer this brand.', viAnswers:['thương hiệu']},
      {word:'options', ipa:'/ˈɑːpʃənz/', meaning:'lựa chọn, phương án', type:'noun', example:'There are many options available.', viAnswers:['lựa chọn', 'phương án']},
      {word:'affordable', ipa:'/əˈfɔːrdəbəl/', meaning:'giá cả phải chăng', type:'adjective', example:'We need an affordable solution.', viAnswers:['giá cả phải chăng', 'hợp túi tiền']},
      {word:'durable', ipa:'/ˈdʊrəbəl/', meaning:'bền bỉ', type:'adjective', example:'We need a durable scanner.', viAnswers:['bền bỉ', 'bền']},
      {word:'efficient', ipa:'/ɪˈfɪʃənt/', meaning:'hiệu năng cao, tiết kiệm', type:'adjective', example:'This model is energy efficient.', viAnswers:['hiệu năng cao', 'hiệu quả']},
      {word:'warranty', ipa:'/ˈwɔːrənti/', meaning:'bảo hành', type:'noun', example:'Does it come with a warranty?', viAnswers:['bảo hành']},
      {word:'specification', ipa:'/ˌspesəfɪˈkeɪʃən/', meaning:'đặc tả kỹ thuật, thông số', type:'noun', example:'Check the specifications sheet.', viAnswers:['thông số', 'đặc tả kỹ thuật']},
      {word:'reliability', ipa:'/rɪˌlaɪəˈbɪləti/', meaning:'sự tin cậy, tính đáng tin', type:'noun', example:'Reliability is important for office machines.', viAnswers:['sự tin cậy', 'tính đáng tin']}
    ]
  },

  {
    day: 23,
    topic: "Môi trường",
    topicEn: "Environment",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Từ loại sau very / sau chủ ngữ",
      explanation: "1) Sau VERY, SO, TOO, QUITE, RATHER → dùng TÍNH TỪ hoặc TRẠNG TỪ:\n• very + adj: The weather is very hot.\n• very + adv: He works very carefully.\n\n2) Sau CHỦ NGỮ + BE → dùng TÍNH TỪ (không dùng trạng từ):\n• The pollution is serious. ✅\n• The pollution is seriously. ❌\n\n3) Sau CHỦ NGỮ + ĐỘNG TỪ THƯỜNG → dùng TRẠNG TỪ:\n• The temperature rises quickly. ✅",
      structure: "very/so/too + ADJ/ADV | S + be + ADJ | S + V + ADV",
      examples: ["The climate is very different. (very + adj)", "Pollution is very serious. (be + adj)", "The temperature changes quickly. (V + adv)"],
      exceptions: ["Sau trạng từ chỉ mức độ (very, extremely, highly...) thường là tính từ. Tuy nhiên, nếu sau tính từ là một danh từ, thì trạng từ đó vẫn bổ nghĩa cho tính từ đứng trước danh từ. Cấu trúc: <code>S + V + a + very + Adj + N</code>."],
      notes: ["Trạng từ có thể đứng xen vào giữa Chủ ngữ và Động từ thường để bổ nghĩa cho động từ: <code>Subject + Adverb + Verb</code> (ví dụ: <i>He quickly signed the contract</i>). Tránh nhầm lẫn điền tính từ vào đây."],
      tips: "Nhớ: sau BE → tính từ; sau VERY → tính từ hoặc trạng từ; bổ nghĩa cho động từ → trạng từ."
    },
    words: [
      {word:'shopping', ipa:'/ˈʃɑːpɪŋ/', meaning:'việc mua sắm', type:'noun', example:'Online shopping is convenient.', viAnswers:['mua sắm', 'việc mua sắm']},
      {word:'store', ipa:'/stɔːr/', meaning:'cửa hàng, lưu trữ', type:'noun / verb', example:'The store is open until 9 p.m.', viAnswers:['cửa hàng', 'lưu trữ']},
      {word:'customer', ipa:'/ˈkʌstəmər/', meaning:'khách hàng', type:'noun', example:'The customer requested a refund.', viAnswers:['khách hàng']},
      {word:'checkout', ipa:'/ˈtʃekaʊt/', meaning:'quầy thanh toán', type:'noun', example:'There is a long line at checkout.', viAnswers:['quầy thanh toán', 'thanh toán']},
      {word:'receipt', ipa:'/rɪˈsiːt/', meaning:'biên lai, hóa đơn', type:'noun', example:'Always keep your receipt.', viAnswers:['biên lai', 'hóa đơn']},
      {word:'discount', ipa:'/ˈdɪskaʊnt/', meaning:'giảm giá', type:'noun / verb', example:'Can I get a discount?', viAnswers:['giảm giá']},
      {word:'price', ipa:'/praɪs/', meaning:'giá cả', type:'noun', example:'The prices are reasonable.', viAnswers:['giá', 'giá cả']},
      {word:'item', ipa:'/ˈaɪtəm/', meaning:'mặt hàng, mặt mục', type:'noun', example:'Scan the items.', viAnswers:['mặt hàng', 'món đồ']},
      {word:'purchase', ipa:'/ˈpɜːrtʃəs/', meaning:'mua, món hàng', type:'verb / noun', example:'We purchased new supplies.', viAnswers:['mua', 'món hàng']},
      {word:'on sale', ipa:'/ɒn seɪl/', meaning:'đang giảm giá', type:'adjective phrase', example:'These shoes are on sale.', viAnswers:['giảm giá', 'đang giảm giá']},
      {word:'coupon', ipa:'/ˈkuːpɑːn/', meaning:'phiếu giảm giá, coupon', type:'noun', example:'I have a discount coupon.', viAnswers:['phiếu giảm giá', 'coupon']},
      {word:'refund', ipa:'/ˈriːfʌnd/', meaning:'hoàn tiền', type:'noun / verb', example:'She wants a full refund.', viAnswers:['hoàn tiền']},
      {word:'return', ipa:'/rɪˈtɜːrn/', meaning:'trả lại, quay lại, lợi nhuận', type:'verb / noun', example:'You can return the item within 30 days.', viAnswers:['trả lại', 'quay lại']},
      {word:'bag', ipa:'/bæɡ/', meaning:'túi, giỏ', type:'noun', example:'Put it in a plastic bag.', viAnswers:['túi', 'bao']},
      {word:'shelf', ipa:'/ʃelf/', meaning:'kệ, giá sách/đồ', type:'noun', example:'The products are on the top shelf.', viAnswers:['kệ', 'giá']},
      {word:'aisle', ipa:'/aɪl/', meaning:'lối đi giữa các dãy ghế/kệ', type:'noun', example:'You can find milk in aisle 3.', viAnswers:['lối đi', 'lối đi giữa các hàng']},
      {word:'trolley', ipa:'/ˈtrɑːli/', meaning:'xe đẩy mua hàng (shopping cart)', type:'noun', example:'Fill the trolley with groceries.', viAnswers:['xe đẩy', 'xe đẩy mua hàng']},
      {word:'cashier', ipa:'/kæˈʃɪr/', meaning:'thu ngân', type:'noun', example:'Pay the cashier.', viAnswers:['thu ngân']},
      {word:'payment', ipa:'/ˈpeɪmənt/', meaning:'sự thanh toán, tiền thanh toán', type:'noun', example:'We accept credit card payment.', viAnswers:['thanh toán', 'sự thanh toán']},
      {word:'merchandise', ipa:'/ˈmɜːrtʃəndaɪz/', meaning:'hàng hóa', type:'noun', example:'The store offers high-quality merchandise.', viAnswers:['hàng hóa']}
    ]
  },

  {
    day: 24,
    topic: "Du lịch",
    topicEn: "Travel",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Giới từ in, on, at",
      explanation: "Giới từ chỉ thời gian:\n• IN + tháng / năm / mùa / buổi: in May, in 2024, in summer, in the morning\n• ON + ngày / thứ / ngày tháng: on Monday, on June 5th, on the weekend\n• AT + giờ / thời điểm cụ thể: at 9 AM, at noon, at night, at the moment\n\nGiới từ chỉ nơi chốn:\n• IN + không gian lớn hoặc bên trong: in the city, in the hotel, in Vietnam\n• ON + bề mặt / phương tiện: on the table, on the bus, on the second floor\n• AT + địa điểm cụ thể: at the airport, at home, at the station",
      structure: "IN + tháng/năm/mùa | ON + ngày/thứ | AT + giờ/điểm cụ thể",
      examples: ["The flight arrives at 3 PM.", "We will travel in July.", "The hotel is on Main Street.", "I will meet you at the airport."],
      exceptions: ["Ta nói <i>in the morning/afternoon/evening</i> nhưng lại nói <i>on Monday morning</i> (khi có thứ cụ thể đi kèm).", "Ngoại lệ về thời gian: nói <i>at night</i> (vào ban đêm) chứ không dùng <i>in night</i>."],
      notes: ["<b>Mẹo nhớ giới từ thời gian:</b> <b>at</b> (giờ giấc, mốc thời gian cụ thể) -> <b>on</b> (ngày trong tuần, ngày tháng cụ thể, ngày lễ) -> <b>in</b> (tháng, năm, mùa, thập kỷ, thế kỷ).", "<b>Lưu ý:</b> Không dùng giới từ <i>in, on, at</i> trước các từ chỉ thời gian có chứa <i>next, last, this, every</i> (ví dụ: <i>last Sunday</i>, không viết <i>on last Sunday</i> ❌)."],
      tips: "Nhớ: AT → điểm nhỏ (giờ, địa điểm); ON → bề mặt, ngày; IN → không gian lớn, tháng/năm."
    },
    words: [
      {word:'salary', ipa:'/ˈsæləri/', meaning:'lương tháng', type:'noun', example:'The annual salary is competitive.', viAnswers:['lương', 'lương tháng']},
      {word:'wage', ipa:'/weɪdʒ/', meaning:'tiền công (trả theo giờ/ngày)', type:'noun', example:'Minimum wage laws are strictly enforced.', viAnswers:['tiền công', 'lương']},
      {word:'benefit', ipa:'/ˈbenɪfɪt/', meaning:'lợi ích, phúc lợi', type:'noun', example:'The job offer includes health benefits.', viAnswers:['lợi ích', 'phúc lợi']},
      {word:'compensation', ipa:'/ˌkɑːmpənˈseɪʃən/', meaning:'sự đền bù, lương bổng đãi ngộ', type:'noun', example:'The compensation package is generous.', viAnswers:['đãi ngộ', 'sự đền bù', 'lương bổng']},
      {word:'bonus', ipa:'/ˈboʊnəs/', meaning:'tiền thưởng', type:'noun', example:'Employees receive a performance bonus.', viAnswers:['tiền thưởng', 'thưởng']},
      {word:'insurance', ipa:'/ɪnˈʃʊrəns/', meaning:'bảo hiểm', type:'noun', example:'The company provides health insurance.', viAnswers:['bảo hiểm']},
      {word:'overtime', ipa:'/ˈoʊvərtaɪm/', meaning:'làm thêm giờ, giờ làm thêm', type:'noun / adverb', example:'You get paid extra for overtime.', viAnswers:['làm thêm giờ', 'tăng ca']},
      {word:'paycheck', ipa:'/ˈpeɪtʃek/', meaning:'phiếu trả lương, tiền lương', type:'noun', example:'He receives his paycheck every Friday.', viAnswers:['phiếu lương', 'tiền lương']},
      {word:'deduction', ipa:'/dɪˈdʌkʃən/', meaning:'sự khấu trừ, trừ bớt', type:'noun', example:'Tax deductions are listed on the slip.', viAnswers:['khấu trừ', 'sự khấu trừ']},
      {word:'earnings', ipa:'/ˈɜːrnɪŋz/', meaning:'thu nhập, lợi nhuận', type:'noun', example:'Her quarterly earnings increased.', viAnswers:['thu nhập', 'lợi nhuận']},
      {word:'payroll', ipa:'/ˈpeɪroʊl/', meaning:'bảng lương, danh sách phát lương', type:'noun', example:'We have 200 employees on the payroll.', viAnswers:['bảng lương', 'danh sách phát lương']},
      {word:'slip', ipa:'/slɪp/', meaning:'phiếu (giấy), trượt chân', type:'noun / verb', example:'Check your pay slip.', viAnswers:['phiếu', 'giấy']},
      {word:'reimburse', ipa:'/ˌriːɪmˈbɜːrs/', meaning:'hoàn tiền, trả lại chi phí đã chi', type:'verb', example:'The company will reimburse travel expenses.', viAnswers:['hoàn tiền', 'trả lại chi phí']},
      {word:'allowance', ipa:'/əˈlaʊəns/', meaning:'tiền trợ cấp, định mức chi tiêu', type:'noun', example:'Employees receive a monthly housing allowance.', viAnswers:['trợ cấp', 'tiền trợ cấp']},
      {word:'pension', ipa:'/ˈpenʃən/', meaning:'lương hưu', type:'noun', example:'The pension scheme is excellent.', viAnswers:['lương hưu', 'tiền hưu trí']},
      {word:'incentive', ipa:'/ɪnˈsentɪv/', meaning:'sự khuyến khích, động lực', type:'noun / adjective', example:'Salesmen have a strong financial incentive.', viAnswers:['khuyến khích', 'động lực']},
      {word:'retirement', ipa:'/rɪˈtaɪərmənt/', meaning:'sự nghỉ hưu', type:'noun', example:'She is planning her retirement.', viAnswers:['nghỉ hưu', 'sự nghỉ hưu']},
      {word:'raise', ipa:'/reɪz/', meaning:'tăng lương, nâng lên, nuôi nấng', type:'noun / verb', example:'I requested a pay raise.', viAnswers:['tăng lương', 'nâng lên']},
      {word:'negotiate', ipa:'/nɪˈɡoʊʃieɪt/', meaning:'đàm phán', type:'verb', example:'She wants to negotiate a higher salary.', viAnswers:['đàm phán']},
      {word:'package', ipa:'/ˈpækɪdʒ/', meaning:'gói (phúc lợi), kiện hàng, bọc lại', type:'noun / verb', example:'The benefits package is very good.', viAnswers:['gói', 'kiện hàng']}
    ]
  },

  {
    day: 25,
    topic: "Thức ăn / Nhà hàng",
    topicEn: "Food / Restaurant",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Giới từ for, to, from, with",
      explanation: "• FOR: dùng cho mục đích, thời gian, đối tượng\n  - for lunch (cho bữa trưa), for 2 hours (trong 2 giờ), for you (cho bạn)\n\n• TO: dùng cho hướng đến, người nhận\n  - go to the restaurant, give it to the waiter\n\n• FROM: dùng cho nguồn gốc, thời gian bắt đầu\n  - from 9 AM to 5 PM, from Vietnam, made from rice\n\n• WITH: dùng cho đi cùng, kèm theo\n  - coffee with milk, go with friends, a dish with vegetables",
      structure: "for + mục đích/thời gian | to + hướng đến | from + nguồn gốc | with + đi kèm",
      examples: ["This dish is for two people.", "We walked to the restaurant.", "The recipe is from Italy.", "I like coffee with sugar."],
      exceptions: ["Thông thường sau giới từ <i>to</i> là động từ nguyên mẫu (<i>to V</i>). Tuy nhiên, trong một số cụm từ cố định, <i>to</i> đóng vai trò là giới từ thực sự và đi kèm <b>V-ing hoặc Danh từ</b>: <i>look forward to + V-ing</i> (mong đợi), <i>be/get used to + V-ing</i> (quen với), <i>be committed to + V-ing</i> (cam kết), <i>object to + V-ing</i> (phản đối)."],
      notes: ["Giới từ <i>for</i> đi với khoảng thời gian trong thì Hiện tại hoàn thành (ví dụ: <i>for 3 years</i>), phân biệt với <i>since</i> đi với mốc thời gian (ví dụ: <i>since 2020</i>)."],
      tips: "FOR = cho/vì; TO = đến; FROM = từ; WITH = với/cùng."
    },
    words: [
      {word:'promotion', ipa:'/prəˈmoʊʃən/', meaning:'sự thăng tiến, sự quảng bá', type:'noun', example:'He deserved the promotion to manager.', viAnswers:['thăng tiến', 'thăng chức', 'quảng bá']},
      {word:'pension', ipa:'/ˈpenʃən/', meaning:'lương hưu, tiền trợ cấp hưu trí', type:'noun', example:'He lives comfortably on his pension.', viAnswers:['lương hưu', 'tiền hưu trí']},
      {word:'award', ipa:'/əˈwɔːrd/', meaning:'giải thưởng, trao tặng', type:'noun / verb', example:'She won an award for excellence.', viAnswers:['giải thưởng', 'trao tặng']},
      {word:'achievement', ipa:'/əˈtʃiːvmənt/', meaning:'thành tích, thành tựu', type:'noun', example:'The new design is a major achievement.', viAnswers:['thành tích', 'thành tựu']},
      {word:'recognize', ipa:'/ˈrekəɡnaɪz/', meaning:'ghi nhận, công nhận, nhận ra', type:'verb', example:'The company recognizes hard work.', viAnswers:['ghi nhận', 'công nhận', 'nhận ra']},
      {word:'contribution', ipa:'/ˌkɑːntrɪˈbjuːʃən/', meaning:'sự đóng góp', type:'noun', example:'Thank you for your valuable contribution.', viAnswers:['sự đóng góp', 'đóng góp']},
      {word:'retire', ipa:'/rɪˈtaɪər/', meaning:'nghỉ hưu', type:'verb', example:'The founder retired last year.', viAnswers:['nghỉ hưu']},
      {word:'merit', ipa:'/ˈmerɪt/', meaning:'xứng đáng, sự xuất sắc, công trạng', type:'noun / verb', example:'Promotions are based on merit.', viAnswers:['công trạng', 'sự xuất sắc', 'xứng đáng']},
      {word:'honor', ipa:'/ˈɑːnər/', meaning:'tôn vinh, vinh danh, danh dự', type:'verb / noun', example:'They honored him with a plaque.', viAnswers:['tôn vinh', 'vinh danh', 'danh dự']},
      {word:'ceremony', ipa:'/ˈserəmoʊni/', meaning:'buổi lễ, nghi lễ', type:'noun', example:'The award ceremony is tonight.', viAnswers:['buổi lễ', 'lễ']},
      {word:'nominate', ipa:'/ˈnɑːmɪneɪt/', meaning:'đề cử', type:'verb', example:'Who nominated you for the award?', viAnswers:['đề cử']},
      {word:'plaque', ipa:'/plæk/', meaning:'tấm bản vinh danh, kỷ niệm chương', type:'noun', example:'He received a commemorative plaque.', viAnswers:['kỷ niệm chương', 'bản vinh danh']},
      {word:'praise', ipa:'/preɪz/', meaning:'khen ngợi, sự ca ngợi', type:'verb / noun', example:'The manager praised the team.', viAnswers:['khen ngợi', 'ca ngợi']},
      {word:'outstanding', ipa:'/aʊtˈstændɪŋ/', meaning:'xuất sắc, còn tồn đọng (chưa thanh toán)', type:'adjective', example:'She is an outstanding employee.', viAnswers:['xuất sắc', 'nổi bật']},
      {word:'performance', ipa:'/pərˈfɔːrməns/', meaning:'hiệu suất, sự trình diễn', type:'noun', example:'His job performance is excellent.', viAnswers:['hiệu suất', 'hiệu quả', 'trình diễn']},
      {word:'eligible', ipa:'/ˈelɪdʒəbəl/', meaning:'đủ điều kiện, đủ tư cách', type:'adjective', example:'Are you eligible for the pension scheme?', viAnswers:['đủ điều kiện', 'đủ tư cách']},
      {word:'loyalty', ipa:'/ˈlɔɪəlti/', meaning:'lòng trung thành', type:'noun', example:'They rewarded his loyalty.', viAnswers:['lòng trung thành', 'sự trung thành']},
      {word:'dedication', ipa:'/ˌdedɪˈkeɪʃən/', meaning:'sự cống hiến, tận tụy', type:'noun', example:'Thank you for your dedication to the project.', viAnswers:['sự cống hiến', 'cống hiến', 'tận tụy']},
      {word:'distinction', ipa:'/dɪˈstɪŋkʃən/', meaning:'sự xuất chúng, sự phân biệt', type:'noun', example:'He served the company with distinction.', viAnswers:['sự xuất chúng', 'sự xuất sắc', 'sự phân biệt']},
      {word:'seniority', ipa:'/ˌsiːniˈɔːrəti/', meaning:'thâm niên, cấp bậc cao', type:'noun', example:'Promotions are often based on seniority.', viAnswers:['thâm niên']}
    ]
  },

  {
    day: 26,
    topic: "Giải trí",
    topicEn: "Entertainment",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Giới từ before, after, during, between",
      explanation: "• BEFORE + danh từ/V-ing: trước khi\n  - before the show, before eating\n\n• AFTER + danh từ/V-ing: sau khi\n  - after the movie, after watching\n\n• DURING + danh từ: trong suốt (nhấn mạnh khoảng thời gian)\n  - during the concert, during the game\n  ⚠️ DURING + danh từ (KHÔNG dùng DURING + số giờ → dùng FOR)\n\n• BETWEEN + A + AND + B: giữa A và B\n  - between 6 PM and 8 PM, between work and home",
      structure: "before/after + N/V-ing | during + N | between + A + and + B",
      examples: ["We had dinner before the show.", "Let us talk after the movie.", "Please be quiet during the concert.", "The game is between 3 PM and 5 PM."],
      exceptions: ["Tránh nhầm lẫn cách dùng <i>during</i> và <i>while</i>: <i>during</i> là giới từ nên theo sau bắt buộc là <b>Danh từ/Cụm danh từ</b> (ví dụ: <i>during the meeting</i>). Còn <i>while</i> là liên từ nên theo sau là một <b>mệnh đề S+V</b> hoặc <b>V-ing rút gọn</b> (ví dụ: <i>while attending the meeting</i>)."],
      notes: ["<i>before</i> và <i>after</i> vừa có thể làm giới từ (theo sau là N/V-ing), vừa làm liên từ (S+V).", "Giới từ <i>between</i> chỉ dùng khi nói về 2 đối tượng (cấu trúc: <i>between A and B</i>). Nếu từ 3 đối tượng trở lên, ta phải dùng giới từ <i>among</i>."],
      tips: "DURING + danh từ (sự kiện); FOR + khoảng thời gian (số giờ/ngày). Đừng nhầm lẫn!"
    },
    words: [
      {word:'order', ipa:'/ˈɔːrdər/', meaning:'đơn đặt hàng, đặt hàng, ra lệnh', type:'noun / verb', example:'Place an order for more printer paper.', viAnswers:['đơn hàng', 'đặt hàng']},
      {word:'supply', ipa:'/səˈplaɪ/', meaning:'cung cấp, vật phẩm cung cấp', type:'verb / noun', example:'Check the office supply closet.', viAnswers:['cung cấp', 'văn phòng phẩm', 'vật phẩm']},
      {word:'requisition', ipa:'/ˌrekwɪˈzɪʃən/', meaning:'yêu cầu chính thức, giấy yêu cầu cấp vật tư', type:'noun / verb', example:'Fill out a requisition form for a new laptop.', viAnswers:['giấy yêu cầu', 'yêu cầu']},
      {word:'approve', ipa:'/əˈpruːv/', meaning:'phê duyệt, chấp thuận', type:'verb', example:'The manager must approve your supply request.', viAnswers:['phê duyệt', 'chấp thuận']},
      {word:'vendor', ipa:'/ˈvendər/', meaning:'nhà cung cấp', type:'noun', example:'We order stationery from a local vendor.', viAnswers:['nhà cung cấp']},
      {word:'catalog', ipa:'/ˈkætəlɔːɡ/', meaning:'danh mục sản phẩm', type:'noun', example:'Browse the catalog for office chairs.', viAnswers:['danh mục', 'catalog']},
      {word:'purchase', ipa:'/ˈpɜːrtʃəs/', meaning:'mua sắm, món hàng mua', type:'verb / noun', example:'The purchasing department handles orders.', viAnswers:['mua', 'mua sắm']},
      {word:'quantity', ipa:'/ˈkwɑːntəti/', meaning:'số lượng', type:'noun', example:'Specify the quantity you want.', viAnswers:['số lượng']},
      {word:'item', ipa:'/ˈaɪtəm/', meaning:'mặt hàng', type:'noun', example:'Write down the item number.', viAnswers:['mặt hàng', 'món đồ']},
      {word:'stock', ipa:'/stɑːk/', meaning:'kho, cổ phiếu, tích trữ', type:'noun / verb', example:'The item is currently out of stock.', viAnswers:['kho', 'hàng trong kho', 'tích trữ']},
      {word:'delivery', ipa:'/dɪˈlɪvəri/', meaning:'sự giao hàng', type:'noun', example:'We expect delivery next Tuesday.', viAnswers:['giao hàng', 'sự giao hàng']},
      {word:'invoice', ipa:'/ˈɪnvɔɪs/', meaning:'hóa đơn', type:'noun', example:'Check the invoice details.', viAnswers:['hóa đơn']},
      {word:'payment', ipa:'/ˈpeɪmənt/', meaning:'sự thanh toán', type:'noun', example:'Payment is due upon receipt.', viAnswers:['thanh toán', 'sự thanh toán']},
      {word:'stationery', ipa:'/ˈsteɪʃəneri/', meaning:'văn phòng phẩm (giấy, bút...)', type:'noun', example:'We need to order more stationery.', viAnswers:['văn phòng phẩm']},
      {word:'refill', ipa:'/ˌriːˈfɪl/', meaning:'làm đầy lại, ruột thay thế', type:'verb / noun', example:'I need a pen refill.', viAnswers:['làm đầy lại', 'ruột thay thế']},
      {word:'bulk', ipa:'/bʌlk/', meaning:'số lượng lớn, số đông', type:'noun / adjective', example:'Buying in bulk saves money.', viAnswers:['số lượng lớn', 'hàng loạt']},
      {word:'cart', ipa:'/kɑːrt/', meaning:'xe đẩy, giỏ hàng', type:'noun', example:'Add items to your online shopping cart.', viAnswers:['giỏ hàng', 'xe đẩy']},
      {word:'process', ipa:'/ˈprɑːses/', meaning:'xử lý, quy trình', type:'verb / noun', example:'The order is being processed.', viAnswers:['xử lý', 'quy trình']},
      {word:'confirm', ipa:'/kənˈfɜːrm/', meaning:'xác nhận', type:'verb', example:'Please confirm the order.', viAnswers:['xác nhận']},
      {word:'track', ipa:'/træk/', meaning:'theo dõi, đường ray', type:'verb / noun', example:'Track the shipment progress.', viAnswers:['theo dõi']}
    ]
  },

  {
    day: 27,
    topic: "Giao tiếp",
    topicEn: "Communication",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Liên từ and, but, or, so",
      explanation: "Liên từ đẳng lập (Coordinating Conjunctions) nối 2 từ, cụm từ hoặc mệnh đề ngang hàng:\n\n• AND: và (thêm thông tin)\n  - She speaks English and French.\n\n• BUT: nhưng (tương phản)\n  - He listened but did not agree.\n\n• OR: hoặc (lựa chọn)\n  - Do you want to call or send an email?\n\n• SO: vì vậy (kết quả)\n  - She was busy, so she did not reply.\n\n⚠️ Trước and, but, or, so nối 2 mệnh đề → thường có DẤU PHẨY.",
      structure: "S + V, + and/but/or/so + S + V",
      examples: ["He explained the plan, and she agreed.", "I called him, but he did not answer.", "You can speak now, or you can wait.", "The meeting was long, so we were tired."],
      exceptions: ["Khi nối hai mệnh đề độc lập (mỗi vế đều có S + V hoàn chỉnh), bắt buộc phải có <b>dấu phẩy (,)</b> đứng trước liên từ <i>and, but, or, so</i>. Cấu trúc: <code>S + V, so/but/and S + V</code>."],
      notes: ["<b>Quy tắc song hành (Parallelism):</b> Các từ hoặc cụm từ được nối bởi liên từ đẳng lập phải đồng dạng với nhau (ví dụ: <i>Noun and Noun</i>, <i>Adj but Adj</i>, <i>V-ing or V-ing</i>). Đây là bẫy ngữ pháp rất hay gặp trong TOEIC."],
      tips: "AND = thêm; BUT = nhưng; OR = hoặc; SO = nên. Nhớ dấu phẩy trước liên từ khi nối 2 câu."
    },
    words: [
      {word:'shipment', ipa:'/ˈʃɪpmənt/', meaning:'sự vận chuyển, lô hàng', type:'noun', example:'The shipment of electronics is delayed.', viAnswers:['lô hàng', 'vận chuyển']},
      {word:'freight', ipa:'/freɪt/', meaning:'hàng hóa vận tải, cước phí vận chuyển', type:'noun / verb', example:'We transport goods by ocean freight.', viAnswers:['hàng hóa', 'vận tải', 'cước phí']},
      {word:'carrier', ipa:'/ˈkæriər/', meaning:'công ty vận chuyển, người vận chuyển', type:'noun', example:'The carrier is responsible for damaged goods.', viAnswers:['công ty vận chuyển', 'hãng vận chuyển', 'người vận chuyển']},
      {word:'customs', ipa:'/ˈkʌstəmz/', meaning:'hải quan', type:'noun', example:'The package is clearing customs.', viAnswers:['hải quan']},
      {word:'destination', ipa:'/ˌdestəˈneɪʃən/', meaning:'điểm đến, nơi đến', type:'noun', example:'The goods reached their destination.', viAnswers:['điểm đến', 'nơi đến']},
      {word:'transit', ipa:'/ˈtrænsɪt/', meaning:'sự đi qua, sự quá cảnh, sự chuyển vận', type:'noun / verb', example:'The goods are in transit.', viAnswers:['quá cảnh', 'chuyển vận', 'vận chuyển']},
      {word:'warehouse', ipa:'/ˈwerhaʊs/', meaning:'nhà kho, kho hàng', type:'noun / verb', example:'Keep the stock in the warehouse.', viAnswers:['nhà kho', 'kho hàng', 'kho']},
      {word:'tracking number', ipa:'/ˈtrækɪŋ ˈnʌmbər/', meaning:'mã số theo dõi', type:'noun', example:'The tracking number is on the receipt.', viAnswers:['mã vận đơn', 'mã theo dõi']},
      {word:'package', ipa:'/ˈpækɪdʒ/', meaning:'kiện hàng, bưu phẩm, đóng gói', type:'noun / verb', example:'The package was delivered today.', viAnswers:['kiện hàng', 'bưu phẩm']},
      {word:'deliver', ipa:'/dɪˈlɪvər/', meaning:'giao hàng, phát biểu', type:'verb', example:'We deliver nationwide.', viAnswers:['giao', 'giao hàng']},
      {word:'delay', ipa:'/dɪˈleɪ/', meaning:'trì hoãn, sự chậm trễ', type:'verb / noun', example:'The bad weather delayed the flight.', viAnswers:['trì hoãn', 'chậm trễ']},
      {word:'cargo', ipa:'/ˈkɑːrɡoʊ/', meaning:'hàng hóa (trên tàu, máy bay)', type:'noun', example:'The cargo ship docked this morning.', viAnswers:['hàng hóa', 'hàng']},
      {word:'insurance', ipa:'/ɪnˈʃʊrəns/', meaning:'bảo hiểm', type:'noun', example:'We bought shipping insurance.', viAnswers:['bảo hiểm']},
      {word:'handling fee', ipa:'/ˈhændlɪŋ fiː/', meaning:'phí đóng gói/xử lý hàng hóa', type:'noun', example:'There is a small handling fee.', viAnswers:['phí xử lý', 'phí đóng gói']},
      {word:'expedited', ipa:'/ˈekspədaɪtɪd/', meaning:'được thúc tiến nhanh, hỏa tốc', type:'adjective', example:'We need expedited shipping.', viAnswers:['hỏa tốc', 'nhanh', 'gấp']},
      {word:'fragile', ipa:'/ˈfrædʒəl/', meaning:'dễ vỡ', type:'adjective', example:'The box contains fragile glassware.', viAnswers:['dễ vỡ']},
      {word:'unload', ipa:'/ˌʌnˈloʊd/', meaning:'dỡ hàng, bốc dỡ', type:'verb', example:'Workers are unloading the truck.', viAnswers:['dỡ hàng', 'bốc dỡ']},
      {word:'shipper', ipa:'/ˈʃɪpər/', meaning:'người gửi hàng, chủ hàng', type:'noun', example:'Contact the shipper for invoice details.', viAnswers:['người gửi hàng', 'người gửi']},
      {word:'logistics', ipa:'/lɒˈdʒɪstɪks/', meaning:'hậu cần, logistics', type:'noun', example:'Logistics is complex.', viAnswers:['hậu cần', 'logistics']},
      {word:'on schedule', ipa:'/ɒn ˈskedʒuːl/', meaning:'đúng lịch trình, đúng giờ', type:'adjective phrase', example:'The train arrived on schedule.', viAnswers:['đúng giờ', 'đúng lịch trình']}
    ]
  },

  {
    day: 28,
    topic: "Luật pháp / Quy định",
    topicEn: "Law / Rules",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Liên từ because, although, when, if",
      explanation: "Liên từ phụ thuộc (Subordinating Conjunctions) nối mệnh đề chính với mệnh đề phụ:\n\n• BECAUSE: vì (lý do)\n  - He was fined because he broke the law.\n\n• ALTHOUGH / EVEN THOUGH: mặc dù (tương phản)\n  - Although he was guilty, the penalty was small.\n\n• WHEN: khi (thời gian)\n  - When you sign the contract, read it carefully.\n\n• IF: nếu (điều kiện)\n  - If you violate the rule, you will pay a fine.\n\n⚠️ Mệnh đề phụ thuộc có thể đứng đầu câu (có dấu phẩy) hoặc cuối câu (không cần dấu phẩy).",
      structure: "Because/Although/When/If + S + V, S + V. | S + V + because/although/when/if + S + V.",
      examples: ["Because he broke the law, he paid a fine.", "Although the rule is strict, everyone must comply.", "When the judge arrives, please stand up.", "If you sign the contract, you must follow it."],
      exceptions: ["Phân biệt liên từ (sau đó là mệnh đề S + V) và giới từ tương đương (sau đó là Cụm danh từ / V-ing):", "- Nhóm nguyên nhân: <i>because, since, as</i> (liên từ) vs. <i>because of, due to, owing to, as a result of</i> (giới từ).", "- Nhóm nhượng bộ: <i>although, even though, though</i> (liên từ) vs. <i>despite, in spite of</i> (giới từ)."],
      notes: ["Khi mệnh đề phụ thuộc (chứa liên từ) đứng đầu câu, bắt buộc phải có dấu phẩy ngăn cách giữa hai mệnh đề. Nếu mệnh đề phụ thuộc đứng sau mệnh đề chính, ta không cần dùng dấu phẩy."],
      tips: "BECAUSE = vì; ALTHOUGH = mặc dù; WHEN = khi; IF = nếu. Mệnh đề phụ đầu câu → dấu phẩy."
    },
    words: [
      {word:'invoice', ipa:'/ˈɪnvɔɪs/', meaning:'hóa đơn thanh toán', type:'noun / verb', example:'Please pay the invoice by the due date.', viAnswers:['hóa đơn', 'hóa đơn thanh toán']},
      {word:'billing', ipa:'/ˈbɪlɪŋ/', meaning:'việc xuất hóa đơn, lập hóa đơn', type:'noun', example:'Send queries to the billing department.', viAnswers:['lập hóa đơn', 'xuất hóa đơn']},
      {word:'charge', ipa:'/tʃɑːrdʒ/', meaning:'phí, tính phí, nạp điện', type:'noun / verb', example:'There is a charge for delivery.', viAnswers:['phí', 'tính phí', 'tiền phạt']},
      {word:'payment terms', ipa:'/ˈpeɪmənt tɜːrmz/', meaning:'điều khoản thanh toán', type:'noun', example:'Read the payment terms carefully.', viAnswers:['điều khoản thanh toán']},
      {word:'due date', ipa:'/duː deɪt/', meaning:'hạn thanh toán, hạn chót', type:'noun', example:'The due date is next Friday.', viAnswers:['hạn chót', 'hạn thanh toán']},
      {word:'outstanding', ipa:'/aʊtˈstændɪŋ/', meaning:'còn nợ, chưa trả, xuất sắc', type:'adjective', example:'You have an outstanding balance of $50.', viAnswers:['chưa thanh toán', 'còn nợ', 'chưa trả']},
      {word:'receipt', ipa:'/rɪˈsiːt/', meaning:'biên lai, sự nhận được', type:'noun', example:'We sent a receipt after payment.', viAnswers:['biên lai', 'sự nhận được']},
      {word:'dispute', ipa:'/dɪˈspjuːt/', meaning:'tranh chấp, tranh cãi', type:'noun / verb', example:'There is a dispute over the bill.', viAnswers:['tranh chấp', 'tranh cãi']},
      {word:'credit', ipa:'/ˈkredɪt/', meaning:'tín dụng, tiền gửi vào tài khoản, uy tín', type:'noun / verb', example:'We will credit your account next month.', viAnswers:['tín dụng', 'tiền gửi']},
      {word:'debit', ipa:'/ˈdebɪt/', meaning:'tiền trừ đi, ghi nợ', type:'noun / verb', example:'The bank debited $10 from my account.', viAnswers:['ghi nợ', 'trừ tiền']},
      {word:'itemized', ipa:'/ˈaɪtəmaɪzd/', meaning:'được chia thành từng mục nhỏ, chi tiết', type:'adjective', example:'We requested an itemized bill.', viAnswers:['chi tiết', 'phân tích từng mục']},
      {word:'overdue', ipa:'/ˌoʊvərˈduː/', meaning:'quá hạn', type:'adjective', example:'The invoice is two weeks overdue.', viAnswers:['quá hạn']},
      {word:'statement', ipa:'/ˈsteɪtmənt/', meaning:'bản sao kê, lời tuyên bố', type:'noun', example:'Check your bank statement.', viAnswers:['sao kê', 'bản sao kê', 'tuyên bố']},
      {word:'remit', ipa:'/rɪˈmɪt/', meaning:'gửi tiền thanh toán', type:'verb', example:'Please remit payment to our office.', viAnswers:['gửi tiền', 'thanh toán']},
      {word:'tax', ipa:'/tæks/', meaning:'thuế', type:'noun / verb', example:'The price includes sales tax.', viAnswers:['thuế']},
      {word:'penalty', ipa:'/ˈpenəlti/', meaning:'hình phạt, tiền phạt', type:'noun', example:'There is a penalty for late payment.', viAnswers:['tiền phạt', 'hình phạt']},
      {word:'fee', ipa:'/fiː/', meaning:'phí dịch vụ, lệ phí', type:'noun', example:'The membership fee is annual.', viAnswers:['phí', 'lệ phí']},
      {word:'balance due', ipa:'/ˈbæləns duː/', meaning:'số dư cần thanh toán', type:'noun', example:'The balance due is $100.', viAnswers:['số dư', 'tiền còn nợ']},
      {word:'reconcile', ipa:'/ˈrekənsaɪl/', meaning:'đối chiếu (kế toán), hòa giải', type:'verb', example:'We reconciled the accounts at the end of the month.', viAnswers:['đối chiếu', 'hòa giải']},
      {word:'accounting', ipa:'/əˈkaʊntɪŋ/', meaning:'kế toán, ngành kế toán', type:'noun', example:'She works in accounting.', viAnswers:['kế toán', 'ngành kế toán']}
    ]
  },

  {
    day: 29,
    topic: "Sản xuất",
    topicEn: "Manufacturing",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mệnh đề phụ thuộc (Dependent Clauses)",
      explanation: "Mệnh đề phụ thuộc KHÔNG thể đứng một mình, phải đi kèm mệnh đề chính.\n\nCác loại mệnh đề phụ thuộc:\n1) Mệnh đề chỉ thời gian: when, while, before, after, until, as soon as\n  - When the machine stops, call the supervisor.\n  - We will wait until the parts arrive.\n\n2) Mệnh đề chỉ lý do: because, since, as\n  - Because the quality was poor, we returned the products.\n\n3) Mệnh đề chỉ điều kiện: if, unless\n  - Unless you inspect the equipment, defects may occur.\n\n4) Mệnh đề chỉ tương phản: although, even though\n  - Although the process is slow, the quality is excellent.",
      structure: "When/Before/After/If/Unless/Although + S + V, S + V.",
      examples: ["When the machine breaks down, we stop production.", "Before we ship the product, we inspect it.", "If the quality is poor, we reject the batch.", "Although the process is slow, it is very efficient."],
      exceptions: ["Trong các mệnh đề trạng ngữ chỉ thời gian hoặc điều kiện (bắt đầu bằng <i>when, as soon as, if, unless, before, after</i>), động từ được chia ở <b>thì hiện tại đơn</b> ngay cả khi hành động đó diễn ra ở tương lai. Không dùng <i>will</i> trong mệnh đề này. Ví dụ: <i>I will call you when I will arrive</i> ❌ -> <i>I will call you when I arrive</i> ✅."],
      notes: ["Mệnh đề phụ thuộc không bao giờ có thể đứng độc lập làm một câu hoàn chỉnh, nó bắt buộc phải đi kèm và bổ nghĩa cho một mệnh đề chính."],
      tips: "Mệnh đề phụ thuộc = liên từ + S + V. Luôn cần mệnh đề chính để hoàn chỉnh câu."
    },
    words: [
      {word:'inventory', ipa:'/ˈɪnvəntɔːri/', meaning:'hàng tồn kho, sự kiểm kê', type:'noun / verb', example:'We need to count the inventory.', viAnswers:['hàng tồn kho', 'kiểm kê']},
      {word:'stock', ipa:'/stɑːk/', meaning:'kho hàng, cổ phiếu, tích trữ', type:'noun / verb', example:'Keep a stock of spare parts.', viAnswers:['kho hàng', 'tích trữ']},
      {word:'warehouse', ipa:'/ˈwerhaʊs/', meaning:'nhà kho', type:'noun', example:'The warehouse is full of boxes.', viAnswers:['nhà kho', 'kho']},
      {word:'shortage', ipa:'/ˈʃɔːrtɪdʒ/', meaning:'sự thiếu hụt', type:'noun', example:'There is a shortage of skilled labor.', viAnswers:['thiếu hụt', 'sự thiếu hụt']},
      {word:'surplus', ipa:'/ˈsɜːrpləs/', meaning:'số dư, thặng dư', type:'noun / adjective', example:'We have a surplus of food supplies.', viAnswers:['thặng dư', 'số dư']},
      {word:'supply', ipa:'/səˈplaɪ/', meaning:'cung cấp, nguồn cung', type:'verb / noun', example:'We supply parts to factories.', viAnswers:['cung cấp', 'nguồn cung']},
      {word:'distribution', ipa:'/ˌdɪstrɪˈbjuːʃən/', meaning:'sự phân phối', type:'noun', example:'The distribution network is efficient.', viAnswers:['phân phối', 'sự phân phối']},
      {word:'replenish', ipa:'/rɪˈplenɪʃ/', meaning:'làm đầy lại, bổ sung', type:'verb', example:'We need to replenish our stocks.', viAnswers:['bổ sung', 'làm đầy lại']},
      {word:'shrinkage', ipa:'/ˈʃrɪŋkɪdʒ/', meaning:'sự hao hụt hàng hóa (do mất mát, hỏng)', type:'noun', example:'The store reported high inventory shrinkage.', viAnswers:['hao hụt', 'sự hao hụt']},
      {word:'barcode', ipa:'/ˈbɑːrkoʊd/', meaning:'mã vạch', type:'noun', example:'Scan the barcode on the tag.', viAnswers:['mã vạch']},
      {word:'scan', ipa:'/skæn/', meaning:'quét, nhìn lướt', type:'verb / noun', example:'Scan the barcode.', viAnswers:['quét']},
      {word:'track', ipa:'/træk/', meaning:'theo dõi', type:'verb', example:'The system tracks inventory in real time.', viAnswers:['theo dõi']},
      {word:'reorder', ipa:'/ˌriːˈɔːrdər/', meaning:'đặt hàng lại', type:'verb / noun', example:'It is time to reorder paper.', viAnswers:['đặt hàng lại']},
      {word:'shelf life', ipa:'/ʃelf laɪf/', meaning:'hạn sử dụng của sản phẩm', type:'noun', example:'Fresh milk has a short shelf life.', viAnswers:['hạn sử dụng']},
      {word:'logistics', ipa:'/lɒˈdʒɪstɪks/', meaning:'ngành hậu cần, logistics', type:'noun', example:'He manages logistics.', viAnswers:['logistics', 'hậu cần']},
      {word:'procurement', ipa:'/prəˈkjʊərmənt/', meaning:'sự thu mua, mua sắm vật tư', type:'noun', example:'He works in procurement.', viAnswers:['thu mua', 'sự thu mua']},
      {word:'supplier', ipa:'/səˈplaɪər/', meaning:'nhà cung cấp', type:'noun', example:'They are our main supplier.', viAnswers:['nhà cung cấp']},
      {word:'shipping', ipa:'/ˈʃɪpɪŋ/', meaning:'sự vận chuyển', type:'noun', example:'Shipping takes 3 days.', viAnswers:['vận chuyển', 'sự vận chuyển']},
      {word:'goods', ipa:'/ɡʊdz/', meaning:'hàng hóa', type:'noun', example:'These goods are imported.', viAnswers:['hàng hóa']},
      {word:'asset', ipa:'/ˈæset/', meaning:'tài sản, vốn quý', type:'noun', example:'Inventory is a company asset.', viAnswers:['tài sản']}
    ]
  },

  {
    day: 30,
    topic: "Tiếp thị",
    topicEn: "Marketing",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Câu bị động (Passive Voice) - Cơ bản",
      explanation: "Câu bị động được dùng khi ta muốn nhấn mạnh vào đối tượng chịu tác động của hành động, thay vì người thực hiện hành động.\n\nCác bước chuyển câu chủ động sang bị động:\n- Bước 1: Lấy Tân ngữ (O) của câu chủ động làm Chủ ngữ (S) của câu bị động.\n- Bước 2: Chia động từ be theo thì của câu chủ động và theo số của chủ ngữ mới.\n- Bước 3: Đổi động từ chính sang dạng Phân từ 2 (V3 hoặc thêm -ed).\n- Bước 4: Chuyển Chủ ngữ (S) của câu chủ động thành Tân ngữ sau giới từ by (by + O). Có thể lược bỏ by him, by her, by them, by people... nếu không quan trọng.\n\nCấu trúc bị động ở Thì Hiện tại đơn và Quá khứ đơn:\n- 1. Hiện tại đơn: S + am/is/are + V3/V-ed\n  + Chủ động: The manager checks the report.\n  + Bị động: The report is checked by the manager.\n- 2. Quá khứ đơn: S + was/were + V3/V-ed\n  + Chủ động: They built this house in 2010.\n  + Bị động: This house was built in 2010.",
      structure: "S + be + V3/V-ed (+ by O)",
      examples: ["Emails are sent every morning. (Thư điện tử được gửi đi mỗi sáng.)", "The project was approved yesterday. (Dự án đã được phê duyệt ngày hôm qua.)", "English is spoken all over the world. (Tiếng Anh được nói trên toàn thế giới.)"],
      exceptions: ["<b>Không chia bị động với Nội động từ:</b> Các nội động từ (intransitive verbs) như <i>happen, occur, exist, remain, rise, fall, arrive, look, seem</i> không bao giờ được chia ở dạng bị động. Ví dụ: viết <i>The accident was occurred</i> ❌ -> <i>The accident occurred</i> ✅."],
      notes: ["<b>Mẹo làm nhanh TOEIC:</b> Nhìn phía sau chỗ trống cần điền động từ. Nếu có Danh từ làm Tân ngữ thì chọn câu <b>Chủ động</b>. Nếu không có danh từ (thường là giới từ, trạng từ hoặc hết câu) thì chọn câu <b>Bị động</b>."],
      tips: "Mẹo: Trong đề thi TOEIC, nếu sau khoảng trống có danh từ làm tân ngữ, câu đó thường ở dạng Chủ động. Nếu sau khoảng trống là giới từ (by, to, in...) hoặc không có danh từ nào, câu đó thường ở dạng Bị động."
    },
    words: [
      {word:'account', ipa:'/əˈkaʊnt/', meaning:'tài khoản, tài khoản ngân hàng, báo cáo', type:'noun / verb', example:'I opened a bank account.', viAnswers:['tài khoản', 'sự chia sẻ']},
      {word:'transaction', ipa:'/trænˈzækʃən/', meaning:'giao dịch', type:'noun', example:'Keep a record of your transactions.', viAnswers:['giao dịch']},
      {word:'deposit', ipa:'/dɪˈpɑːzɪt/', meaning:'gửi tiền vào tài khoản, đặt cọc', type:'verb / noun', example:'I deposited $100 in my account.', viAnswers:['gửi tiền', 'đặt cọc', 'tiền gửi']},
      {word:'withdraw', ipa:'/wɪðˈdrɔː/', meaning:'rút tiền, rút lui', type:'verb', example:'I need to withdraw some cash.', viAnswers:['rút tiền', 'rút', 'rút lui']},
      {word:'balance', ipa:'/ˈbæləns/', meaning:'số dư tài khoản, sự cân bằng', type:'noun / verb', example:'What is my account balance?', viAnswers:['số dư', 'cân bằng']},
      {word:'interest rate', ipa:'/ˈɪntrəst reɪt/', meaning:'lãi suất', type:'noun', example:'Interest rates are low now.', viAnswers:['lãi suất']},
      {word:'loan', ipa:'/loʊn/', meaning:'khoản vay, cho vay', type:'noun / verb', example:'I applied for a bank loan.', viAnswers:['khoản vay', 'cho vay']},
      {word:'mortgage', ipa:'/ˈmɔːrɡɪdʒ/', meaning:'khoản thế chấp (mua nhà)', type:'noun / verb', example:'We have a 25-year mortgage.', viAnswers:['thế chấp', 'khoản thế chấp']},
      {word:'transfer', ipa:'/trænsˈfɜːr/', meaning:'chuyển khoản, thuyên chuyển', type:'verb / noun', example:'Transfer the funds to my account.', viAnswers:['chuyển khoản', 'chuyển']},
      {word:'fee', ipa:'/fiː/', meaning:'lệ phí, phí', type:'noun', example:'There is a fee for wire transfers.', viAnswers:['phí', 'lệ phí']},
      {word:'statement', ipa:'/ˈsteɪtmənt/', meaning:'sao kê tài khoản, tuyên bố', type:'noun', example:'I received my monthly bank statement.', viAnswers:['sao kê', 'tuyên bố']},
      {word:'overdraft', ipa:'/ˈoʊvərdræft/', meaning:'sự chi bội, thấu chi', type:'noun', example:'He has a $500 overdraft limit.', viAnswers:['thấu chi', 'chi bội']},
      {word:'savings', ipa:'/ˈseɪvɪŋz/', meaning:'tiền tiết kiệm', type:'noun', example:'I keep my savings in this account.', viAnswers:['tiền tiết kiệm', 'tiết kiệm']},
      {word:'teller', ipa:'/ˈtelər/', meaning:'giao dịch viên ngân hàng', type:'noun', example:'Talk to the bank teller.', viAnswers:['giao dịch viên']},
      {word:'branch', ipa:'/bræntʃ/', meaning:'chi nhánh, cành cây', type:'noun', example:'Our bank has a branch near your office.', viAnswers:['chi nhánh']},
      {word:'atm', ipa:'/ˌeɪ tiː ˈem/', meaning:'máy rút tiền tự động ATM', type:'noun', example:'Where is the nearest ATM?', viAnswers:['máy ATM', 'ATM']},
      {word:'direct deposit', ipa:'/dəˈrekt dɪˈpɑːzɪt/', meaning:'chuyển khoản lương trực tiếp', type:'noun', example:'My salary is paid via direct deposit.', viAnswers:['chuyển khoản trực tiếp']},
      {word:'currency', ipa:'/ˈkɜːrənsi/', meaning:'tiền tệ', type:'noun', example:'The local currency is the dong.', viAnswers:['tiền tệ']},
      {word:'exchange rate', ipa:'/ɪksˈtʃeɪndʒ reɪt/', meaning:'tỷ giá hối đoái', type:'noun', example:'Check the exchange rate.', viAnswers:['tỷ giá', 'tỷ giá hối đoái']},
      {word:'credit card', ipa:'/ˈkredɪt kɑːrd/', meaning:'thẻ tín dụng', type:'noun', example:'Pay with credit card.', viAnswers:['thẻ tín dụng']}
    ]
  },

  {
    day: 31,
    topic: "Nhân sự",
    topicEn: "Human Resources",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Bị động các thì tiếp diễn và hoàn thành",
      explanation: "Cấu trúc bị động ở các thì phức tạp hơn:\n\n1. Bị động thì Hiện tại tiếp diễn: S + am/is/are + being + V3/V-ed\n- Chủ động: She is writing a letter.\n- Bị động: A letter is being written by her.\n\n2. Bị động thì Quá khứ tiếp diễn: S + was/were + being + V3/V-ed\n- Chủ động: They were repainting the office.\n- Bị động: The office was being repainted.\n\n3. Bị động thì Hiện tại hoàn thành: S + have/has + been + V3/V-ed\n- Chủ động: The company has launched a new product.\n- Bị động: A new product has been launched by the company.",
      structure: "S + am/is/are + being + V3 | S + was/were + being + V3 | S + have/has + been + V3",
      examples: ["The road is being repaired at the moment. (Con đường đang được sửa chữa ngay lúc này.)", "Our computers have been upgraded recently. (Máy tính của chúng tôi đã được nâng cấp gần đây.)", "The report was being typed when the power went out. (Bản báo cáo đang được gõ thì mất điện.)"],
      exceptions: ["Bị động thì hiện tại hoàn thành có cấu trúc: <code>S + have/has + been + V3/V-ed</code>. Tránh nhầm lẫn bỏ sót từ <b>been</b> dẫn đến viết sai thành câu chủ động."],
      notes: ["Bị động thì tiếp diễn luôn chứa từ <b>being</b> ngay trước động từ phân từ 2: <code>S + am/is/are/was/were + being + V3/V-ed</code>. Mẹo nhớ: 'Tiếp diễn cần -ing -> dùng being'."],
      tips: "Mẹo: Để nhận biết bị động tiếp diễn, hãy tìm các dấu hiệu như at the moment, right now, currently. Với bị động hoàn thành, tìm các từ already, recently, lately, since, for."
    },
    words: [
      {word:'accounting', ipa:'/əˈkaʊntɪŋ/', meaning:'ngành kế toán, kế toán', type:'noun', example:'Accounting is essential for businesses.', viAnswers:['kế toán', 'ngành kế toán']},
      {word:'audit', ipa:'/ˈɔːdɪt/', meaning:'kiểm toán, cuộc kiểm toán', type:'noun / verb', example:'The company underwent an annual audit.', viAnswers:['kiểm toán', 'cuộc kiểm toán']},
      {word:'ledger', ipa:'/ˈledʒər/', meaning:'sổ cái kế toán', type:'noun', example:'Transactions are recorded in the ledger.', viAnswers:['sổ cái']},
      {word:'asset', ipa:'/ˈæset/', meaning:'tài sản, vốn quý', type:'noun', example:'Our assets include buildings and machinery.', viAnswers:['tài sản']},
      {word:'liability', ipa:'/ˌlaɪəˈbɪləti/', meaning:'nợ phải trả, trách nhiệm pháp lý', type:'noun', example:'The company has more assets than liabilities.', viAnswers:['nợ phải trả', 'trách nhiệm']},
      {word:'revenue', ipa:'/ˈrevənuː/', meaning:'doanh thu', type:'noun', example:'Company revenue grew by 10%.', viAnswers:['doanh thu']},
      {word:'expenditure', ipa:'/ɪkˈspendɪtʃər/', meaning:'sự tiêu dùng, chi tiêu, kinh phí', type:'noun', example:'The board approved capital expenditure.', viAnswers:['chi tiêu', 'sự chi tiêu', 'kinh phí']},
      {word:'profit', ipa:'/ˈprɑːfɪt/', meaning:'lợi nhuận, tiền lãi', type:'noun / verb', example:'Our net profit doubled this year.', viAnswers:['lợi nhuận', 'lợi ích', 'tiền lãi']},
      {word:'loss', ipa:'/lɔːs/', meaning:'sự thất thoát, thua lỗ', type:'noun', example:'The firm reported a loss in Q1.', viAnswers:['thua lỗ', 'thất thoát', 'sự thất thoát']},
      {word:'deficit', ipa:'/ˈdefəsɪt/', meaning:'sự thâm hụt, số tiền thâm hụt', type:'noun', example:'We have a budget deficit.', viAnswers:['thâm hụt', 'sự thâm hụt']},
      {word:'transaction', ipa:'/trænˈzækʃən/', meaning:'giao dịch', type:'noun', example:'We record every transaction.', viAnswers:['giao dịch']},
      {word:'reconcile', ipa:'/ˈrekənsaɪl/', meaning:'đối chiếu tài khoản, hòa giải', type:'verb', example:'Reconcile the bank statements.', viAnswers:['đối chiếu', 'hòa giải']},
      {word:'capital', ipa:'/ˈkæpɪtəl/', meaning:'vốn, thủ đô, chữ hoa', type:'noun / adjective', example:'We need capital to expand.', viAnswers:['vốn', 'thủ đô']},
      {word:'equity', ipa:'/ˈekwəti/', meaning:'vốn chủ sở hữu, sự công bằng', type:'noun', example:'She has equity in the business.', viAnswers:['vốn chủ sở hữu', 'công bằng']},
      {word:'depreciation', ipa:'/dɪˌpriːʃiˈeɪʃən/', meaning:'sự khấu hao, sụt giá', type:'noun', example:'Depreciation of equipment is recorded yearly.', viAnswers:['khấu hao', 'sự khấu hao', 'sụt giá']},
      {word:'balance sheet', ipa:'/ˈbæləns ʃiːt/', meaning:'bảng cân đối kế toán', type:'noun', example:'Read the company\'s balance sheet.', viAnswers:['bảng cân đối kế toán']},
      {word:'fiscal year', ipa:'/ˈfɪskəl jɪər/', meaning:'năm tài chính', type:'noun', example:'The fiscal year ends in December.', viAnswers:['năm tài chính']},
      {word:'cash flow', ipa:'/kæʃ floʊ/', meaning:'dòng tiền', type:'noun', example:'We monitor our cash flow daily.', viAnswers:['dòng tiền']},
      {word:'bookkeeping', ipa:'/ˈbʊkkiːpɪŋ/', meaning:'việc ghi chép sổ sách kế toán', type:'noun', example:'She handles bookkeeping tasks.', viAnswers:['ghi sổ', 'ghi sổ kế toán']},
      {word:'accountant', ipa:'/əˈkaʊntənt/', meaning:'kế toán viên', type:'noun', example:'Hire an accountant for tax return.', viAnswers:['kế toán viên', 'nhân viên kế toán']}
    ]
  },

  {
    day: 32,
    topic: "Ngân hàng",
    topicEn: "Banking",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Bị động với Động từ khuyết thiếu (Modal Verbs)",
      explanation: "Động từ khuyết thiếu gồm: will, can, could, must, should, may, might, have to, ought to.\n\n- Trong câu chủ động, sau động từ khuyết thiếu là động từ nguyên mẫu không to (S + Modal Verb + V-inf).\n- Trong câu bị động, cấu trúc biến đổi thành: S + Modal Verb + be + V3/V-ed.\n  + Chủ động: You must submit the report.\n  + Bị động: The report must be submitted.\n  + Chủ động: We will hold the meeting tomorrow.\n  + Bị động: The meeting will be held tomorrow.",
      structure: "S + Modal Verb (will/can/must/should...) + be + V3/V-ed",
      examples: ["The package will be delivered tomorrow. (Bưu phẩm sẽ được giao vào ngày mai.)", "This document must be signed by the director. (Tài liệu này bắt buộc phải được ký bởi giám đốc.)", "Employees should be trained before working. (Nhân viên nên được đào tạo trước khi làm việc.)", "The issue can be resolved easily. (Vấn đề có thể được giải quyết dễ dàng.)"],
      exceptions: ["Cấu trúc bị động với động từ khuyết thiếu: <code>S + can/must/should/will... + be + V3/V-ed</code>. Lưu ý từ <b>be</b> trong cấu trúc này luôn giữ nguyên mẫu, không được chia thành <i>is/are/was/were</i>."],
      notes: ["Tránh nhầm lẫn dạng bị động hoàn thành của động từ khuyết thiếu (dùng cho dự đoán quá khứ): <code>S + modal verb + have been + V3/V-ed</code> (ví dụ: <i>should have been done</i>)."],
      tips: "Mẹo: Sau các từ khuyết thiếu will, must, should, can, nếu chọn thể bị động thì cấu trúc luôn luôn có dạng be + V3/V-ed (giữ nguyên chữ be)."
    },
    words: [
      {word:'investment', ipa:'/ɪnˈvestmənt/', meaning:'khoản đầu tư, sự đầu tư', type:'noun', example:'Real estate is a good investment.', viAnswers:['khoản đầu tư', 'đầu tư', 'sự đầu tư']},
      {word:'portfolio', ipa:'/pɔːrtˈfoʊlioʊ/', meaning:'danh mục đầu tư, hồ sơ năng lực', type:'noun', example:'Diversify your investment portfolio.', viAnswers:['danh mục đầu tư', 'hồ sơ năng lực']},
      {word:'stock', ipa:'/stɑːk/', meaning:'cổ phiếu, kho hàng', type:'noun', example:'He bought stocks in tech companies.', viAnswers:['cổ phiếu', 'kho hàng']},
      {word:'bond', ipa:'/bɑːnd/', meaning:'trái phiếu, sự gắn kết', type:'noun', example:'Government bonds are safe.', viAnswers:['trái phiếu', 'sự gắn kết']},
      {word:'shareholder', ipa:'/ˈʃerhoʊldər/', meaning:'cổ đông', type:'noun', example:'Shareholders vote at the AGM.', viAnswers:['cổ đông']},
      {word:'dividend', ipa:'/ˈdɪvɪdend/', meaning:'cổ tức', type:'noun', example:'The company declared a dividend of $1 per share.', viAnswers:['cổ tức']},
      {word:'yield', ipa:'/jiːld/', meaning:'lợi suất, sản lượng, đầu hàng/nhường đường', type:'noun / verb', example:'The investment yields high returns.', viAnswers:['lợi suất', 'sản lượng', 'mang lại']},
      {word:'return', ipa:'/rɪˈtɜːrn/', meaning:'lợi nhuận, hoàn lại, quay lại', type:'noun / verb', example:'We hope for a high return on investment.', viAnswers:['lợi nhuận', 'hoàn lại']},
      {word:'risk', ipa:'/rɪsk/', meaning:'rủi ro', type:'noun', example:'All investments carry some risk.', viAnswers:['rủi ro']},
      {word:'mutual fund', ipa:'/ˈmjuːtʃuəl fʌnd/', meaning:'quỹ tương hỗ', type:'noun', example:'Invest in a mutual fund.', viAnswers:['quỹ đầu tư', 'quỹ tương hỗ']},
      {word:'diversify', ipa:'/daɪˈvɜːrsɪfaɪ/', meaning:'đa dạng hóa', type:'verb', example:'You should diversify your investments.', viAnswers:['đa dạng hóa']},
      {word:'capital gain', ipa:'/ˈkæpɪtəl ɡeɪn/', meaning:'lợi nhuận thu được từ vốn đầu tư', type:'noun', example:'Capital gains are taxable.', viAnswers:['lợi nhuận vốn']},
      {word:'broker', ipa:'/ˈbroʊkər/', meaning:'người môi giới, đại lý môi giới', type:'noun', example:'Consult a stock broker.', viAnswers:['người môi giới', 'môi giới']},
      {word:'speculate', ipa:'/ˈspekjəleɪt/', meaning:'đầu cơ, suy đoán', type:'verb', example:'He speculates on the housing market.', viAnswers:['đầu cơ', 'suy đoán']},
      {word:'volatile', ipa:'/ˈvɑːlətəl/', meaning:'biến động mạnh, dễ bay hơi', type:'adjective', example:'The stock market is very volatile.', viAnswers:['biến động', 'biến động mạnh']},
      {word:'asset allocation', ipa:'/ˈæset ˌæləˈkeɪʃən/', meaning:'phân bổ tài sản', type:'noun', example:'Decide on your asset allocation.', viAnswers:['phân bổ tài sản']},
      {word:'maturity', ipa:'/məˈtʃʊrəti/', meaning:'hạn đáo hạn, sự trưởng thành', type:'noun', example:'The bond reached maturity.', viAnswers:['đáo hạn', 'sự trưởng thành']},
      {word:'equity', ipa:'/ˈekwəti/', meaning:'cổ phần, vốn chủ sở hữu', type:'noun', example:'He has equity in the firm.', viAnswers:['cổ phần', 'vốn chủ sở hữu']},
      {word:'liquidity', ipa:'/lɪˈkwɪdəti/', meaning:'tính thanh khoản', type:'noun', example:'Cash is an asset with high liquidity.', viAnswers:['thanh khoản', 'tính thanh khoản']},
      {word:'bull market', ipa:'/bʊl ˈmɑːrkɪt/', meaning:'thị trường tăng trưởng (thị trường bò tót)', type:'noun', example:'We are currently in a bull market.', viAnswers:['thị trường tăng trưởng']}
    ]
  },

  {
    day: 33,
    topic: "Chất lượng / Dịch vụ",
    topicEn: "Quality / Service",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "So sánh hơn (Comparatives)",
      explanation: "So sánh hơn được dùng để so sánh giữa 2 người hoặc 2 vật.\n\nPhân biệt Tính từ ngắn và Tính từ dài:\n- Tính từ ngắn: Có 1 âm tiết (tall, short, big, fast), hoặc có 2 âm tiết kết thúc bằng -y, -le, -ow, -er, -et (happy, simple, narrow, clever, quiet).\n- Tính từ dài: Có từ 2 âm tiết trở lên (expensive, beautiful, difficult, professional).\n\n1. Công thức với tính từ ngắn: S + V + Adj-er + than + O\n- Cách thêm đuôi -er: tall -> taller; kết thúc bằng e chỉ thêm r (large -> larger); phụ âm + y đổi thành i-er (happy -> happier); CVC gấp đôi phụ âm cuối (big -> bigger).\n\n2. Công thức với tính từ dài: S + V + more + Adj + than + O\n- Ví dụ: more expensive than, more professional than.\n- So sánh kém hơn: less + Adj + than. Ví dụ: less difficult than.\n\n3. Các tính từ so sánh bất quy tắc (Bắt buộc thuộc lòng):\n- good/well -> better (tốt hơn)\n- bad/badly -> worse (tệ hơn)\n- far -> farther (khoảng cách vật lý) / further (chi tiết hơn, sâu hơn. Ví dụ: further information).\n- many/much -> more (nhiều hơn)\n- little -> less (ít hơn)",
      structure: "S1 + V + Adj-er + than + S2 | S1 + V + more + Adj + than + S2",
      examples: ["This laptop is faster than that one. (Chiếc laptop này nhanh hơn chiếc kia.)", "Traveling by plane is more expensive than by train. (Đi máy bay thì đắt hơn đi tàu hỏa.)", "If you need further information, please contact us. (Nếu bạn cần thêm thông tin chi tiết, vui lòng liên hệ chúng tôi.)", "He does his job better than his coworker. (Anh ấy làm công việc của mình tốt hơn đồng nghiệp.)"],
      exceptions: ["Một số tính từ/trạng từ biến đổi so sánh hơn bất quy tắc: <i>good/well -> better</i>, <i>bad/badly -> worse</i>, <i>many/much -> more</i>, <i>little -> less</i>, <i>far -> farther</i> (khoảng cách vật lý) / <i>further</i> (sâu hơn, thêm nữa).", "Tính từ 2 âm tiết kết thúc bằng đuôi <b>-y</b> vẫn được coi là tính từ ngắn: đổi <b>y</b> thành <b>i</b> rồi thêm <b>-er</b> (ví dụ: <i>easy -> easier</i>, <i>happy -> happier</i>)."],
      notes: ["Bắt buộc phải có từ <b>than</b> đứng phía sau tính từ/trạng từ so sánh trong so sánh hơn.", "Có thể thêm các trạng từ bổ nghĩa đứng trước so sánh hơn để nhấn mạnh mức độ: <i>much, far, significantly, substantially, slightly</i> (ví dụ: <i>much better, significantly higher</i>)."],
      tips: "Mẹo: Nếu trong câu có từ than, chắc chắn phải chọn so sánh hơn (Adj-er hoặc more + Adj). Các từ much, far, significantly, slightly đứng trước so sánh hơn để nhấn mạnh (ví dụ: much cheaper)."
    },
    words: [
      {word:'tax', ipa:'/tæks/', meaning:'thuế', type:'noun / verb', example:'Every citizen pays income tax.', viAnswers:['thuế']},
      {word:'income tax', ipa:'/ˈɪnkʌm tæks/', meaning:'thuế thu nhập', type:'noun', example:'Income tax rates vary by bracket.', viAnswers:['thuế thu nhập']},
      {word:'revenue', ipa:'/ˈrevənuː/', meaning:'doanh thu, nguồn thu thuế', type:'noun', example:'Taxes generate government revenue.', viAnswers:['doanh thu', 'nguồn thu']},
      {word:'audit', ipa:'/ˈɔːdɪt/', meaning:'kiểm toán, sự thanh tra thuế', type:'noun / verb', example:'The IRS audited his tax return.', viAnswers:['thanh tra thuế', 'kiểm toán']},
      {word:'deductible', ipa:'/dɪˈdʌktəbəl/', meaning:'được trừ thuế, khoản khấu trừ', type:'adjective / noun', example:'Business expenses are often tax-deductible.', viAnswers:['được trừ thuế', 'khấu trừ']},
      {word:'exemption', ipa:'/ɪɡˈzempʃən/', meaning:'sự miễn trừ', type:'noun', example:'He claimed a tax exemption for his son.', viAnswers:['miễn trừ', 'sự miễn trừ']},
      {word:'file', ipa:'/faɪl/', meaning:'nộp (đơn, tờ khai), hồ sơ, lưu trữ', type:'verb / noun', example:'You must file your tax return by April 15.', viAnswers:['nộp', 'hồ sơ', 'lưu trữ']},
      {word:'refund', ipa:'/ˈriːfʌnd/', meaning:'tiền hoàn thuế, hoàn tiền', type:'noun / verb', example:'I got a tax refund check.', viAnswers:['hoàn tiền', 'hoàn thuế']},
      {word:'withhold', ipa:'/wɪðˈhoʊld/', meaning:'giữ lại, khấu trừ tại nguồn', type:'verb', example:'Taxes are withheld from your salary.', viAnswers:['giữ lại', 'khấu trừ']},
      {word:'compliance', ipa:'/kəmˈplaɪəns/', meaning:'sự tuân thủ', type:'noun', example:'We ensure full tax compliance.', viAnswers:['tuân thủ', 'sự tuân thủ']},
      {word:'liability', ipa:'/ˌlaɪəˈbɪləti/', meaning:'khoản nợ thuế, trách nhiệm pháp lý', type:'noun', example:'Calculate your total tax liability.', viAnswers:['nợ thuế', 'trách nhiệm']},
      {word:'penalty', ipa:'/ˈpenəlti/', meaning:'tiền phạt', type:'noun', example:'There is a penalty for late filing.', viAnswers:['tiền phạt']},
      {word:'corporate tax', ipa:'/ˈkɔːrpərət tæks/', meaning:'thuế doanh nghiệp', type:'noun', example:'The corporate tax rate was reduced.', viAnswers:['thuế doanh nghiệp']},
      {word:'sales tax', ipa:'/seɪlz tæks/', meaning:'thuế tiêu thụ, thuế bán hàng', type:'noun', example:'Sales tax is added to the price.', viAnswers:['thuế tiêu thụ', 'thuế bán hàng']},
      {word:'evasion', ipa:'/ɪˈveɪʒən/', meaning:'sự trốn tránh, lẩn tránh', type:'noun', example:'Tax evasion is a serious crime.', viAnswers:['trốn tránh', 'trốn thuế']},
      {word:'bracket', ipa:'/ˈbrækɪt/', meaning:'khung thuế, dấu ngoặc đơn/kép', type:'noun', example:'I am in a higher tax bracket now.', viAnswers:['khung thuế', 'ngoặc']},
      {word:'auditor', ipa:'/ˈɔːdɪtər/', meaning:'kiểm toán viên', type:'noun', example:'The tax auditor checked our books.', viAnswers:['kiểm toán viên']},
      {word:'declare', ipa:'/dɪˈkler/', meaning:'khai báo, tuyên bố', type:'verb', example:'You must declare all your income.', viAnswers:['khai báo', 'tuyên bố']},
      {word:'deduction', ipa:'/dɪˈdʌkʃən/', meaning:'sự khấu trừ thuế', type:'noun', example:'Home office deduction can save money.', viAnswers:['khấu trừ', 'khấu trừ thuế']},
      {word:'returns', ipa:'/rɪˈtɜːrnz/', meaning:'tờ khai thuế, lợi nhuận', type:'noun', example:'We filed our tax returns.', viAnswers:['tờ khai thuế', 'tờ khai']}
    ]
  },

  {
    day: 34,
    topic: "Cuộc sống hàng ngày",
    topicEn: "Daily Life",
    phase: 2,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "So sánh nhất (Superlatives)",
      explanation: "So sánh nhất được dùng khi so sánh từ 3 đối tượng trở lên.\n\n1. Công thức với tính từ ngắn: S + V + the + Adj-est\n- Quy tắc thêm đuôi -est tương tự như thêm -er: tall -> the tallest, big -> the biggest, happy -> the happiest, simple -> the simplest.\n\n2. Công thức với tính từ dài: S + V + the + adjective_long-est (S + V + the most + Adj)\n- Ví dụ: the most expensive, the most important.\n- So sánh kém nhất: the least + Adj. Ví dụ: the least expensive.\n\n3. Các trường hợp so sánh nhất bất quy tắc:\n- good/well -> the best (tốt nhất)\n- bad/badly -> the worst (tệ nhất)\n- far -> the farthest / the furthest (xa nhất)\n- many/much -> the most (nhiều nhất)\n- little -> the least (ít nhất)",
      structure: "S + V + the + Adj-est (+ N) | S + V + the most + Adj (+ N)",
      examples: ["He is the tallest employee in our department. (Anh ấy là nhân viên cao nhất trong bộ phận của chúng tôi.)", "This is the most important project of the year. (Đây là dự án quan trọng nhất trong năm.)", "She provided the best solution to the problem. (Cô ấy đã đưa ra giải pháp tốt nhất cho vấn đề.)", "This is the least difficult task. (Đây là nhiệm vụ ít khó nhất.)"],
      exceptions: ["Tính từ/trạng từ biến đổi bất quy tắc ở so sánh nhất: <i>good/well -> the best</i>, <i>bad/badly -> the worst</i>, <i>many/much -> the most</i>, <i>little -> the least</i>, <i>far -> the farthest / the furthest</i>.", "Tương tự so sánh hơn, tính từ 2 âm tiết kết thúc bằng <b>-y</b> đổi thành <b>-iest</b> (ví dụ: <i>the easiest, the happiest</i>)."],
      notes: ["So sánh nhất bắt buộc phải đi kèm mạo từ <b>the</b> phía trước (ví dụ: <i>the most important, the fastest</i>).", "Thường có các cụm từ giới hạn phạm vi đi kèm như: <i>in the world, of all, in the team</i>, hoặc mệnh đề hiện tại hoàn thành <i>...I have ever seen</i>."],
      tips: "Mẹo: Trước vị trí so sánh nhất luôn có mạo từ the. Các cụm từ đi kèm ở vế sau để giới thiệu phạm vi so sánh thường là: in the world, in the team, of all, of the three, that I have ever seen."
    },
    words: [
      {word:'property', ipa:'/ˈprɑːpərti/', meaning:'bất động sản, tài sản', type:'noun', example:'The company owns several properties.', viAnswers:['bất động sản', 'tài sản']},
      {word:'department', ipa:'/dɪˈpɑːrtmənt/', meaning:'bộ phận, phòng ban', type:'noun', example:'She heads the accounting department.', viAnswers:['phòng ban', 'bộ phận']},
      {word:'headquarters', ipa:'/ˈhedkwɔːrtərz/', meaning:'trụ sở chính', type:'noun', example:'The corporate headquarters is in New York.', viAnswers:['trụ sở chính', 'trụ sở']},
      {word:'real estate', ipa:'/ˈriːəl ɪˌsteɪt/', meaning:'bất động sản', type:'noun', example:'He invested in commercial real estate.', viAnswers:['bất động sản']},
      {word:'premises', ipa:'/ˈpreməsɪz/', meaning:'cơ sở, khuôn viên công ty', type:'noun', example:'No smoking is allowed on the premises.', viAnswers:['khuôn viên', 'cơ sở', 'mặt bằng']},
      {word:'relocate', ipa:'/ˌriːˈloʊkeɪt/', meaning:'di dời, chuyển văn phòng/nhà', type:'verb', example:'The company will relocate to Texas.', viAnswers:['di dời', 'chuyển đi', 'chuyển địa điểm']},
      {word:'facility', ipa:'/fəˈsɪləti/', meaning:'cơ sở vật chất, trang thiết bị', type:'noun', example:'The new facility has state-of-the-art labs.', viAnswers:['cơ sở vật chất', 'trang thiết bị', 'cơ sở']},
      {word:'asset', ipa:'/ˈæset/', meaning:'tài sản', type:'noun', example:'Our office building is our biggest asset.', viAnswers:['tài sản']},
      {word:'lease', ipa:'/liːs/', meaning:'hợp đồng thuê, cho thuê', type:'noun / verb', example:'The lease on the office expires next month.', viAnswers:['cho thuê', 'hợp đồng thuê']},
      {word:'division', ipa:'/dɪˈvɪʒən/', meaning:'phân bộ, sư đoàn, phép chia', type:'noun', example:'He is the head of the sales division.', viAnswers:['phân bộ', 'phân nhánh', 'phần']},
      {word:'branch', ipa:'/bræntʃ/', meaning:'chi nhánh', type:'noun', example:'We are opening a new branch in Tokyo.', viAnswers:['chi nhánh']},
      {word:'manager', ipa:'/ˈmænɪdʒər/', meaning:'quản lý, giám đốc', type:'noun', example:'Talk to the department manager.', viAnswers:['quản lý', 'giám đốc']},
      {word:'personnel', ipa:'/ˌpɜːrsəˈnel/', meaning:'nhân viên, phòng nhân sự', type:'noun', example:'All personnel must wear ID badges.', viAnswers:['nhân sự', 'nhân viên']},
      {word:'administration', ipa:'/ədˌmɪnɪˈstreɪʃən/', meaning:'ban hành chính, sự quản trị', type:'noun', example:'Contact administration for supply requests.', viAnswers:['hành chính', 'quản trị', 'sự quản lý']},
      {word:'operations', ipa:'/ˌɑːpəˈreɪʃənz/', meaning:'hoạt động vận hành', type:'noun', example:'He oversees daily business operations.', viAnswers:['hoạt động', 'vận hành']},
      {word:'infrastructure', ipa:'/ˈɪnfrəˌstrʌktʃər/', meaning:'cơ sở hạ tầng', type:'noun', example:'The company invested in IT infrastructure.', viAnswers:['cơ sở hạ tầng']},
      {word:'relocation', ipa:'/ˌriːloʊˈkeɪʃən/', meaning:'sự di dời, sự chuyển địa điểm', type:'noun', example:'The company paid for my relocation expenses.', viAnswers:['sự di dời', 'chuyển địa điểm']},
      {word:'supervise', ipa:'/ˈsuːpərvaɪz/', meaning:'giám sát', type:'verb', example:'She supervises a team of ten engineers.', viAnswers:['giám sát']},
      {word:'coordinator', ipa:'/koʊˈɔːrdɪneɪtər/', meaning:'điều phối viên', type:'noun', example:'Ask the project coordinator for the files.', viAnswers:['điều phối viên']},
      {word:'executive', ipa:'/ɪɡˈzekjətɪv/', meaning:'ủy viên ban điều hành, cao cấp', type:'noun / adjective', example:'He is a senior executive at the firm.', viAnswers:['điều hành', 'ủy viên ban điều hành', 'sếp cao cấp']}
    ]
  },

  {
    day: 35,
    topic: "Ôn tập ngày 18-26",
    topicEn: "Review Days 18-26",
    phase: 2,
    isReview: true,
    reviewDays: [18, 19, 20, 21, 22, 23, 24, 25, 26],
    grammar: {
      title: "Ôn tập ngữ pháp",
      explanation: "Ôn lại tất cả ngữ pháp đã học từ ngày 18 đến 26:\n• Ngày 18: Ôn tập thì hiện tại / quá khứ / tương lai đơn\n• Ngày 19: Ôn tập các thì tiếp diễn và hoàn thành\n• Ngày 20: Ôn tập tổng hợp các thì\n• Ngày 21: Nhận diện từ loại (noun, verb, adj, adv)\n• Ngày 22: Từ loại sau the / a / an / my\n• Ngày 23: Từ loại sau very, sau chủ ngữ\n• Ngày 24: Giới từ in, on, at\n• Ngày 25: Giới từ for, to, from, with\n• Ngày 26: Giới từ before, after, during, between",
      structure: "",
      examples: [],
      exceptions: [],
      notes: [],
      tips: "Làm bài tập, chữa lỗi, ghi lại lỗi sai. Ôn lại từ vựng các chủ đề: Sức khỏe, Giáo dục, Công nghệ, Tài chính, Nhà ở, Môi trường, Du lịch, Thức ăn, Giải trí."
    },
    words: []
  },

  {
    day: 36,
    topic: "Ôn tập ngày 27-34",
    topicEn: "Review Days 27-34",
    phase: 2,
    isReview: true,
    reviewDays: [27, 28, 29, 30, 31, 32, 33, 34],
    grammar: {
      title: "Ôn tập ngữ pháp",
      explanation: "Ôn lại tất cả ngữ pháp đã học từ ngày 27 đến 34:\n• Ngày 27: Liên từ and, but, or, so\n• Ngày 28: Liên từ because, although, when, if\n• Ngày 29: Mệnh đề phụ thuộc\n• Ngày 30: Câu bị động - cấu trúc S + be + V3\n• Ngày 31: Bị động thì hiện tại và quá khứ đơn\n• Ngày 32: Bị động với will / can / must / should\n• Ngày 33: So sánh hơn (more...than, -er than)\n• Ngày 34: So sánh nhất (the most, the -est)",
      structure: "",
      examples: [],
      exceptions: [],
      notes: [],
      tips: "Làm bài tập, chữa lỗi, ghi lại lỗi sai. Ôn lại từ vựng các chủ đề: Giao tiếp, Luật pháp, Sản xuất, Tiếp thị, Nhân sự, Ngân hàng, Chất lượng, Cuộc sống hàng ngày."
    },
    words: []
  },

  {
    day: 37,
    topic: "Ôn tập toàn bộ Giai đoạn 2",
    topicEn: "Review Full Phase 2",
    phase: 2,
    isReview: true,
    reviewDays: [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
    grammar: {
      title: "Ôn tập ngữ pháp",
      explanation: "Ôn lại TOÀN BỘ ngữ pháp Giai đoạn 2 (ngày 18-34):\n\nCác thì: hiện tại đơn, quá khứ đơn, tương lai đơn, hiện tại tiếp diễn, hiện tại hoàn thành.\n\nTừ loại: nhận diện noun/verb/adj/adv, vị trí sau the/a/an/my, sau very, sau be.\n\nGiới từ: in/on/at, for/to/from/with, before/after/during/between.\n\nLiên từ: and/but/or/so, because/although/when/if, mệnh đề phụ thuộc.\n\nCâu bị động: be + V3, bị động các thì, bị động với modal verbs.\n\nSo sánh: so sánh hơn (-er/more), so sánh nhất (-est/the most).",
      structure: "",
      examples: [],
      exceptions: [],
      notes: [],
      tips: "Làm bài tập tổng hợp, chữa lỗi sai, ghi nhớ các quy tắc quan trọng. Tập trung vào những phần còn yếu."
    },
    words: []
  },

  {
    day: 38,
    topic: "Thời tiết / Thiên nhiên",
    topicEn: "Weather / Nature",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Chiến thuật nghe Part 1 - Mô tả tranh",
      explanation: "TOEIC Listening Part 1: Nghe 4 câu mô tả tranh, chọn câu đúng nhất.\n\nChiến thuật:\n1. TRƯỚC KHI NGHE: Quan sát tranh kỹ trong 5 giây.\n   - Tranh người: ai? đang làm gì? ở đâu? mặc gì?\n   - Tranh vật/phong cảnh: có gì? ở đâu? trạng thái nào?\n\n2. KHI NGHE: Nghe từ khóa chính (danh từ, động từ, giới từ).\n   - Chú ý: hành động đang diễn ra (be + V-ing)\n   - Cẩn thận từ phát âm giống nhau (weather/whether, sunny/Sunday)\n\n3. LOẠI TRỪ đáp án sai:\n   - Sai người/vật\n   - Sai hành động\n   - Sai vị trí",
      structure: "Mô tả tranh: S + be + V-ing (hành động) | There is/are + N (sự vật)",
      examples: ["The woman is standing in the rain.", "It is sunny outside.", "There are clouds in the sky.", "The man is wearing a jacket."],
      exceptions: [],
      notes: [],
      tips: "Nhìn tranh → đoán từ vựng → nghe và so khớp. Loại trừ đáp án sai ngay khi nghe."
    },
    words: [
      {word:'atmosphere', ipa:'/ˈætməsfɪr/', meaning:'bầu khí quyển, bầu không khí', type:'noun', example:'Carbon dioxide levels in the atmosphere are rising.', viAnswers:['bầu khí quyển', 'không khí', 'khí quyển']},
      {word:'precipitation', ipa:'/prɪˌsɪpɪˈteɪʃən/', meaning:'lượng mưa, sự kết tủa', type:'noun', example:'The forecast warns of heavy precipitation tonight.', viAnswers:['lượng mưa', 'sự kết tủa', 'mưa']},
      {word:'meteorologist', ipa:'/ˌmiːtiəˈrɑːlədʒɪst/', meaning:'nhà khí tượng học', type:'noun', example:'Meteorologists predicted the storm path accurately.', viAnswers:['nhà khí tượng học']},
      {word:'ecosystem', ipa:'/ˈiːkoʊˌsɪstəm/', meaning:'hệ sinh thái', type:'noun', example:'Pollution threatens the marine ecosystem.', viAnswers:['hệ sinh thái']},
      {word:'biodegradable', ipa:'/ˌbaɪoʊdɪˈɡreɪdəbəl/', meaning:'phân hủy sinh học', type:'adjective', example:'We use biodegradable packaging.', viAnswers:['phân hủy sinh học']},
      {word:'conservation', ipa:'/ˌkɑːnsərˈveɪʃən/', meaning:'sự bảo tồn, sự gìn giữ', type:'noun', example:'Wildlife conservation is essential.', viAnswers:['sự bảo tồn', 'bảo tồn']},
      {word:'emission', ipa:'/ɪˈmɪʃən/', meaning:'sự phát thải, khí thải', type:'noun', example:'We need to reduce greenhouse gas emissions.', viAnswers:['khí thải', 'phát thải', 'sự phát thải']},
      {word:'sustainability', ipa:'/səˌsteɪnəˈbɪləti/', meaning:'sự phát triển bền vững', type:'noun', example:'Our focus is on environmental sustainability.', viAnswers:['phát triển bền vững', 'sự bền vững']},
      {word:'conserve', ipa:'/kənˈsɜːrv/', meaning:'bảo tồn, tiết kiệm', type:'verb', example:'Conserve energy by switching off lights.', viAnswers:['bảo tồn', 'tiết kiệm', 'gìn giữ']},
      {word:'renewable', ipa:'/rɪˈnuːəbəl/', meaning:'có thể tái tạo', type:'adjective', example:'Solar power is a renewable energy source.', viAnswers:['tái tạo', 'có thể tái tạo']},
      {word:'deplete', ipa:'/dɪˈpliːt/', meaning:'làm cạn kiệt', type:'verb', example:'Fossil fuels are being rapidly depleted.', viAnswers:['cạn kiệt', 'làm cạn kiệt']},
      {word:'contamination', ipa:'/kənˌtæmɪˈneɪʃən/', meaning:'sự ô nhiễm, sự nhiễm độc', type:'noun', example:'The spill caused water contamination.', viAnswers:['ô nhiễm', 'sự ô nhiễm', 'nhiễm độc']},
      {word:'disaster', ipa:'/dɪˈzæstər/', meaning:'thảm họa', type:'noun', example:'The flood was a major natural disaster.', viAnswers:['thảm họa']},
      {word:'evacuate', ipa:'/ɪˈvækjueɪt/', meaning:'sơ tán, di tản', type:'verb', example:'People were evacuated before the hurricane hit.', viAnswers:['sơ tán', 'di tản']},
      {word:'drought', ipa:'/draʊt/', meaning:'hạn hán', type:'noun', example:'The drought damaged the crops.', viAnswers:['hạn hán']},
      {word:'barometer', ipa:'/bəˈrɑːmɪtər/', meaning:'áp kế, thước đo xu hướng', type:'noun', example:'A fall in the barometer indicates rain.', viAnswers:['áp kế', 'thước đo']},
      {word:'climate change', ipa:'/ˈklaɪmət tʃeɪndʒ/', meaning:'biến đổi khí hậu', type:'noun', example:'Governments must tackle climate change.', viAnswers:['biến đổi khí hậu']},
      {word:'toxic waste', ipa:'/ˈtɑːksɪk weɪst/', meaning:'chất thải độc hại', type:'noun', example:'The factory dumped toxic waste into the river.', viAnswers:['chất thải độc hại']},
      {word:'adverse', ipa:'/ædˈvɜːrs/', meaning:'bất lợi, có hại', type:'adjective', example:'The flight was canceled due to adverse weather.', viAnswers:['bất lợi', 'có hại']},
      {word:'catastrophe', ipa:'/kəˈtæstrəfi/', meaning:'tai ương, thảm họa thảm khốc', type:'noun', example:'The environmental catastrophe affected the town.', viAnswers:['thảm họa', 'tai ương']},
      {word:'greenhouse effect', ipa:'/ˈɡriːnhaʊs ɪˈfekt/', meaning:'hiệu ứng nhà kính', type:'noun', example:'The greenhouse effect causes global warming.', viAnswers:['hiệu ứng nhà kính']},
      {word:'environmentalist', ipa:'/ɪnˌvaɪrənˈmentəlɪst/', meaning:'nhà môi trường học', type:'noun', example:'Environmentalists protested the forest clearance.', viAnswers:['nhà môi trường']}
    ]
  },

  {
    day: 39,
    topic: "Tin tức / Truyền thông",
    topicEn: "News / Media",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Chiến thuật nghe Part 2 - Hỏi đáp",
      explanation: "TOEIC Listening Part 2: Nghe 1 câu hỏi + 3 đáp án, chọn câu trả lời phù hợp nhất.\n\nChiến thuật:\n1. TẬP TRUNG nghe TỪ ĐẦU TIÊN của câu hỏi (Who, What, When, Where, Why, How).\n   - Who → trả lời về NGƯỜI\n   - What → trả lời về SỰ VIỆC / VẬT\n   - When → trả lời về THỜI GIAN\n   - Where → trả lời về NƠI CHỐN\n   - Why → trả lời bằng Because...\n   - How → trả lời về CÁCH THỨC\n\n2. CẨN THẬN với câu hỏi Yes/No:\n   - Đáp án có thể không bắt đầu bằng Yes/No\n   - Ví dụ: 'Did the reporter finish?' → 'He is still working on it.'\n\n3. LOẠI TRỪ đáp án lặp lại từ trong câu hỏi (thường là bẫy).",
      structure: "Who/What/When/Where/Why/How + trợ động từ + S + V?",
      examples: ["Who wrote this article? - The new reporter did.", "When was the news published? - It was published yesterday.", "Where is the press conference? - It is at the hotel.", "Why was the interview canceled? - Because the editor was sick."],
      exceptions: [],
      notes: [],
      tips: "Nghe từ đầu tiên → xác định loại câu hỏi → loại đáp án sai. Cẩn thận đáp án gián tiếp!"
    },
    words: [
      {word:'broadcast', ipa:'/ˈbrɔːdkæst/', meaning:'phát sóng, truyền hình, buổi phát thanh', type:'verb / noun', example:'The interview will be broadcast live.', viAnswers:['phát sóng', 'truyền hình']},
      {word:'coverage', ipa:'/ˈkʌvərɪdʒ/', meaning:'tin tức đưa tin, phạm vi bảo hiểm, phủ sóng', type:'noun', example:'The media coverage of the election was extensive.', viAnswers:['đưa tin', 'phủ sóng', 'bảo hiểm']},
      {word:'correspondent', ipa:'/ˌkɔːrəˈspɑːndənt/', meaning:'phóng viên thường trú', type:'noun', example:'He is a war correspondent for the BBC.', viAnswers:['phóng viên', 'phóng viên thường trú']},
      {word:'press release', ipa:'/ˈpres rɪˈliːs/', meaning:'thông cáo báo chí', type:'noun', example:'The firm issued a press release about the merger.', viAnswers:['thông cáo báo chí']},
      {word:'editor', ipa:'/ˈedɪtər/', meaning:'biên tập viên', type:'noun', example:'He works as a senior editor.', viAnswers:['biên tập viên']},
      {word:'journalism', ipa:'/ˈdʒɜːrnəlɪzəm/', meaning:'ngành báo chí', type:'noun', example:'She studied journalism at college.', viAnswers:['báo chí', 'ngành báo chí']},
      {word:'publication', ipa:'/ˌpʌblɪˈkeɪʃən/', meaning:'sự công bố, sự xuất bản, ấn phẩm', type:'noun', example:'The publication date is next Tuesday.', viAnswers:['xuất bản', 'ấn phẩm', 'sự xuất bản']},
      {word:'spokesperson', ipa:'/ˈspoʊksˌpɜːrsən/', meaning:'người phát ngôn', type:'noun', example:'A spokesperson denied the rumors.', viAnswers:['người phát ngôn']},
      {word:'circulation', ipa:'/ˈsɜːrkjəˈleɪʃən/', meaning:'số lượng bản in lưu hành, tuần hoàn', type:'noun', example:'The newspaper has a daily circulation of one million.', viAnswers:['số bản phát hành', 'lưu hành', 'tuần hoàn']},
      {word:'censor', ipa:'/ˈsensər/', meaning:'kiểm duyệt, người kiểm duyệt', type:'verb / noun', example:'The government censored the report.', viAnswers:['kiểm duyệt']},
      {word:'expose', ipa:'/ɪkˈspoʊz/', meaning:'phơi bày, vạch trần', type:'verb', example:'The journalist exposed the corruption.', viAnswers:['phơi bày', 'vạch trần']},
      {word:'bias', ipa:'/ˈbaɪəs/', meaning:'thành kiến, thiên vị', type:'noun / verb', example:'The article showed a clear political bias.', viAnswers:['thành kiến', 'thiên vị']},
      {word:'sensational', ipa:'/senˈseɪʃənəl/', meaning:'giật gân, gây chấn động', type:'adjective', example:'Sensational headlines sell newspapers.', viAnswers:['giật gân', 'chấn động']},
      {word:'advertising agency', ipa:'/ˈædvərtaɪzɪŋ ˈeɪdʒənsi/', meaning:'đại lý quảng cáo', type:'noun', example:'We hired an advertising agency.', viAnswers:['đại lý quảng cáo']},
      {word:'public relations', ipa:'/ˈpʌblɪk rɪˈleɪʃənz/', meaning:'quan hệ công chúng (PR)', type:'noun', example:'She works in public relations.', viAnswers:['quan hệ công chúng', 'PR']},
      {word:'editorial', ipa:'/ˌedɪˈtɔːriəl/', meaning:'bài xã luận, thuộc biên tập', type:'noun / adjective', example:'The editorial criticized the new policy.', viAnswers:['xã luận', 'bài xã luận']},
      {word:'exclusive', ipa:'/ɪkˈskluːsɪv/', meaning:'độc quyền, riêng biệt', type:'adjective / noun', example:'The magazine published an exclusive interview.', viAnswers:['độc quyền', 'riêng biệt']},
      {word:'acclaim', ipa:'/əˈkleɪm/', meaning:'sự hoan nghênh, ca ngợi', type:'noun / verb', example:'The novel won critical acclaim.', viAnswers:['hoan nghênh', 'ca ngợi']},
      {word:'publicity', ipa:'/pʌbˈlɪsəti/', meaning:'sự quảng bá, sự công khai', type:'noun', example:'The event generated a lot of publicity.', viAnswers:['quảng bá', 'sự công khai']},
      {word:'hype', ipa:'/haɪp/', meaning:'sự thổi phồng, quảng cáo quá mức', type:'noun / verb', example:'Don\'t believe the media hype.', viAnswers:['thổi phồng', 'quảng cáo quá mức']},
      {word:'columnist', ipa:'/ˈkɑːləmnɪst/', meaning:'người viết mục báo thường kỳ', type:'noun', example:'She is a political columnist.', viAnswers:['người viết mục báo']},
      {word:'medium', ipa:'/ˈmiːdiəm/', meaning:'phương tiện truyền thông, trung bình', type:'noun / adjective', example:'Television is an effective advertising medium.', viAnswers:['phương tiện', 'trung bình']}
    ]
  },

  {
    day: 40,
    topic: "Xây dựng",
    topicEn: "Construction",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Nghe bắt từ khóa (Listening for Keywords)",
      explanation: "Kỹ thuật nghe bắt từ khóa giúp bạn hiểu ý chính mà không cần hiểu mọi từ.\n\nCách thực hiện:\n1. XÁC ĐỊNH từ khóa: danh từ, động từ, tính từ quan trọng\n   - Bỏ qua: a, the, is, are, of, in...\n   - Tập trung: build, construct, site, permit, inspect...\n\n2. LIÊN KẾT từ khóa thành ý nghĩa:\n   - Nghe: 'construction... delayed... permit... next month'\n   - Hiểu: Việc xây dựng bị hoãn vì chưa có giấy phép, sẽ tiếp tục tháng sau.\n\n3. GHI NHỚ các từ khóa về:\n   - THỜI GIAN: today, tomorrow, next week, by Friday\n   - HÀNH ĐỘNG: build, repair, inspect, complete\n   - VẤN ĐỀ: delay, problem, issue, cancel",
      structure: "Nghe từ khóa: DANH TỪ + ĐỘNG TỪ + THỜI GIAN = hiểu ý chính",
      examples: ["The construction site will be inspected tomorrow.", "The building was renovated last year.", "The contractor said the project is delayed.", "A new permit is required before we can start."],
      exceptions: [],
      notes: [],
      tips: "Không cần hiểu 100% → bắt từ khóa quan trọng → ghép lại thành ý chính. Luyện tập mỗi ngày!"
    },
    words: [
      {word:'blueprint', ipa:'/ˈbluːprɪnt/', meaning:'bản thiết kế xanh, bản kế hoạch chi tiết', type:'noun', example:'The architect presented the blueprints.', viAnswers:['bản thiết kế', 'bản chi tiết', 'sơ đồ']},
      {word:'contractor', ipa:'/ˈkɑːntræktər/', meaning:'nhà thầu', type:'noun', example:'The general contractor managed the project.', viAnswers:['nhà thầu']},
      {word:'excavate', ipa:'/ˈekskəveɪt/', meaning:'đào, khai quật', type:'verb', example:'They began to excavate the foundation.', viAnswers:['đào', 'khai quật']},
      {word:'scaffolding', ipa:'/ˈskæfəldɪŋ/', meaning:'giàn giáo', type:'noun', example:'Scaffolding was erected around the building.', viAnswers:['giàn giáo']},
      {word:'renovation', ipa:'/ˌrenəˈveɪʃən/', meaning:'sự cải tạo, nâng cấp', type:'noun', example:'The theater is closed for renovation.', viAnswers:['cải tạo', 'trùng tu', 'sự cải tạo']},
      {word:'demolish', ipa:'/dɪˈmɑːlɪʃ/', meaning:'phá hủy, phá dỡ (tòa nhà)', type:'verb', example:'The old factory was demolished.', viAnswers:['phá dỡ', 'phá hủy']},
      {word:'infrastructure', ipa:'/ˈɪnfrəˌstrʌktʃər/', meaning:'cơ sở hạ tầng', type:'noun', example:'The city needs to upgrade its infrastructure.', viAnswers:['cơ sở hạ tầng']},
      {word:'superintendent', ipa:'/ˌsuːpərɪnˈtendənt/', meaning:'người giám sát, người quản lý công trường', type:'noun', example:'Talk to the construction superintendent.', viAnswers:['người giám sát', 'giám thị']},
      {word:'hazard', ipa:'/ˈhæzərd/', meaning:'mối nguy hiểm, rủi ro', type:'noun / verb', example:'Piles of debris are a safety hazard.', viAnswers:['nguy hiểm', 'mối nguy hiểm', 'rủi ro']},
      {word:'zoning', ipa:'/ˈzoʊnɪŋ/', meaning:'sự phân khu, quy hoạch đất', type:'noun', example:'The project violates zoning regulations.', viAnswers:['quy hoạch đất', 'quy hoạch']},
      {word:'builder', ipa:'/ˈbɪldər/', meaning:'nhà thầu xây dựng, thợ xây', type:'noun', example:'The builder offers a ten-year structural warranty.', viAnswers:['nhà thầu', 'người xây dựng']},
      {word:'concrete', ipa:'/ˈkɑːnkriːt/', meaning:'bê tông, cụ thể', type:'noun / adjective', example:'The pillars are made of reinforced concrete.', viAnswers:['bê tông', 'cụ thể']},
      {word:'architect', ipa:'/ˈɑːrkɪtekt/', meaning:'kiến trúc sư', type:'noun', example:'The architect designed the new museum.', viAnswers:['kiến trúc sư']},
      {word:'specifications', ipa:'/ˌspesəfɪˈkeɪʃənz/', meaning:'thông số kỹ thuật, bản thiết kế chi tiết', type:'noun', example:'The builder must follow specifications.', viAnswers:['thông số kỹ thuật']},
      {word:'masonry', ipa:'/ˈmeɪsənri/', meaning:'công việc xây đá/gạch, tường gạch', type:'noun', example:'The masonry work was done by hand.', viAnswers:['xây gạch', 'xây đá']},
      {word:'insulation', ipa:'/ˌɪnsəˈleɪʃən/', meaning:'sự cách nhiệt, vật liệu cách nhiệt/điện', type:'noun', example:'Good insulation reduces heating bills.', viAnswers:['cách nhiệt', 'sự cách nhiệt']},
      {word:'reinforce', ipa:'/ˌriːɪnˈfɔːrs/', meaning:'củng cố, gia cố', type:'verb', example:'Steel beams reinforce the structure.', viAnswers:['gia cố', 'củng cố']},
      {word:'permit', ipa:'/pərˈmɪt/', meaning:'giấy phép, cho phép', type:'noun / verb', example:'We applied for a building permit.', viAnswers:['giấy phép', 'cho phép']},
      {word:'inspector', ipa:'/ɪnˈspektər/', meaning:'thanh tra viên, người kiểm tra', type:'noun', example:'The building inspector approved the foundation.', viAnswers:['thanh tra viên', 'người kiểm tra']},
      {word:'compliance', ipa:'/kəmˈplaɪəns/', meaning:'sự tuân thủ đúng quy chuẩn', type:'noun', example:'The building is in compliance with safety codes.', viAnswers:['tuân thủ', 'sự tuân thủ']},
      {word:'structure', ipa:'/ˈstrʌktʃər/', meaning:'cấu trúc, công trình kiến trúc', type:'noun', example:'The wooden structure was damaged by fire.', viAnswers:['cấu trúc', 'công trình']},
      {word:'retrofit', ipa:'/ˈretrəfɪt/', meaning:'cải tạo lại, lắp đặt thêm thiết bị mới', type:'verb / noun', example:'The factory was retrofitted with green tech.', viAnswers:['cải tạo', 'lắp đặt thêm']}
    ]
  }
];
