const DAYS_DATA_PART3 = [
  {
    day: 41,
    topic: "Điện tử",
    topicEn: "Electronics",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Nghe mô tả hành động (Listening - Mô tả hành động)",
      explanation: "Trong phần nghe TOEIC Part 1, bạn sẽ nghe mô tả về hành động đang diễn ra trong hình ảnh. Hãy chú ý đến: 1) Ai đang làm gì (chủ ngữ + động từ), 2) Đồ vật ở đâu, đang được sử dụng thế nào. Thường dùng thì hiện tại tiếp diễn (is/are + V-ing) để mô tả hành động đang xảy ra.",
      structure: "Subject + is/are + V-ing + Object",
      examples: [
        "The man is plugging in the charger.",
        "She is adjusting the settings on the monitor.",
        "They are recording a video with a camera.",
        "The technician is checking the circuit board."
      ],
      tips: "Khi nghe mô tả hành động, tập trung vào ĐỘNG TỪ chính. Phân biệt các hành động tương tự nhau: plugging in ≠ unplugging, turning on ≠ turning off."
    },
    words: [
      {word:'battery', meaning:'pin, ắc quy', type:'noun', example:'The battery is low.', viAnswers:['pin','ắc quy','pin ắc quy']},
      {word:'charger', meaning:'bộ sạc', type:'noun', example:'I forgot my charger at home.', viAnswers:['bộ sạc','sạc','cục sạc']},
      {word:'cable', meaning:'dây cáp', type:'noun', example:'Please connect the cable to the computer.', viAnswers:['dây cáp','cáp','dây']},
      {word:'plug', meaning:'cắm (phích cắm)', type:'noun / verb', example:'Plug the lamp into the wall.', viAnswers:['cắm','phích cắm','ổ cắm']},
      {word:'switch', meaning:'công tắc, chuyển đổi', type:'noun / verb', example:'Turn the switch on.', viAnswers:['công tắc','chuyển đổi','nút bật']},
      {word:'wire', meaning:'dây điện', type:'noun', example:'The wire is broken.', viAnswers:['dây điện','dây','sợi dây']},
      {word:'circuit', meaning:'mạch điện', type:'noun', example:'The circuit was damaged.', viAnswers:['mạch điện','mạch']},
      {word:'signal', meaning:'tín hiệu', type:'noun', example:'The signal is weak here.', viAnswers:['tín hiệu']},
      {word:'antenna', meaning:'ăng-ten', type:'noun', example:'The antenna receives radio signals.', viAnswers:['ăng-ten','ăng ten','an ten']},
      {word:'remote', meaning:'điều khiển từ xa', type:'noun / adjective', example:'Where is the remote control?', viAnswers:['điều khiển từ xa','remote','điều khiển']},
      {word:'sensor', meaning:'cảm biến', type:'noun', example:'The sensor detects movement.', viAnswers:['cảm biến','bộ cảm biến']},
      {word:'monitor', meaning:'màn hình', type:'noun', example:'The monitor shows a clear image.', viAnswers:['màn hình','màn hình máy tính']},
      {word:'display', meaning:'hiển thị, màn hình hiển thị', type:'noun / verb', example:'The display is very bright.', viAnswers:['hiển thị','màn hình hiển thị','trưng bày']},
      {word:'pixel', meaning:'điểm ảnh', type:'noun', example:'This screen has many pixels.', viAnswers:['điểm ảnh','pixel']},
      {word:'resolution', meaning:'độ phân giải', type:'noun', example:'The resolution of this camera is high.', viAnswers:['độ phân giải']},
      {word:'speaker', meaning:'loa', type:'noun', example:'The speaker is very loud.', viAnswers:['loa','người nói']},
      {word:'microphone', meaning:'micrô', type:'noun', example:'Speak into the microphone.', viAnswers:['micrô','mi-crô','micro','mic']},
      {word:'camera', meaning:'máy ảnh, máy quay', type:'noun', example:'She bought a new camera.', viAnswers:['máy ảnh','máy quay','camera']},
      {word:'lens', meaning:'ống kính, thấu kính', type:'noun', example:'The lens is dirty.', viAnswers:['ống kính','thấu kính']},
      {word:'flash', meaning:'đèn flash', type:'noun', example:'Use the flash in dark rooms.', viAnswers:['đèn flash','flash','đèn chớp']},
      {word:'record', meaning:'ghi, thu', type:'verb', example:'Please record the meeting.', viAnswers:['ghi','thu','ghi lại','thu âm']},
      {word:'playback', meaning:'phát lại', type:'noun', example:'Check the playback of the video.', viAnswers:['phát lại','phát']},
      {word:'adjust', meaning:'điều chỉnh', type:'verb', example:'Adjust the volume, please.', viAnswers:['điều chỉnh','chỉnh']},
      {word:'setting', meaning:'cài đặt', type:'noun', example:'Change the setting to save battery.', viAnswers:['cài đặt','thiết lập']},
      {word:'compatible', meaning:'tương thích', type:'adjective', example:'This cable is compatible with your phone.', viAnswers:['tương thích']}
    ]
  },
  {
    day: 42,
    topic: "Hợp đồng / Pháp lý",
    topicEn: "Contracts / Legal",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Nghe hội thoại (Listening - Hội thoại)",
      explanation: "Trong TOEIC Part 3, bạn sẽ nghe đoạn hội thoại giữa 2-3 người. Mẹo: 1) Đọc câu hỏi TRƯỚC khi nghe, 2) Chú ý ai nói gì - phân biệt người nói, 3) Nghe từ khóa để trả lời câu hỏi về: mục đích cuộc hội thoại, chi tiết cụ thể, hành động tiếp theo.",
      structure: "Nghe → Xác định: Who? What? Where? Why? What next?",
      examples: [
        "A: Have you signed the contract yet? B: Not yet. I need to review it first.",
        "A: When does the agreement expire? B: It expires next month.",
        "A: We should negotiate better terms. B: I agree. Let's set up a meeting."
      ],
      tips: "Trước khi nghe, đọc lướt câu hỏi và các đáp án. Gạch chân từ khóa trong câu hỏi. Khi nghe, tập trung vào từ khóa đó."
    },
    words: [
      {word:'contract', meaning:'hợp đồng', type:'noun', example:'Please sign the contract.', viAnswers:['hợp đồng']},
      {word:'clause', meaning:'điều khoản', type:'noun', example:'Read every clause carefully.', viAnswers:['điều khoản']},
      {word:'term', meaning:'điều kiện, kỳ hạn', type:'noun', example:'The term of the contract is two years.', viAnswers:['điều kiện','kỳ hạn','thời hạn']},
      {word:'condition', meaning:'điều kiện', type:'noun', example:'You must accept the conditions.', viAnswers:['điều kiện']},
      {word:'negotiate', meaning:'đàm phán, thương lượng', type:'verb', example:'They will negotiate the price.', viAnswers:['đàm phán','thương lượng']},
      {word:'agree', meaning:'đồng ý', type:'verb', example:'I agree with your idea.', viAnswers:['đồng ý']},
      {word:'sign', meaning:'ký', type:'verb', example:'Please sign your name here.', viAnswers:['ký','ký tên']},
      {word:'renew', meaning:'gia hạn, đổi mới', type:'verb', example:'We need to renew the contract.', viAnswers:['gia hạn','đổi mới','làm mới']},
      {word:'expire', meaning:'hết hạn', type:'verb', example:'The agreement will expire soon.', viAnswers:['hết hạn']},
      {word:'cancel', meaning:'hủy bỏ', type:'verb', example:'She wants to cancel the order.', viAnswers:['hủy bỏ','hủy']},
      {word:'breach', meaning:'vi phạm', type:'noun / verb', example:'He was accused of a breach of contract.', viAnswers:['vi phạm']},
      {word:'liability', meaning:'trách nhiệm pháp lý', type:'noun', example:'The company has no liability for this.', viAnswers:['trách nhiệm pháp lý','trách nhiệm']},
      {word:'obligation', meaning:'nghĩa vụ', type:'noun', example:'You have an obligation to pay on time.', viAnswers:['nghĩa vụ','bổn phận']},
      {word:'guarantee', meaning:'bảo đảm', type:'noun / verb', example:'The product has a one-year guarantee.', viAnswers:['bảo đảm','bảo hành','đảm bảo']},
      {word:'warranty', meaning:'bảo hành', type:'noun', example:'The warranty covers repairs.', viAnswers:['bảo hành']},
      {word:'confidential', meaning:'bảo mật, bí mật', type:'adjective', example:'This document is confidential.', viAnswers:['bảo mật','bí mật']},
      {word:'intellectual', meaning:'trí tuệ, thuộc trí tuệ', type:'adjective', example:'Protect your intellectual property.', viAnswers:['trí tuệ','thuộc trí tuệ']},
      {word:'property', meaning:'tài sản', type:'noun', example:'This is company property.', viAnswers:['tài sản','bất động sản']},
      {word:'copyright', meaning:'bản quyền', type:'noun', example:'The copyright belongs to the author.', viAnswers:['bản quyền']},
      {word:'patent', meaning:'bằng sáng chế', type:'noun', example:'They filed a patent for the invention.', viAnswers:['bằng sáng chế']},
      {word:'trademark', meaning:'nhãn hiệu', type:'noun', example:'The trademark is registered.', viAnswers:['nhãn hiệu','thương hiệu']},
      {word:'dispute', meaning:'tranh chấp', type:'noun / verb', example:'They had a dispute about the payment.', viAnswers:['tranh chấp']},
      {word:'arbitrate', meaning:'phân xử, trọng tài', type:'verb', example:'A judge will arbitrate the case.', viAnswers:['phân xử','trọng tài','phân xử trọng tài']},
      {word:'settle', meaning:'giải quyết, dàn xếp', type:'verb', example:'They settled the dispute quickly.', viAnswers:['giải quyết','dàn xếp']},
      {word:'comply', meaning:'tuân thủ', type:'verb', example:'You must comply with the rules.', viAnswers:['tuân thủ','tuân theo']}
    ]
  },
  {
    day: 43,
    topic: "Sự kiện",
    topicEn: "Events",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Nghe thông báo (Listening - Thông báo / Talks)",
      explanation: "Trong TOEIC Part 4, bạn sẽ nghe một người nói (thông báo, quảng cáo, tin nhắn thoại, bài phát biểu). Mẹo: 1) Xác định LOẠI thông báo (announcement, advertisement, voicemail...), 2) Nghe mục đích chính, 3) Chú ý các chi tiết: thời gian, địa điểm, yêu cầu hành động.",
      structure: "Nghe → Xác định: Loại thông báo? Mục đích? Chi tiết quan trọng?",
      examples: [
        "Attention all guests, the ceremony will begin at 3 PM in the main hall.",
        "Please note that the exhibition has been moved to the second floor.",
        "We are pleased to announce the opening of our new conference center."
      ],
      tips: "Thông báo thường bắt đầu bằng: Attention please, We are pleased to announce, Please note that... Hãy nghe kỹ phần đầu để biết chủ đề chính."
    },
    words: [
      {word:'event', meaning:'sự kiện', type:'noun', example:'The event starts at 7 PM.', viAnswers:['sự kiện']},
      {word:'ceremony', meaning:'buổi lễ', type:'noun', example:'The ceremony was beautiful.', viAnswers:['buổi lễ','lễ','nghi lễ']},
      {word:'celebration', meaning:'lễ kỷ niệm, sự ăn mừng', type:'noun', example:'It was a big celebration.', viAnswers:['lễ kỷ niệm','sự ăn mừng','ăn mừng']},
      {word:'reception', meaning:'tiệc chiêu đãi, lễ tân', type:'noun', example:'The reception is at the hotel.', viAnswers:['tiệc chiêu đãi','lễ tân','tiệc tiếp tân']},
      {word:'banquet', meaning:'tiệc lớn', type:'noun', example:'The company held a banquet.', viAnswers:['tiệc lớn','yến tiệc','tiệc']},
      {word:'conference', meaning:'hội nghị', type:'noun', example:'The conference is next week.', viAnswers:['hội nghị']},
      {word:'exhibition', meaning:'triển lãm', type:'noun', example:'The art exhibition is free.', viAnswers:['triển lãm','cuộc triển lãm']},
      {word:'fair', meaning:'hội chợ', type:'noun', example:'We visited the job fair.', viAnswers:['hội chợ']},
      {word:'launch', meaning:'ra mắt, khởi động', type:'noun / verb', example:'The product launch was successful.', viAnswers:['ra mắt','khởi động','phát động']},
      {word:'opening', meaning:'khai mạc, lễ khai trương', type:'noun', example:'The grand opening is tomorrow.', viAnswers:['khai mạc','lễ khai trương','khai trương']},
      {word:'anniversary', meaning:'kỷ niệm', type:'noun', example:'It is their 10th anniversary.', viAnswers:['kỷ niệm','ngày kỷ niệm']},
      {word:'award', meaning:'giải thưởng', type:'noun', example:'She won the best employee award.', viAnswers:['giải thưởng']},
      {word:'honor', meaning:'vinh danh, danh dự', type:'noun / verb', example:'We honor our best workers.', viAnswers:['vinh danh','danh dự','tôn vinh']},
      {word:'invite', meaning:'mời', type:'verb', example:'We invite you to the party.', viAnswers:['mời']},
      {word:'host', meaning:'chủ nhà, tổ chức', type:'noun / verb', example:'She will host the event.', viAnswers:['chủ nhà','tổ chức','người dẫn chương trình']},
      {word:'organize', meaning:'tổ chức, sắp xếp', type:'verb', example:'They organize events every year.', viAnswers:['tổ chức','sắp xếp']},
      {word:'coordinate', meaning:'phối hợp', type:'verb', example:'She will coordinate the event.', viAnswers:['phối hợp','điều phối']},
      {word:'decorate', meaning:'trang trí', type:'verb', example:'They decorate the room with flowers.', viAnswers:['trang trí']},
      {word:'cater', meaning:'cung cấp thức ăn, phục vụ ăn uống', type:'verb', example:'Who will cater the wedding?', viAnswers:['cung cấp thức ăn','phục vụ ăn uống','phục vụ tiệc']},
      {word:'entertain', meaning:'giải trí, tiếp đãi', type:'verb', example:'The band will entertain the guests.', viAnswers:['giải trí','tiếp đãi']},
      {word:'speech', meaning:'bài phát biểu', type:'noun', example:'He gave a great speech.', viAnswers:['bài phát biểu','bài diễn văn']},
      {word:'toast', meaning:'lời chúc mừng, nâng cốc', type:'noun / verb', example:'Let us make a toast!', viAnswers:['lời chúc mừng','nâng cốc','chúc mừng']},
      {word:'congratulate', meaning:'chúc mừng', type:'verb', example:'I congratulate you on your success.', viAnswers:['chúc mừng']},
      {word:'participate', meaning:'tham gia', type:'verb', example:'Everyone can participate.', viAnswers:['tham gia']},
      {word:'venue', meaning:'địa điểm tổ chức', type:'noun', example:'The venue is easy to find.', viAnswers:['địa điểm tổ chức','địa điểm']}
    ]
  },
  {
    day: 44,
    topic: "Nông nghiệp / Thiên nhiên",
    topicEn: "Agriculture / Nature",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Tổng ôn nghe (Listening - Tổng hợp)",
      explanation: "Tổng ôn tất cả kỹ năng nghe TOEIC: Part 1 (mô tả hình ảnh), Part 2 (hỏi-đáp), Part 3 (hội thoại), Part 4 (bài nói). Quy trình làm bài nghe hiệu quả: 1) Đọc trước câu hỏi và đáp án, 2) Gạch chân từ khóa, 3) Nghe và chọn đáp án ngay, 4) Không dừng lại ở câu khó - đi tiếp.",
      structure: "Part 1: Hình ảnh → Part 2: Hỏi-đáp → Part 3: Hội thoại → Part 4: Bài nói",
      examples: [
        "Part 1: The farmer is planting seeds in the field.",
        "Part 2: When is the harvest season? - It starts in September.",
        "Part 3: A: How is the crop this year? B: It is better than last year.",
        "Part 4: Due to the drought, water usage will be limited."
      ],
      tips: "Luyện nghe mỗi ngày 15-30 phút. Nghe đi nghe lại nhiều lần. Lần 1: nghe hiểu ý chính. Lần 2: nghe chi tiết. Lần 3: nghe và đọc transcript."
    },
    words: [
      {word:'farm', meaning:'nông trại, trang trại', type:'noun', example:'He works on a farm.', viAnswers:['nông trại','trang trại']},
      {word:'crop', meaning:'vụ mùa, cây trồng', type:'noun', example:'Rice is an important crop.', viAnswers:['vụ mùa','cây trồng','mùa vụ']},
      {word:'harvest', meaning:'thu hoạch', type:'noun / verb', example:'The harvest is in October.', viAnswers:['thu hoạch','mùa thu hoạch','gặt hái']},
      {word:'plant', meaning:'trồng, cây', type:'verb / noun', example:'They plant trees every spring.', viAnswers:['trồng','cây','thực vật']},
      {word:'seed', meaning:'hạt giống', type:'noun', example:'Put the seeds in the soil.', viAnswers:['hạt giống','hạt']},
      {word:'soil', meaning:'đất', type:'noun', example:'The soil is very rich.', viAnswers:['đất','thổ nhưỡng']},
      {word:'fertilizer', meaning:'phân bón', type:'noun', example:'Use fertilizer to help plants grow.', viAnswers:['phân bón']},
      {word:'irrigate', meaning:'tưới tiêu', type:'verb', example:'They irrigate the fields every day.', viAnswers:['tưới tiêu','tưới']},
      {word:'organic', meaning:'hữu cơ', type:'adjective', example:'I prefer organic vegetables.', viAnswers:['hữu cơ']},
      {word:'pesticide', meaning:'thuốc trừ sâu', type:'noun', example:'Do not use too much pesticide.', viAnswers:['thuốc trừ sâu']},
      {word:'livestock', meaning:'gia súc', type:'noun', example:'The farmer raises livestock.', viAnswers:['gia súc','vật nuôi']},
      {word:'poultry', meaning:'gia cầm', type:'noun', example:'Poultry includes chickens and ducks.', viAnswers:['gia cầm']},
      {word:'dairy', meaning:'sản phẩm sữa', type:'noun / adjective', example:'She buys dairy products.', viAnswers:['sản phẩm sữa','sữa','bơ sữa']},
      {word:'grain', meaning:'ngũ cốc, hạt', type:'noun', example:'Wheat is a common grain.', viAnswers:['ngũ cốc','hạt']},
      {word:'vegetable', meaning:'rau', type:'noun', example:'Eat more vegetables.', viAnswers:['rau','rau củ']},
      {word:'fruit', meaning:'trái cây', type:'noun', example:'I eat fruit every morning.', viAnswers:['trái cây','hoa quả']},
      {word:'orchard', meaning:'vườn cây ăn quả', type:'noun', example:'The orchard has many apple trees.', viAnswers:['vườn cây ăn quả','vườn cây']},
      {word:'greenhouse', meaning:'nhà kính', type:'noun', example:'Plants grow fast in a greenhouse.', viAnswers:['nhà kính']},
      {word:'yield', meaning:'sản lượng, cho ra', type:'noun / verb', example:'The yield was high this year.', viAnswers:['sản lượng','năng suất','cho ra']},
      {word:'cultivate', meaning:'canh tác, trồng trọt', type:'verb', example:'They cultivate rice in this area.', viAnswers:['canh tác','trồng trọt']},
      {word:'sustain', meaning:'duy trì', type:'verb', example:'We must sustain our natural resources.', viAnswers:['duy trì','bền vững']},
      {word:'drought', meaning:'hạn hán', type:'noun', example:'The drought destroyed many crops.', viAnswers:['hạn hán']},
      {word:'fertile', meaning:'màu mỡ, phì nhiêu', type:'adjective', example:'The land here is very fertile.', viAnswers:['màu mỡ','phì nhiêu']},
      {word:'seasonal', meaning:'theo mùa', type:'adjective', example:'This is a seasonal fruit.', viAnswers:['theo mùa','mùa vụ']},
      {word:'export', meaning:'xuất khẩu', type:'noun / verb', example:'Vietnam exports a lot of rice.', viAnswers:['xuất khẩu']}
    ]
  },
  {
    day: 45,
    topic: "Chính sách / Quy trình",
    topicEn: "Policies / Procedures",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Chọn từ loại (Word Forms)",
      explanation: "Trong TOEIC Part 5, bạn cần chọn từ loại đúng để điền vào chỗ trống. Cách nhận biết từ loại: 1) DANH TỪ (noun): đứng sau a/an/the, sau tính từ - đuôi: -tion, -ment, -ness, -ity, -ance. 2) ĐỘNG TỪ (verb): đứng sau chủ ngữ - đuôi: -ize, -ify, -ate. 3) TÍNH TỪ (adjective): đứng trước danh từ, sau be - đuôi: -ful, -less, -ive, -able, -ous. 4) TRẠNG TỪ (adverb): bổ nghĩa cho động từ, tính từ - đuôi: -ly.",
      structure: "Nhìn vị trí chỗ trống → Xác định cần từ loại gì → Chọn đáp án đúng từ loại",
      examples: [
        "The company will ___ the new policy. (implement - verb)",
        "The ___ of the new rule is important. (implementation - noun)",
        "We need ___ guidelines. (regulatory - adjective)",
        "The policy was ___ enforced. (strictly - adverb)"
      ],
      tips: "Học thuộc các đuôi từ phổ biến: -tion (noun), -ly (adverb), -ive (adjective), -ize (verb). Khi làm bài, nhìn VỊ TRÍ chỗ trống trước, rồi mới nhìn đáp án."
    },
    words: [
      {word:'policy', meaning:'chính sách', type:'noun', example:'The company has a new policy.', viAnswers:['chính sách']},
      {word:'procedure', meaning:'quy trình, thủ tục', type:'noun', example:'Follow the correct procedure.', viAnswers:['quy trình','thủ tục']},
      {word:'guideline', meaning:'hướng dẫn', type:'noun', example:'Read the guidelines carefully.', viAnswers:['hướng dẫn','nguyên tắc chỉ đạo']},
      {word:'comply', meaning:'tuân thủ', type:'verb', example:'All staff must comply with the rules.', viAnswers:['tuân thủ','tuân theo']},
      {word:'enforce', meaning:'thực thi, thi hành', type:'verb', example:'The police enforce the law.', viAnswers:['thực thi','thi hành']},
      {word:'implement', meaning:'thực hiện, triển khai', type:'verb', example:'We will implement the plan next month.', viAnswers:['thực hiện','triển khai']},
      {word:'revise', meaning:'sửa đổi, xem lại', type:'verb', example:'They will revise the document.', viAnswers:['sửa đổi','xem lại','chỉnh sửa']},
      {word:'approve', meaning:'phê duyệt, chấp thuận', type:'verb', example:'The manager approved the request.', viAnswers:['phê duyệt','chấp thuận']},
      {word:'authorize', meaning:'ủy quyền, cho phép', type:'verb', example:'Only the director can authorize this.', viAnswers:['ủy quyền','cho phép']},
      {word:'restrict', meaning:'hạn chế', type:'verb', example:'Access is restricted to employees.', viAnswers:['hạn chế','giới hạn']},
      {word:'mandate', meaning:'bắt buộc, ủy thác', type:'verb / noun', example:'The government mandates safety checks.', viAnswers:['bắt buộc','ủy thác','chỉ thị']},
      {word:'regulate', meaning:'điều tiết, quản lý', type:'verb', example:'The agency regulates food safety.', viAnswers:['điều tiết','quản lý']},
      {word:'standard', meaning:'tiêu chuẩn', type:'noun', example:'We follow international standards.', viAnswers:['tiêu chuẩn']},
      {word:'requirement', meaning:'yêu cầu', type:'noun', example:'What are the requirements for this job?', viAnswers:['yêu cầu','điều kiện']},
      {word:'exception', meaning:'ngoại lệ', type:'noun', example:'There is no exception to this rule.', viAnswers:['ngoại lệ']},
      {word:'penalty', meaning:'hình phạt', type:'noun', example:'The penalty for being late is a fine.', viAnswers:['hình phạt','phạt']},
      {word:'violation', meaning:'vi phạm', type:'noun', example:'This is a serious violation.', viAnswers:['vi phạm','sự vi phạm']},
      {word:'monitor', meaning:'giám sát, theo dõi', type:'verb', example:'We monitor the system every day.', viAnswers:['giám sát','theo dõi']},
      {word:'assess', meaning:'đánh giá', type:'verb', example:'We need to assess the risk.', viAnswers:['đánh giá']},
      {word:'evaluate', meaning:'đánh giá, định giá', type:'verb', example:'The teacher will evaluate your work.', viAnswers:['đánh giá','định giá']},
      {word:'criteria', meaning:'tiêu chí', type:'noun', example:'What are the criteria for selection?', viAnswers:['tiêu chí']},
      {word:'benchmark', meaning:'tiêu chuẩn đối sánh', type:'noun', example:'This is the benchmark for quality.', viAnswers:['tiêu chuẩn đối sánh','chuẩn mực','điểm chuẩn']},
      {word:'framework', meaning:'khung, khuôn khổ', type:'noun', example:'The framework of the project is clear.', viAnswers:['khung','khuôn khổ','bộ khung']},
      {word:'protocol', meaning:'quy tắc, giao thức', type:'noun', example:'Follow the safety protocol.', viAnswers:['quy tắc','giao thức','nghi thức']},
      {word:'oversight', meaning:'sự giám sát', type:'noun', example:'The committee provides oversight.', viAnswers:['sự giám sát','giám sát','sơ suất']}
    ]
  },
  {
    day: 46,
    topic: "Đào tạo",
    topicEn: "Training",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Thì động từ (Verb Tenses)",
      explanation: "Trong TOEIC Part 5, bạn cần chọn thì động từ đúng. Các dấu hiệu nhận biết: 1) Hiện tại đơn: always, usually, every day, often. 2) Quá khứ đơn: yesterday, last week, ago, in 2020. 3) Hiện tại hoàn thành: since, for, already, yet, recently. 4) Tương lai: tomorrow, next week, will, be going to. 5) Hiện tại tiếp diễn: now, currently, at the moment.",
      structure: "Tìm dấu hiệu thời gian → Chọn thì phù hợp",
      examples: [
        "The training program ___ last month. (started - quá khứ đơn, vì 'last month')",
        "She ___ three courses since January. (has completed - hiện tại hoàn thành, vì 'since')",
        "The workshop ___ every Friday. (takes place - hiện tại đơn, vì 'every Friday')",
        "They ___ a new program next year. (will launch - tương lai, vì 'next year')"
      ],
      tips: "Gạch chân trạng từ chỉ thời gian trong câu trước. Đó là chìa khóa để chọn thì đúng. Nếu không có trạng từ, nhìn ngữ cảnh câu."
    },
    words: [
      {word:'training', meaning:'đào tạo, huấn luyện', type:'noun', example:'The training starts on Monday.', viAnswers:['đào tạo','huấn luyện']},
      {word:'workshop', meaning:'hội thảo thực hành', type:'noun', example:'I attended a writing workshop.', viAnswers:['hội thảo thực hành','hội thảo','xưởng']},
      {word:'seminar', meaning:'hội thảo chuyên đề', type:'noun', example:'The seminar is about marketing.', viAnswers:['hội thảo chuyên đề','hội thảo']},
      {word:'program', meaning:'chương trình', type:'noun', example:'This is a new training program.', viAnswers:['chương trình']},
      {word:'curriculum', meaning:'chương trình giảng dạy', type:'noun', example:'The curriculum has been updated.', viAnswers:['chương trình giảng dạy','giáo trình']},
      {word:'instructor', meaning:'giảng viên, người hướng dẫn', type:'noun', example:'The instructor is very experienced.', viAnswers:['giảng viên','người hướng dẫn']},
      {word:'participant', meaning:'người tham gia', type:'noun', example:'There are 50 participants.', viAnswers:['người tham gia']},
      {word:'material', meaning:'tài liệu', type:'noun', example:'Please bring your training materials.', viAnswers:['tài liệu','vật liệu']},
      {word:'module', meaning:'mô-đun, phần học', type:'noun', example:'This course has five modules.', viAnswers:['mô-đun','phần học','module']},
      {word:'session', meaning:'buổi học, phiên', type:'noun', example:'The morning session is two hours.', viAnswers:['buổi học','phiên','buổi']},
      {word:'skill', meaning:'kỹ năng', type:'noun', example:'Communication is an important skill.', viAnswers:['kỹ năng']},
      {word:'develop', meaning:'phát triển', type:'verb', example:'We develop new skills every day.', viAnswers:['phát triển']},
      {word:'certify', meaning:'chứng nhận, cấp chứng chỉ', type:'verb', example:'The course will certify you.', viAnswers:['chứng nhận','cấp chứng chỉ']},
      {word:'accredit', meaning:'công nhận, cấp phép', type:'verb', example:'The university is accredited.', viAnswers:['công nhận','cấp phép']},
      {word:'evaluate', meaning:'đánh giá', type:'verb', example:'We evaluate each student carefully.', viAnswers:['đánh giá']},
      {word:'assess', meaning:'đánh giá, nhận định', type:'verb', example:'The test will assess your level.', viAnswers:['đánh giá','nhận định']},
      {word:'competent', meaning:'có năng lực', type:'adjective', example:'She is a competent manager.', viAnswers:['có năng lực','đủ năng lực','thành thạo']},
      {word:'proficient', meaning:'thành thạo, thông thạo', type:'adjective', example:'He is proficient in English.', viAnswers:['thành thạo','thông thạo']},
      {word:'beginner', meaning:'người mới bắt đầu', type:'noun', example:'This class is for beginners.', viAnswers:['người mới bắt đầu','người mới']},
      {word:'advanced', meaning:'nâng cao', type:'adjective', example:'She took an advanced course.', viAnswers:['nâng cao','trình độ cao']},
      {word:'mentor', meaning:'người cố vấn', type:'noun', example:'My mentor helped me a lot.', viAnswers:['người cố vấn','cố vấn']},
      {word:'coach', meaning:'huấn luyện viên', type:'noun / verb', example:'He is my business coach.', viAnswers:['huấn luyện viên','huấn luyện']},
      {word:'guide', meaning:'hướng dẫn, người hướng dẫn', type:'noun / verb', example:'The guide showed us around.', viAnswers:['hướng dẫn','người hướng dẫn']},
      {word:'practice', meaning:'thực hành, luyện tập', type:'noun / verb', example:'Practice makes perfect.', viAnswers:['thực hành','luyện tập']},
      {word:'demonstrate', meaning:'minh họa, trình diễn', type:'verb', example:'She demonstrated how to use it.', viAnswers:['minh họa','trình diễn','chứng minh']}
    ]
  },
  {
    day: 47,
    topic: "Bảo hiểm",
    topicEn: "Insurance",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Giới từ (Prepositions)",
      explanation: "Giới từ là phần hay gặp trong TOEIC Part 5. Cần nhớ các giới từ đi với danh từ, động từ, tính từ: 1) Giới từ chỉ thời gian: in (tháng, năm), on (ngày), at (giờ), by (trước thời hạn), within (trong vòng). 2) Giới từ chỉ nơi chốn: in, on, at, between, among. 3) Cụm giới từ cố định: depend on, apply for, responsible for, comply with.",
      structure: "Verb/Adj/Noun + Preposition (học thuộc cụm cố định)",
      examples: [
        "The insurance policy is valid ___ two years. (for)",
        "You must file a claim ___ 30 days. (within)",
        "The coverage depends ___ the plan you choose. (on)",
        "She applied ___ health insurance. (for)"
      ],
      tips: "Giới từ không có quy tắc rõ ràng - phải HỌC THUỘC từng cụm. Mỗi ngày học 3-5 cụm giới từ. Ví dụ: apply for, depend on, responsible for, comply with."
    },
    words: [
      {word:'insurance', meaning:'bảo hiểm', type:'noun', example:'Do you have health insurance?', viAnswers:['bảo hiểm']},
      {word:'policy', meaning:'hợp đồng bảo hiểm', type:'noun', example:'Review your insurance policy.', viAnswers:['hợp đồng bảo hiểm','chính sách']},
      {word:'premium', meaning:'phí bảo hiểm', type:'noun', example:'The monthly premium is $200.', viAnswers:['phí bảo hiểm','phí']},
      {word:'coverage', meaning:'phạm vi bảo hiểm', type:'noun', example:'The coverage includes dental care.', viAnswers:['phạm vi bảo hiểm','bảo hiểm','sự bao phủ']},
      {word:'claim', meaning:'yêu cầu bồi thường', type:'noun / verb', example:'She filed a claim after the accident.', viAnswers:['yêu cầu bồi thường','khiếu nại']},
      {word:'deductible', meaning:'khoản khấu trừ', type:'noun', example:'The deductible is $500.', viAnswers:['khoản khấu trừ','mức miễn thường']},
      {word:'benefit', meaning:'quyền lợi, lợi ích', type:'noun', example:'The benefits are very good.', viAnswers:['quyền lợi','lợi ích']},
      {word:'provider', meaning:'nhà cung cấp', type:'noun', example:'Choose an insurance provider.', viAnswers:['nhà cung cấp']},
      {word:'liability', meaning:'trách nhiệm bồi thường', type:'noun', example:'The liability is limited.', viAnswers:['trách nhiệm bồi thường','trách nhiệm pháp lý','trách nhiệm']},
      {word:'property', meaning:'tài sản', type:'noun', example:'Insure your property against fire.', viAnswers:['tài sản','bất động sản']},
      {word:'damage', meaning:'thiệt hại, hư hại', type:'noun / verb', example:'The storm caused a lot of damage.', viAnswers:['thiệt hại','hư hại','tổn hại']},
      {word:'accident', meaning:'tai nạn', type:'noun', example:'He had a car accident.', viAnswers:['tai nạn']},
      {word:'injury', meaning:'chấn thương', type:'noun', example:'She suffered a minor injury.', viAnswers:['chấn thương','thương tích']},
      {word:'medical', meaning:'y tế, thuộc y khoa', type:'adjective', example:'Medical insurance is important.', viAnswers:['y tế','thuộc y khoa']},
      {word:'dental', meaning:'nha khoa', type:'adjective', example:'I need dental insurance.', viAnswers:['nha khoa','thuộc nha khoa']},
      {word:'vision', meaning:'thị lực, thị giác', type:'noun', example:'Vision care is covered.', viAnswers:['thị lực','thị giác','tầm nhìn']},
      {word:'disability', meaning:'khuyết tật, tàn tật', type:'noun', example:'Disability insurance helps workers.', viAnswers:['khuyết tật','tàn tật','sự khuyết tật']},
      {word:'life', meaning:'cuộc sống, nhân thọ', type:'noun', example:'He has life insurance.', viAnswers:['cuộc sống','nhân thọ','đời sống']},
      {word:'health', meaning:'sức khỏe', type:'noun', example:'Health insurance is required.', viAnswers:['sức khỏe']},
      {word:'renew', meaning:'gia hạn, đổi mới', type:'verb', example:'Renew your policy before it expires.', viAnswers:['gia hạn','đổi mới','làm mới']},
      {word:'cancel', meaning:'hủy bỏ', type:'verb', example:'You can cancel the policy anytime.', viAnswers:['hủy bỏ','hủy']},
      {word:'exclude', meaning:'loại trừ', type:'verb', example:'Some conditions are excluded.', viAnswers:['loại trừ','không bao gồm']},
      {word:'reimburse', meaning:'hoàn trả, bồi hoàn', type:'verb', example:'The company will reimburse your costs.', viAnswers:['hoàn trả','bồi hoàn']},
      {word:'approve', meaning:'phê duyệt, chấp thuận', type:'verb', example:'The claim was approved.', viAnswers:['phê duyệt','chấp thuận']},
      {word:'dependent', meaning:'người phụ thuộc', type:'noun / adjective', example:'Add your dependents to the plan.', viAnswers:['người phụ thuộc','phụ thuộc']}
    ]
  },
  {
    day: 48,
    topic: "Bất động sản",
    topicEn: "Real Estate",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Liên từ (Conjunctions)",
      explanation: "Liên từ nối các mệnh đề trong câu. Có 3 loại chính: 1) Liên từ kết hợp (and, but, or, so, yet): nối 2 mệnh đề ngang hàng. 2) Liên từ phụ thuộc (because, although, if, when, while, unless, until, before, after, since): nối mệnh đề phụ với mệnh đề chính. 3) Liên từ tương quan (both...and, either...or, neither...nor, not only...but also).",
      structure: "Clause 1 + conjunction + Clause 2",
      examples: [
        "___ the property is expensive, it is in a great location. (Although)",
        "We will sign the lease ___ we agree on the price. (after / when)",
        "The tenant must pay rent ___ the landlord will cancel the lease. (or)",
        "___ the house is old, it needs renovation. (Because / Since)"
      ],
      tips: "Đọc cả 2 mệnh đề để hiểu QUAN HỆ LOGIC giữa chúng: nguyên nhân → because/since, tương phản → although/even though, điều kiện → if/unless, thời gian → when/while/before/after."
    },
    words: [
      {word:'property', meaning:'bất động sản, tài sản', type:'noun', example:'They own several properties.', viAnswers:['bất động sản','tài sản']},
      {word:'land', meaning:'đất đai', type:'noun', example:'The land is for sale.', viAnswers:['đất đai','đất']},
      {word:'building', meaning:'tòa nhà', type:'noun', example:'The building has ten floors.', viAnswers:['tòa nhà','công trình']},
      {word:'commercial', meaning:'thương mại', type:'adjective', example:'This is a commercial area.', viAnswers:['thương mại']},
      {word:'residential', meaning:'dân cư, nhà ở', type:'adjective', example:'This is a residential neighborhood.', viAnswers:['dân cư','nhà ở','khu dân cư']},
      {word:'lease', meaning:'hợp đồng thuê', type:'noun / verb', example:'The lease is for one year.', viAnswers:['hợp đồng thuê','thuê']},
      {word:'rent', meaning:'tiền thuê, thuê', type:'noun / verb', example:'The rent is $1000 per month.', viAnswers:['tiền thuê','thuê']},
      {word:'purchase', meaning:'mua', type:'verb / noun', example:'They want to purchase a house.', viAnswers:['mua','mua sắm']},
      {word:'mortgage', meaning:'thế chấp', type:'noun', example:'They got a mortgage from the bank.', viAnswers:['thế chấp','vay thế chấp']},
      {word:'appraisal', meaning:'sự thẩm định giá', type:'noun', example:'The appraisal shows the house value.', viAnswers:['sự thẩm định giá','thẩm định','định giá']},
      {word:'listing', meaning:'danh sách bán, tin rao bán', type:'noun', example:'Check the new property listings.', viAnswers:['danh sách bán','tin rao bán','niêm yết']},
      {word:'agent', meaning:'đại lý, môi giới', type:'noun', example:'The real estate agent helped us.', viAnswers:['đại lý','môi giới','nhân viên môi giới']},
      {word:'broker', meaning:'người môi giới', type:'noun', example:'The broker found a good deal.', viAnswers:['người môi giới','môi giới']},
      {word:'commission', meaning:'hoa hồng, tiền hoa hồng', type:'noun', example:'The agent earns a commission.', viAnswers:['hoa hồng','tiền hoa hồng']},
      {word:'inspection', meaning:'kiểm tra', type:'noun', example:'The inspection found no problems.', viAnswers:['kiểm tra','sự kiểm tra']},
      {word:'zoning', meaning:'quy hoạch khu vực', type:'noun', example:'Zoning laws limit building height.', viAnswers:['quy hoạch khu vực','quy hoạch','phân vùng']},
      {word:'permit', meaning:'giấy phép', type:'noun', example:'You need a building permit.', viAnswers:['giấy phép']},
      {word:'renovation', meaning:'sửa chữa, cải tạo', type:'noun', example:'The renovation took three months.', viAnswers:['sửa chữa','cải tạo','tu sửa']},
      {word:'tenant', meaning:'người thuê', type:'noun', example:'The tenant pays rent on time.', viAnswers:['người thuê','người thuê nhà']},
      {word:'landlord', meaning:'chủ nhà (cho thuê)', type:'noun', example:'The landlord fixed the roof.', viAnswers:['chủ nhà','chủ cho thuê']},
      {word:'vacancy', meaning:'phòng trống, chỗ trống', type:'noun', example:'There is a vacancy on the third floor.', viAnswers:['phòng trống','chỗ trống']},
      {word:'occupy', meaning:'chiếm, ở, sử dụng', type:'verb', example:'The office is occupied.', viAnswers:['chiếm','ở','sử dụng','chiếm giữ']},
      {word:'relocate', meaning:'di dời, chuyển chỗ', type:'verb', example:'The company will relocate next year.', viAnswers:['di dời','chuyển chỗ','chuyển đi']},
      {word:'suburb', meaning:'ngoại ô, vùng ven', type:'noun', example:'They live in the suburbs.', viAnswers:['ngoại ô','vùng ven']},
      {word:'downtown', meaning:'trung tâm thành phố', type:'noun / adverb', example:'The office is downtown.', viAnswers:['trung tâm thành phố','trung tâm']}
    ]
  },
  {
    day: 49,
    topic: "Thuế",
    topicEn: "Taxes",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Đại từ (Pronouns)",
      explanation: "Đại từ thường xuất hiện trong TOEIC Part 5. Các loại đại từ cần nhớ: 1) Đại từ nhân xưng: I, you, he, she, it, we, they. 2) Đại từ tân ngữ: me, you, him, her, it, us, them. 3) Tính từ sở hữu: my, your, his, her, its, our, their. 4) Đại từ sở hữu: mine, yours, his, hers, ours, theirs. 5) Đại từ phản thân: myself, yourself, himself, herself, itself, ourselves, themselves.",
      structure: "Chủ ngữ → đại từ nhân xưng | Tân ngữ → đại từ tân ngữ | Trước danh từ → tính từ sở hữu",
      examples: [
        "Each taxpayer must file ___ return on time. (his/her - tính từ sở hữu)",
        "The accountant prepared the report ___. (herself - đại từ phản thân)",
        "The company paid ___ taxes early. (its - tính từ sở hữu)",
        "___ who file late will pay a penalty. (Those - đại từ chỉ định)"
      ],
      tips: "Nhìn vị trí chỗ trống: trước danh từ → tính từ sở hữu (my, your, his...). Sau động từ → tân ngữ (me, him, her...). Đứng một mình → đại từ sở hữu (mine, yours...)."
    },
    words: [
      {word:'tax', meaning:'thuế', type:'noun', example:'Everyone must pay taxes.', viAnswers:['thuế']},
      {word:'income', meaning:'thu nhập', type:'noun', example:'Her income is high.', viAnswers:['thu nhập']},
      {word:'revenue', meaning:'doanh thu', type:'noun', example:'The company revenue grew.', viAnswers:['doanh thu']},
      {word:'deduction', meaning:'khoản khấu trừ', type:'noun', example:'You can claim a tax deduction.', viAnswers:['khoản khấu trừ','khấu trừ']},
      {word:'exemption', meaning:'miễn trừ', type:'noun', example:'He has a tax exemption.', viAnswers:['miễn trừ','sự miễn trừ']},
      {word:'refund', meaning:'hoàn thuế, tiền hoàn lại', type:'noun / verb', example:'I got a tax refund.', viAnswers:['hoàn thuế','tiền hoàn lại','hoàn trả']},
      {word:'file', meaning:'nộp, khai', type:'verb', example:'File your tax return before April.', viAnswers:['nộp','khai','nộp hồ sơ']},
      {word:'return', meaning:'tờ khai thuế', type:'noun', example:'Submit your tax return on time.', viAnswers:['tờ khai thuế','tờ khai','sự trở về']},
      {word:'audit', meaning:'kiểm toán', type:'noun / verb', example:'The company had a tax audit.', viAnswers:['kiểm toán']},
      {word:'comply', meaning:'tuân thủ', type:'verb', example:'You must comply with tax laws.', viAnswers:['tuân thủ','tuân theo']},
      {word:'penalty', meaning:'tiền phạt', type:'noun', example:'Pay the penalty for late filing.', viAnswers:['tiền phạt','hình phạt']},
      {word:'deadline', meaning:'hạn chót', type:'noun', example:'The tax deadline is April 15.', viAnswers:['hạn chót','thời hạn']},
      {word:'withhold', meaning:'khấu trừ, giữ lại', type:'verb', example:'The employer withholds tax from salary.', viAnswers:['khấu trừ','giữ lại']},
      {word:'payroll', meaning:'bảng lương', type:'noun', example:'Payroll taxes are paid monthly.', viAnswers:['bảng lương']},
      {word:'corporate', meaning:'doanh nghiệp, công ty', type:'adjective', example:'Corporate tax is 20%.', viAnswers:['doanh nghiệp','công ty','thuộc công ty']},
      {word:'individual', meaning:'cá nhân', type:'noun / adjective', example:'Individual tax rates vary.', viAnswers:['cá nhân']},
      {word:'capital', meaning:'vốn, tư bản', type:'noun', example:'Capital gains are taxed.', viAnswers:['vốn','tư bản']},
      {word:'gain', meaning:'lợi nhuận, lãi', type:'noun', example:'Report all gains on your return.', viAnswers:['lợi nhuận','lãi','thu được']},
      {word:'loss', meaning:'lỗ, mất mát', type:'noun', example:'The company reported a loss.', viAnswers:['lỗ','mất mát','thua lỗ']},
      {word:'bracket', meaning:'khung thuế, bậc thuế', type:'noun', example:'Which tax bracket are you in?', viAnswers:['khung thuế','bậc thuế']},
      {word:'rate', meaning:'tỷ lệ, mức', type:'noun', example:'The tax rate is 10%.', viAnswers:['tỷ lệ','mức']},
      {word:'calculate', meaning:'tính toán', type:'verb', example:'Calculate your total tax.', viAnswers:['tính toán','tính']},
      {word:'owe', meaning:'nợ', type:'verb', example:'You owe $500 in taxes.', viAnswers:['nợ']},
      {word:'receipt', meaning:'biên lai, hóa đơn', type:'noun', example:'Keep all your receipts.', viAnswers:['biên lai','hóa đơn']},
      {word:'accountant', meaning:'kế toán', type:'noun', example:'Ask your accountant for help.', viAnswers:['kế toán','nhân viên kế toán']}
    ]
  },
  {
    day: 50,
    topic: "Nghiên cứu",
    topicEn: "Research",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - Câu bị động (Passive Voice)",
      explanation: "Câu bị động được dùng khi muốn nhấn mạnh đối tượng chịu tác động hoặc khi không biết ai thực hiện hành động. Cấu trúc: Subject + be + V3/ed (+ by agent). Các thì bị động thường gặp: 1) Hiện tại đơn: is/are + V3. 2) Quá khứ đơn: was/were + V3. 3) Hiện tại hoàn thành: has/have been + V3. 4) Tương lai: will be + V3.",
      structure: "Subject + be + past participle (V3) + (by + agent)",
      examples: [
        "The research ___ conducted by a team of scientists. (was - quá khứ bị động)",
        "The data ___ being analyzed now. (is - hiện tại tiếp diễn bị động)",
        "The results ___ published next month. (will be - tương lai bị động)",
        "The report has ___ reviewed by experts. (been - hiện tại hoàn thành bị động)"
      ],
      tips: "Nếu chủ ngữ là người/vật CHỊU tác động → dùng bị động. Dấu hiệu: có 'by + ai đó' phía sau, hoặc không đề cập ai thực hiện hành động."
    },
    words: [
      {word:'research', meaning:'nghiên cứu', type:'noun / verb', example:'The research takes two years.', viAnswers:['nghiên cứu']},
      {word:'study', meaning:'nghiên cứu, học', type:'noun / verb', example:'The study shows good results.', viAnswers:['nghiên cứu','học','học tập']},
      {word:'experiment', meaning:'thí nghiệm', type:'noun', example:'The experiment was successful.', viAnswers:['thí nghiệm']},
      {word:'data', meaning:'dữ liệu', type:'noun', example:'We need more data.', viAnswers:['dữ liệu','số liệu']},
      {word:'analyze', meaning:'phân tích', type:'verb', example:'Analyze the data carefully.', viAnswers:['phân tích']},
      {word:'result', meaning:'kết quả', type:'noun', example:'The results are positive.', viAnswers:['kết quả']},
      {word:'finding', meaning:'phát hiện, kết luận', type:'noun', example:'The findings were surprising.', viAnswers:['phát hiện','kết luận']},
      {word:'conclusion', meaning:'kết luận', type:'noun', example:'The conclusion is clear.', viAnswers:['kết luận']},
      {word:'hypothesis', meaning:'giả thuyết', type:'noun', example:'The hypothesis was proven correct.', viAnswers:['giả thuyết']},
      {word:'method', meaning:'phương pháp', type:'noun', example:'Use the correct method.', viAnswers:['phương pháp']},
      {word:'survey', meaning:'khảo sát', type:'noun / verb', example:'We conducted a survey.', viAnswers:['khảo sát','cuộc khảo sát']},
      {word:'sample', meaning:'mẫu', type:'noun', example:'We tested a small sample.', viAnswers:['mẫu','mẫu thử']},
      {word:'statistics', meaning:'thống kê', type:'noun', example:'The statistics support our theory.', viAnswers:['thống kê','số liệu thống kê']},
      {word:'evidence', meaning:'bằng chứng', type:'noun', example:'There is strong evidence.', viAnswers:['bằng chứng','chứng cứ']},
      {word:'report', meaning:'báo cáo', type:'noun / verb', example:'Write a report about the project.', viAnswers:['báo cáo']},
      {word:'publish', meaning:'xuất bản, công bố', type:'verb', example:'They published the results.', viAnswers:['xuất bản','công bố']},
      {word:'peer', meaning:'đồng nghiệp, ngang hàng', type:'noun / adjective', example:'The paper was peer reviewed.', viAnswers:['đồng nghiệp','ngang hàng']},
      {word:'review', meaning:'đánh giá, xem xét', type:'noun / verb', example:'The review process takes time.', viAnswers:['đánh giá','xem xét']},
      {word:'journal', meaning:'tạp chí khoa học', type:'noun', example:'The article was published in a journal.', viAnswers:['tạp chí khoa học','tạp chí','nhật ký']},
      {word:'academic', meaning:'học thuật', type:'adjective', example:'He has an academic background.', viAnswers:['học thuật','thuộc học thuật']},
      {word:'theory', meaning:'lý thuyết', type:'noun', example:'The theory is interesting.', viAnswers:['lý thuyết']},
      {word:'observe', meaning:'quan sát', type:'verb', example:'We observe the changes carefully.', viAnswers:['quan sát']},
      {word:'measure', meaning:'đo lường', type:'verb', example:'Measure the temperature every hour.', viAnswers:['đo lường','đo']},
      {word:'variable', meaning:'biến số', type:'noun', example:'Control all variables in the test.', viAnswers:['biến số','biến']},
      {word:'significant', meaning:'đáng kể, quan trọng', type:'adjective', example:'The difference is significant.', viAnswers:['đáng kể','quan trọng','có ý nghĩa']}
    ]
  },
  {
    day: 51,
    topic: "Đàm phán",
    topicEn: "Negotiations",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Reading Part 5 - So sánh (Comparisons)",
      explanation: "Có 3 cấp so sánh: 1) So sánh hơn: tính từ ngắn + -er + than / more + tính từ dài + than. 2) So sánh nhất: the + tính từ ngắn + -est / the most + tính từ dài. 3) So sánh bằng: as + adj/adv + as. Ngoại lệ: good → better → best, bad → worse → worst, much/many → more → most, little → less → least.",
      structure: "So sánh hơn: adj-er than / more adj than | So sánh nhất: the adj-est / the most adj | So sánh bằng: as adj as",
      examples: [
        "This offer is ___ than the last one. (better - so sánh hơn bất quy tắc)",
        "We need a ___ flexible approach. (more - so sánh hơn, tính từ dài)",
        "This is the ___ important deal of the year. (most - so sánh nhất)",
        "Our terms are as ___ as theirs. (fair - so sánh bằng)"
      ],
      tips: "Tính từ ngắn (1 âm tiết): thêm -er/-est. Tính từ dài (2+ âm tiết): dùng more/most. Luôn nhớ ngoại lệ: good-better-best, bad-worse-worst."
    },
    words: [
      {word:'negotiate', meaning:'đàm phán', type:'verb', example:'We need to negotiate the price.', viAnswers:['đàm phán','thương lượng']},
      {word:'offer', meaning:'đề nghị, lời đề nghị', type:'noun / verb', example:'They made a good offer.', viAnswers:['đề nghị','lời đề nghị']},
      {word:'counter', meaning:'phản đề nghị, phản bác', type:'verb / noun', example:'She countered with a lower price.', viAnswers:['phản đề nghị','phản bác','đáp trả']},
      {word:'accept', meaning:'chấp nhận', type:'verb', example:'I accept your offer.', viAnswers:['chấp nhận','đồng ý']},
      {word:'reject', meaning:'từ chối', type:'verb', example:'They rejected the proposal.', viAnswers:['từ chối','bác bỏ']},
      {word:'propose', meaning:'đề xuất', type:'verb', example:'I propose a new plan.', viAnswers:['đề xuất','đề nghị']},
      {word:'compromise', meaning:'thỏa hiệp', type:'noun / verb', example:'We reached a compromise.', viAnswers:['thỏa hiệp','sự thỏa hiệp']},
      {word:'concession', meaning:'sự nhượng bộ', type:'noun', example:'Both sides made concessions.', viAnswers:['sự nhượng bộ','nhượng bộ']},
      {word:'demand', meaning:'yêu cầu, đòi hỏi', type:'noun / verb', example:'Their demands are too high.', viAnswers:['yêu cầu','đòi hỏi','nhu cầu']},
      {word:'condition', meaning:'điều kiện', type:'noun', example:'We agreed on certain conditions.', viAnswers:['điều kiện']},
      {word:'deadline', meaning:'hạn chót', type:'noun', example:'The deadline for the deal is Friday.', viAnswers:['hạn chót','thời hạn']},
      {word:'leverage', meaning:'đòn bẩy, lợi thế', type:'noun', example:'We have leverage in this deal.', viAnswers:['đòn bẩy','lợi thế']},
      {word:'strategy', meaning:'chiến lược', type:'noun', example:'Our strategy is to wait.', viAnswers:['chiến lược']},
      {word:'outcome', meaning:'kết quả', type:'noun', example:'The outcome was positive.', viAnswers:['kết quả']},
      {word:'mutual', meaning:'lẫn nhau, chung', type:'adjective', example:'We have mutual respect.', viAnswers:['lẫn nhau','chung','tương hỗ']},
      {word:'benefit', meaning:'lợi ích', type:'noun', example:'Both sides benefit from the deal.', viAnswers:['lợi ích','quyền lợi']},
      {word:'dispute', meaning:'tranh chấp', type:'noun', example:'There is a dispute about the price.', viAnswers:['tranh chấp']},
      {word:'mediate', meaning:'hòa giải, trung gian', type:'verb', example:'A lawyer will mediate the dispute.', viAnswers:['hòa giải','trung gian','làm trung gian']},
      {word:'resolve', meaning:'giải quyết', type:'verb', example:'We resolved the issue quickly.', viAnswers:['giải quyết']},
      {word:'agreement', meaning:'thỏa thuận', type:'noun', example:'We signed an agreement.', viAnswers:['thỏa thuận','hợp đồng']},
      {word:'terms', meaning:'điều khoản', type:'noun', example:'Read the terms carefully.', viAnswers:['điều khoản']},
      {word:'priority', meaning:'ưu tiên', type:'noun', example:'Safety is our top priority.', viAnswers:['ưu tiên','sự ưu tiên']},
      {word:'flexible', meaning:'linh hoạt', type:'adjective', example:'We are flexible on the date.', viAnswers:['linh hoạt']},
      {word:'firm', meaning:'kiên quyết, vững chắc', type:'adjective', example:'She is firm about the deadline.', viAnswers:['kiên quyết','vững chắc','cứng rắn']},
      {word:'deal', meaning:'thỏa thuận, giao dịch', type:'noun', example:'It is a good deal for everyone.', viAnswers:['thỏa thuận','giao dịch','hợp đồng']}
    ]
  },
  {
    day: 52,
    topic: "Nghệ thuật / Văn hóa",
    topicEn: "Arts / Culture",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 1)",
      explanation: "Ôn tập tổng hợp các điểm ngữ pháp đã học: từ loại, thì động từ, giới từ, liên từ, đại từ, bị động, so sánh. Khi làm bài TOEIC Part 5, làm theo quy trình: 1) Đọc toàn bộ câu, 2) Xác định loại câu hỏi (từ loại? thì? giới từ?...), 3) Áp dụng kiến thức ngữ pháp phù hợp, 4) Chọn đáp án, 5) Đọc lại câu hoàn chỉnh để kiểm tra.",
      structure: "Đọc câu → Xác định loại câu hỏi → Áp dụng quy tắc → Chọn đáp án → Kiểm tra",
      examples: [
        "The ___ performance was amazing. (artistic - từ loại: tính từ trước danh từ)",
        "The exhibition ___ visited by thousands of people. (was - bị động quá khứ)",
        "This painting is ___ beautiful than that one. (more - so sánh hơn)",
        "The artist created the sculpture ___ herself. (by - giới từ)"
      ],
      tips: "Làm bài Part 5 không quá 30 giây mỗi câu. Nếu không chắc chắn, dùng phương pháp loại trừ. Đánh dấu câu khó và quay lại sau."
    },
    words: [
      {word:'art', meaning:'nghệ thuật', type:'noun', example:'She loves art.', viAnswers:['nghệ thuật']},
      {word:'museum', meaning:'bảo tàng', type:'noun', example:'We visited the museum.', viAnswers:['bảo tàng','viện bảo tàng']},
      {word:'gallery', meaning:'phòng tranh, triển lãm', type:'noun', example:'The gallery has many paintings.', viAnswers:['phòng tranh','triển lãm','phòng trưng bày']},
      {word:'exhibit', meaning:'trưng bày, hiện vật', type:'verb / noun', example:'The museum will exhibit new art.', viAnswers:['trưng bày','hiện vật','triển lãm']},
      {word:'sculpture', meaning:'tác phẩm điêu khắc', type:'noun', example:'The sculpture is made of stone.', viAnswers:['tác phẩm điêu khắc','điêu khắc','tượng']},
      {word:'painting', meaning:'bức tranh', type:'noun', example:'This painting is very old.', viAnswers:['bức tranh','tranh','bức họa']},
      {word:'artist', meaning:'nghệ sĩ', type:'noun', example:'The artist is very famous.', viAnswers:['nghệ sĩ','họa sĩ']},
      {word:'creative', meaning:'sáng tạo', type:'adjective', example:'She is very creative.', viAnswers:['sáng tạo']},
      {word:'design', meaning:'thiết kế', type:'noun / verb', example:'The design is beautiful.', viAnswers:['thiết kế']},
      {word:'perform', meaning:'biểu diễn, trình diễn', type:'verb', example:'The band will perform tonight.', viAnswers:['biểu diễn','trình diễn','thực hiện']},
      {word:'theater', meaning:'nhà hát, rạp hát', type:'noun', example:'We went to the theater.', viAnswers:['nhà hát','rạp hát']},
      {word:'opera', meaning:'nhạc kịch, opera', type:'noun', example:'She loves watching opera.', viAnswers:['nhạc kịch','opera']},
      {word:'ballet', meaning:'múa ba-lê', type:'noun', example:'The ballet performance was wonderful.', viAnswers:['múa ba-lê','ba-lê','ballet']},
      {word:'orchestra', meaning:'dàn nhạc', type:'noun', example:'The orchestra played beautifully.', viAnswers:['dàn nhạc']},
      {word:'instrument', meaning:'nhạc cụ', type:'noun', example:'She plays three instruments.', viAnswers:['nhạc cụ','dụng cụ']},
      {word:'compose', meaning:'sáng tác', type:'verb', example:'He composed a new song.', viAnswers:['sáng tác']},
      {word:'direct', meaning:'đạo diễn, chỉ đạo', type:'verb', example:'She directed the movie.', viAnswers:['đạo diễn','chỉ đạo','hướng dẫn']},
      {word:'produce', meaning:'sản xuất, tạo ra', type:'verb', example:'They produced a great film.', viAnswers:['sản xuất','tạo ra']},
      {word:'culture', meaning:'văn hóa', type:'noun', example:'Vietnamese culture is rich.', viAnswers:['văn hóa']},
      {word:'tradition', meaning:'truyền thống', type:'noun', example:'This is an old tradition.', viAnswers:['truyền thống']},
      {word:'heritage', meaning:'di sản', type:'noun', example:'Protect our cultural heritage.', viAnswers:['di sản']},
      {word:'festival', meaning:'lễ hội', type:'noun', example:'The festival is in March.', viAnswers:['lễ hội']},
      {word:'craft', meaning:'thủ công, nghề thủ công', type:'noun', example:'She sells handmade crafts.', viAnswers:['thủ công','nghề thủ công','đồ thủ công']},
      {word:'inspire', meaning:'truyền cảm hứng', type:'verb', example:'The art inspired many people.', viAnswers:['truyền cảm hứng','gợi cảm hứng']},
      {word:'express', meaning:'biểu đạt, thể hiện', type:'verb', example:'Art helps us express feelings.', viAnswers:['biểu đạt','thể hiện','diễn đạt']}
    ]
  },
  {
    day: 53,
    topic: "Chính phủ",
    topicEn: "Government",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 2)",
      explanation: "Tiếp tục ôn tập tổng hợp. Tập trung vào các dạng câu hỏi thường gặp trong TOEIC: 1) Chọn từ vựng phù hợp ngữ cảnh, 2) Điền từ nối mệnh đề (however, therefore, moreover, furthermore, nevertheless, in addition), 3) Phân biệt các từ gần nghĩa nhưng khác cách dùng (như rise/raise, lay/lie, affect/effect).",
      structure: "Đọc ngữ cảnh → Xác định nghĩa phù hợp → Chọn từ chính xác",
      examples: [
        "The government ___ a new law. (passed - chọn từ phù hợp ngữ cảnh)",
        "Taxes increased; ___, spending was cut. (therefore - từ nối chỉ kết quả)",
        "The policy will ___ all citizens. (affect - phân biệt affect/effect)",
        "The president ___ reforms. (implemented - từ vựng ngữ cảnh)"
      ],
      tips: "Với câu hỏi từ vựng, đọc toàn bộ câu để hiểu ngữ cảnh. Đừng chỉ nhìn chỗ trống. Nhiều khi đáp án đúng không phải từ bạn nghĩ đầu tiên."
    },
    words: [
      {word:'government', meaning:'chính phủ', type:'noun', example:'The government made a new law.', viAnswers:['chính phủ']},
      {word:'president', meaning:'tổng thống, chủ tịch', type:'noun', example:'The president gave a speech.', viAnswers:['tổng thống','chủ tịch']},
      {word:'minister', meaning:'bộ trưởng', type:'noun', example:'The minister of education spoke.', viAnswers:['bộ trưởng']},
      {word:'parliament', meaning:'quốc hội, nghị viện', type:'noun', example:'Parliament approved the budget.', viAnswers:['quốc hội','nghị viện']},
      {word:'election', meaning:'bầu cử', type:'noun', example:'The election is next year.', viAnswers:['bầu cử','cuộc bầu cử']},
      {word:'vote', meaning:'bỏ phiếu, bầu', type:'noun / verb', example:'Everyone should vote.', viAnswers:['bỏ phiếu','bầu','phiếu bầu']},
      {word:'citizen', meaning:'công dân', type:'noun', example:'Every citizen has rights.', viAnswers:['công dân']},
      {word:'democracy', meaning:'dân chủ', type:'noun', example:'Democracy is important.', viAnswers:['dân chủ','nền dân chủ']},
      {word:'policy', meaning:'chính sách', type:'noun', example:'The new policy helps families.', viAnswers:['chính sách']},
      {word:'budget', meaning:'ngân sách', type:'noun', example:'The budget was approved.', viAnswers:['ngân sách']},
      {word:'legislation', meaning:'luật pháp, sự lập pháp', type:'noun', example:'New legislation was passed.', viAnswers:['luật pháp','sự lập pháp','pháp luật']},
      {word:'regulate', meaning:'quản lý, điều tiết', type:'verb', example:'The government regulates businesses.', viAnswers:['quản lý','điều tiết']},
      {word:'public', meaning:'công cộng, công chúng', type:'adjective / noun', example:'This is a public building.', viAnswers:['công cộng','công chúng']},
      {word:'official', meaning:'quan chức, chính thức', type:'noun / adjective', example:'The official announcement was made.', viAnswers:['quan chức','chính thức']},
      {word:'committee', meaning:'ủy ban', type:'noun', example:'The committee will decide.', viAnswers:['ủy ban','ban']},
      {word:'council', meaning:'hội đồng', type:'noun', example:'The city council met today.', viAnswers:['hội đồng']},
      {word:'agency', meaning:'cơ quan, đại lý', type:'noun', example:'The agency handles immigration.', viAnswers:['cơ quan','đại lý']},
      {word:'department', meaning:'bộ, phòng ban', type:'noun', example:'The Department of Health issued a notice.', viAnswers:['bộ','phòng ban']},
      {word:'federal', meaning:'liên bang', type:'adjective', example:'Federal law applies to all states.', viAnswers:['liên bang','thuộc liên bang']},
      {word:'state', meaning:'bang, tiểu bang, nhà nước', type:'noun', example:'Each state has its own laws.', viAnswers:['bang','tiểu bang','nhà nước']},
      {word:'local', meaning:'địa phương', type:'adjective', example:'Local government manages the city.', viAnswers:['địa phương']},
      {word:'reform', meaning:'cải cách', type:'noun / verb', example:'The country needs reform.', viAnswers:['cải cách']},
      {word:'debate', meaning:'tranh luận', type:'noun / verb', example:'The debate lasted two hours.', viAnswers:['tranh luận','cuộc tranh luận']},
      {word:'campaign', meaning:'chiến dịch, vận động', type:'noun', example:'The election campaign has started.', viAnswers:['chiến dịch','vận động','cuộc vận động']},
      {word:'represent', meaning:'đại diện', type:'verb', example:'She represents the company.', viAnswers:['đại diện']}
    ]
  },
  {
    day: 54,
    topic: "Chuỗi cung ứng",
    topicEn: "Supply Chain",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 3)",
      explanation: "Luyện tập tổng hợp tập trung vào Part 6 & 7 của TOEIC: đọc hiểu đoạn văn. Kỹ năng cần: 1) Đọc lướt (skimming) để nắm ý chính, 2) Đọc quét (scanning) để tìm thông tin cụ thể, 3) Suy luận ý ẩn (inference), 4) Hiểu mục đích của đoạn văn (email, thông báo, quảng cáo...).",
      structure: "Đọc câu hỏi trước → Đọc lướt bài → Tìm thông tin → Chọn đáp án",
      examples: [
        "Email: 'The shipment will arrive by Friday.' → Khi nào hàng đến? (By Friday)",
        "Notice: 'All vendors must submit invoices by the 15th.' → Ai phải nộp? (Vendors)",
        "Memo: 'Due to high demand, production has increased.' → Tại sao? (High demand)",
        "Ad: 'Free shipping on orders over $50.' → Điều kiện? (Orders over $50)"
      ],
      tips: "Đọc câu hỏi TRƯỚC khi đọc bài. Gạch chân từ khóa trong câu hỏi. Khi đọc bài, tìm từ khóa đó. Không cần hiểu 100% bài - chỉ cần tìm đúng thông tin."
    },
    words: [
      {word:'supply', meaning:'cung cấp, nguồn cung', type:'noun / verb', example:'The supply of goods is stable.', viAnswers:['cung cấp','nguồn cung']},
      {word:'chain', meaning:'chuỗi', type:'noun', example:'The supply chain is global.', viAnswers:['chuỗi']},
      {word:'logistics', meaning:'hậu cần, logistics', type:'noun', example:'Logistics is very important.', viAnswers:['hậu cần','logistics']},
      {word:'warehouse', meaning:'nhà kho, kho hàng', type:'noun', example:'The goods are in the warehouse.', viAnswers:['nhà kho','kho hàng','kho']},
      {word:'inventory', meaning:'hàng tồn kho', type:'noun', example:'Check the inventory list.', viAnswers:['hàng tồn kho','kiểm kê']},
      {word:'distribute', meaning:'phân phối', type:'verb', example:'We distribute products nationwide.', viAnswers:['phân phối']},
      {word:'transport', meaning:'vận chuyển', type:'verb / noun', example:'We transport goods by truck.', viAnswers:['vận chuyển']},
      {word:'freight', meaning:'hàng hóa vận chuyển', type:'noun', example:'The freight arrived on time.', viAnswers:['hàng hóa vận chuyển','vận tải','hàng hóa']},
      {word:'cargo', meaning:'hàng hóa (tàu/máy bay)', type:'noun', example:'The cargo was unloaded.', viAnswers:['hàng hóa','hàng']},
      {word:'customs', meaning:'hải quan', type:'noun', example:'The package is at customs.', viAnswers:['hải quan']},
      {word:'import', meaning:'nhập khẩu', type:'noun / verb', example:'We import electronics from Japan.', viAnswers:['nhập khẩu']},
      {word:'export', meaning:'xuất khẩu', type:'noun / verb', example:'Vietnam exports coffee.', viAnswers:['xuất khẩu']},
      {word:'manufacturer', meaning:'nhà sản xuất', type:'noun', example:'The manufacturer is in China.', viAnswers:['nhà sản xuất']},
      {word:'retailer', meaning:'nhà bán lẻ', type:'noun', example:'The retailer sells to customers.', viAnswers:['nhà bán lẻ']},
      {word:'wholesale', meaning:'bán buôn, bán sỉ', type:'noun / adjective', example:'We buy at wholesale prices.', viAnswers:['bán buôn','bán sỉ']},
      {word:'vendor', meaning:'nhà cung cấp, người bán', type:'noun', example:'The vendor delivers every Monday.', viAnswers:['nhà cung cấp','người bán']},
      {word:'procure', meaning:'mua sắm, thu mua', type:'verb', example:'We procure materials from abroad.', viAnswers:['mua sắm','thu mua']},
      {word:'order', meaning:'đơn hàng, đặt hàng', type:'noun / verb', example:'Place an order today.', viAnswers:['đơn hàng','đặt hàng']},
      {word:'track', meaning:'theo dõi', type:'verb', example:'Track your package online.', viAnswers:['theo dõi']},
      {word:'deliver', meaning:'giao hàng', type:'verb', example:'We deliver within 3 days.', viAnswers:['giao hàng','giao']},
      {word:'route', meaning:'tuyến đường', type:'noun', example:'The delivery route is long.', viAnswers:['tuyến đường','đường đi','lộ trình']},
      {word:'schedule', meaning:'lịch trình', type:'noun / verb', example:'The delivery schedule is fixed.', viAnswers:['lịch trình','lịch']},
      {word:'efficient', meaning:'hiệu quả', type:'adjective', example:'The system is very efficient.', viAnswers:['hiệu quả']},
      {word:'optimize', meaning:'tối ưu hóa', type:'verb', example:'We optimize the delivery process.', viAnswers:['tối ưu hóa','tối ưu']},
      {word:'automate', meaning:'tự động hóa', type:'verb', example:'We automate many tasks now.', viAnswers:['tự động hóa']}
    ]
  },
  {
    day: 55,
    topic: "Khiếu nại",
    topicEn: "Complaints",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 4)",
      explanation: "Ôn tập cách viết email/thư khiếu nại và phản hồi - dạng hay gặp trong TOEIC Part 6 & 7. Cấu trúc thư khiếu nại: 1) Mở đầu: nêu vấn đề (I am writing to complain about...), 2) Thân bài: mô tả chi tiết vấn đề, 3) Kết luận: yêu cầu giải pháp (I would like a refund/replacement...). Cấu trúc thư phản hồi: xin lỗi → giải thích → đề xuất giải pháp.",
      structure: "Khiếu nại: Problem → Details → Request | Phản hồi: Apology → Explanation → Solution",
      examples: [
        "I am writing to complain about the service I received.",
        "The product was damaged when it arrived.",
        "I would like a full refund.",
        "We sincerely apologize for the inconvenience."
      ],
      tips: "Trong TOEIC, thường hỏi: 'What is the purpose of the email?' → Mục đích. 'What does the customer want?' → Yêu cầu. 'What will the company do?' → Giải pháp."
    },
    words: [
      {word:'complain', meaning:'phàn nàn, khiếu nại', type:'verb', example:'The customer complained about the service.', viAnswers:['phàn nàn','khiếu nại']},
      {word:'complaint', meaning:'lời phàn nàn, đơn khiếu nại', type:'noun', example:'We received many complaints.', viAnswers:['lời phàn nàn','đơn khiếu nại','khiếu nại']},
      {word:'issue', meaning:'vấn đề', type:'noun', example:'There is an issue with the order.', viAnswers:['vấn đề']},
      {word:'problem', meaning:'vấn đề, trục trặc', type:'noun', example:'We will fix the problem.', viAnswers:['vấn đề','trục trặc']},
      {word:'dissatisfied', meaning:'không hài lòng', type:'adjective', example:'The customer is dissatisfied.', viAnswers:['không hài lòng','bất mãn']},
      {word:'frustrated', meaning:'thất vọng, bực bội', type:'adjective', example:'She was frustrated with the delay.', viAnswers:['thất vọng','bực bội','bực tức']},
      {word:'inconvenience', meaning:'sự bất tiện', type:'noun', example:'We apologize for the inconvenience.', viAnswers:['sự bất tiện','bất tiện']},
      {word:'resolve', meaning:'giải quyết', type:'verb', example:'We will resolve this quickly.', viAnswers:['giải quyết']},
      {word:'apologize', meaning:'xin lỗi', type:'verb', example:'We apologize for the mistake.', viAnswers:['xin lỗi']},
      {word:'compensate', meaning:'bồi thường, đền bù', type:'verb', example:'The company will compensate you.', viAnswers:['bồi thường','đền bù']},
      {word:'refund', meaning:'hoàn tiền', type:'noun / verb', example:'I want a full refund.', viAnswers:['hoàn tiền','hoàn lại tiền']},
      {word:'replace', meaning:'thay thế', type:'verb', example:'We will replace the item.', viAnswers:['thay thế']},
      {word:'exchange', meaning:'đổi', type:'verb / noun', example:'Can I exchange this product?', viAnswers:['đổi','trao đổi']},
      {word:'escalate', meaning:'chuyển lên cấp trên', type:'verb', example:'The issue was escalated to the manager.', viAnswers:['chuyển lên cấp trên','leo thang','nâng lên']},
      {word:'manager', meaning:'quản lý', type:'noun', example:'I want to speak to the manager.', viAnswers:['quản lý','người quản lý']},
      {word:'supervisor', meaning:'giám sát viên', type:'noun', example:'The supervisor handled the complaint.', viAnswers:['giám sát viên','người giám sát']},
      {word:'response', meaning:'phản hồi', type:'noun', example:'We need a quick response.', viAnswers:['phản hồi','câu trả lời']},
      {word:'follow', meaning:'theo dõi, tiếp tục', type:'verb', example:'We will follow up on your case.', viAnswers:['theo dõi','tiếp tục','theo']},
      {word:'investigate', meaning:'điều tra', type:'verb', example:'We will investigate the matter.', viAnswers:['điều tra']},
      {word:'feedback', meaning:'phản hồi, ý kiến', type:'noun', example:'Your feedback is important.', viAnswers:['phản hồi','ý kiến','góp ý']},
      {word:'improve', meaning:'cải thiện', type:'verb', example:'We will improve our service.', viAnswers:['cải thiện','cải tiến']},
      {word:'prevent', meaning:'ngăn chặn, phòng ngừa', type:'verb', example:'We will prevent this from happening again.', viAnswers:['ngăn chặn','phòng ngừa']},
      {word:'recur', meaning:'tái diễn', type:'verb', example:'The problem must not recur.', viAnswers:['tái diễn','xảy ra lại','lặp lại']},
      {word:'satisfaction', meaning:'sự hài lòng', type:'noun', example:'Customer satisfaction is our goal.', viAnswers:['sự hài lòng','hài lòng']},
      {word:'guarantee', meaning:'bảo đảm, cam kết', type:'noun / verb', example:'We guarantee high quality.', viAnswers:['bảo đảm','cam kết','đảm bảo']}
    ]
  },
  {
    day: 56,
    topic: "Lễ kỷ niệm / Chúc mừng",
    topicEn: "Celebrations",
    phase: 3,
    isReview: false,
    reviewDays: [],
    grammar: {
      title: "Mixed Practice - Tổng hợp ngữ pháp (Phần 5)",
      explanation: "Ôn tập toàn diện tất cả ngữ pháp đã học trong 56 ngày. Checklist cuối cùng: ✓ Từ loại (noun, verb, adj, adv), ✓ Thì động từ (12 thì), ✓ Giới từ (in, on, at, by, for, with...), ✓ Liên từ (and, but, because, although...), ✓ Đại từ (I, me, my, mine, myself...), ✓ Câu bị động (be + V3), ✓ So sánh (more/most, -er/-est, as...as).",
      structure: "Ôn tập toàn bộ → Làm bài tập tổng hợp → Sửa lỗi → Ghi nhớ",
      examples: [
        "The ___ ceremony was held at the hotel. (award - từ loại)",
        "They ___ the company's 10th anniversary. (celebrated - thì quá khứ đơn)",
        "The event was ___ by the marketing team. (organized - bị động)",
        "This year's celebration is ___ than last year's. (bigger - so sánh hơn)"
      ],
      tips: "Trước ngày thi, tập trung vào những điểm ngữ pháp mình HAY SAI nhất. Làm lại các bài tập đã sai. Ghi nhớ bằng cách viết lại câu đúng 3 lần."
    },
    words: [
      {word:'celebrate', meaning:'ăn mừng, kỷ niệm', type:'verb', example:'We celebrate our success.', viAnswers:['ăn mừng','kỷ niệm','chúc mừng']},
      {word:'congratulate', meaning:'chúc mừng', type:'verb', example:'I congratulate you on your promotion.', viAnswers:['chúc mừng']},
      {word:'achievement', meaning:'thành tích, thành tựu', type:'noun', example:'This is a great achievement.', viAnswers:['thành tích','thành tựu']},
      {word:'milestone', meaning:'cột mốc quan trọng', type:'noun', example:'This is a major milestone.', viAnswers:['cột mốc quan trọng','cột mốc']},
      {word:'award', meaning:'giải thưởng', type:'noun', example:'She received an award.', viAnswers:['giải thưởng']},
      {word:'ceremony', meaning:'buổi lễ, nghi lễ', type:'noun', example:'The ceremony was formal.', viAnswers:['buổi lễ','nghi lễ','lễ']},
      {word:'reception', meaning:'tiệc chiêu đãi', type:'noun', example:'The reception is at 6 PM.', viAnswers:['tiệc chiêu đãi','tiệc tiếp tân','lễ tân']},
      {word:'toast', meaning:'nâng cốc chúc mừng', type:'noun / verb', example:'He made a toast to the team.', viAnswers:['nâng cốc chúc mừng','nâng cốc','chúc mừng']},
      {word:'gift', meaning:'quà tặng', type:'noun', example:'She gave me a gift.', viAnswers:['quà tặng','quà','món quà']},
      {word:'present', meaning:'quà, hiện tại, có mặt', type:'noun / adjective', example:'Thank you for the present.', viAnswers:['quà','hiện tại','có mặt','quà tặng']},
      {word:'surprise', meaning:'bất ngờ, ngạc nhiên', type:'noun / verb', example:'It was a big surprise!', viAnswers:['bất ngờ','ngạc nhiên','sự bất ngờ']},
      {word:'gather', meaning:'tụ họp, tập hợp', type:'verb', example:'Everyone gathered for the party.', viAnswers:['tụ họp','tập hợp','tụ tập']},
      {word:'reunion', meaning:'buổi họp mặt', type:'noun', example:'The family reunion was fun.', viAnswers:['buổi họp mặt','họp mặt','đoàn tụ']},
      {word:'tradition', meaning:'truyền thống', type:'noun', example:'It is a family tradition.', viAnswers:['truyền thống']},
      {word:'custom', meaning:'phong tục, tập quán', type:'noun', example:'This is a local custom.', viAnswers:['phong tục','tập quán']},
      {word:'holiday', meaning:'ngày lễ, kỳ nghỉ', type:'noun', example:'Monday is a public holiday.', viAnswers:['ngày lễ','kỳ nghỉ']},
      {word:'vacation', meaning:'kỳ nghỉ', type:'noun', example:'We are on vacation next week.', viAnswers:['kỳ nghỉ','nghỉ phép']},
      {word:'memorable', meaning:'đáng nhớ', type:'adjective', example:'It was a memorable day.', viAnswers:['đáng nhớ']},
      {word:'special', meaning:'đặc biệt', type:'adjective', example:'This is a special occasion.', viAnswers:['đặc biệt']},
      {word:'occasion', meaning:'dịp', type:'noun', example:'It was a happy occasion.', viAnswers:['dịp','sự kiện']},
      {word:'honor', meaning:'vinh danh, tôn vinh', type:'verb / noun', example:'We honor our teachers.', viAnswers:['vinh danh','tôn vinh','danh dự']},
      {word:'recognize', meaning:'công nhận, ghi nhận', type:'verb', example:'The company recognized her efforts.', viAnswers:['công nhận','ghi nhận','nhận ra']},
      {word:'appreciate', meaning:'trân trọng, đánh giá cao', type:'verb', example:'I appreciate your help.', viAnswers:['trân trọng','đánh giá cao','cảm kích']},
      {word:'grateful', meaning:'biết ơn', type:'adjective', example:'I am very grateful.', viAnswers:['biết ơn']},
      {word:'cherish', meaning:'trân quý, nâng niu', type:'verb', example:'We cherish these memories.', viAnswers:['trân quý','nâng niu','trân trọng']}
    ]
  },
  {
    day: 57,
    topic: "Bài thi thử",
    topicEn: "Practice Test",
    phase: 3,
    isReview: true,
    reviewDays: [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
    grammar: {
      title: "Bài thi thử TOEIC",
      explanation: "Hôm nay bạn sẽ làm bài thi thử TOEIC để đánh giá trình độ hiện tại. Hãy làm bài trong điều kiện giống thi thật: 1) Không sử dụng từ điển, 2) Tính giờ nghiêm túc (Listening: 45 phút, Reading: 75 phút), 3) Không dừng lại quá lâu ở câu khó, 4) Ghi lại các câu sai để ôn tập.",
      structure: "",
      examples: [],
      tips: "Làm bài thi thử, chữa lỗi, ghi lại lỗi sai. Tập trung vào những phần còn yếu."
    },
    words: []
  },
  {
    day: 58,
    topic: "Ôn tập lỗi sai",
    topicEn: "Review Mistakes",
    phase: 3,
    isReview: true,
    reviewDays: [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
    grammar: {
      title: "Ôn tập lỗi sai",
      explanation: "Xem lại tất cả các lỗi sai từ bài thi thử ngày 57. Phân loại lỗi sai theo nhóm: 1) Lỗi từ vựng: học lại từ đã quên, 2) Lỗi ngữ pháp: ôn lại quy tắc, 3) Lỗi nghe: luyện nghe lại đoạn bị sai, 4) Lỗi đọc hiểu: luyện đọc lại bài. Ghi chú lỗi vào sổ tay để tránh lặp lại.",
      structure: "",
      examples: [],
      tips: "Làm bài tập, chữa lỗi, ghi lại lỗi sai. Ôn lại từ vựng các ngày trước."
    },
    words: []
  },
  {
    day: 59,
    topic: "Ôn tập tổng kết",
    topicEn: "Final Review",
    phase: 3,
    isReview: true,
    reviewDays: [1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
    grammar: {
      title: "Ôn tập tổng kết toàn bộ khóa học",
      explanation: "Đây là ngày ôn tập tổng kết toàn bộ 60 ngày học. Hãy: 1) Ôn lại tất cả từ vựng từ ngày 1 đến ngày 56, 2) Làm lại các bài tập ngữ pháp khó, 3) Luyện nghe 1-2 bài TOEIC hoàn chỉnh, 4) Đọc lại các dạng bài Reading Part 5, 6, 7, 5) Ghi nhớ các mẹo làm bài thi.",
      structure: "",
      examples: [],
      tips: "Làm bài tập, chữa lỗi, ghi lại lỗi sai. Ôn lại tất cả từ vựng và ngữ pháp đã học."
    },
    words: []
  },
  {
    day: 60,
    topic: "Chuẩn bị thi",
    topicEn: "Test Preparation",
    phase: 3,
    isReview: true,
    reviewDays: [1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56],
    grammar: {
      title: "Chuẩn bị trước ngày thi",
      explanation: "Ngày cuối cùng trước kỳ thi TOEIC. Checklist chuẩn bị: 1) ĐÊM TRƯỚC: ngủ đủ giấc (7-8 tiếng), chuẩn bị giấy tờ (CMND/CCCD, phiếu dự thi), bút chì 2B, gôm. 2) SÁNG THI: ăn sáng nhẹ, đến sớm 30 phút, giữ bình tĩnh. 3) KHI THI: quản lý thời gian, không dừng quá lâu ở câu khó, tô đáp án cẩn thận. 4) CHIẾN LƯỢC: Listening - đọc trước câu hỏi, Reading - làm Part 5 trước (nhanh), dành thời gian cho Part 7.",
      structure: "",
      examples: [],
      tips: "Nghỉ ngơi đầy đủ, tự tin vào bản thân. Bạn đã chuẩn bị tốt trong 60 ngày qua. Chúc bạn thi tốt! 🎯"
    },
    words: []
  }
];
